#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
from typing import Iterable


def write_output(path: Path, tool: str, inputs: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix == ".json":
        payload = {"tool": tool, "inputs": list(inputs)}
        path.write_text(json.dumps(payload, indent=2))
    elif path.suffix == ".csv":
        path.write_text("variant_id,score\nplaceholder,0.0\n")
    else:
        path.write_text(f"Generated by {tool}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Stub runner for pipeline tools.")
    parser.add_argument("tool", help="Tool name to simulate.")
    parser.add_argument("--input", action="append", default=[], dest="inputs")
    parser.add_argument("--output", action="append", default=[], dest="outputs")
    args = parser.parse_args()

    if not args.outputs:
        raise SystemExit("No outputs provided to run_tool.py")

    for output in args.outputs:
        write_output(Path(output), args.tool, args.inputs)


if __name__ == "__main__":
    main()
