-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.compute
-- phase: tables

CREATE TABLE compute_source_manifests (
    manifest_id TEXT PRIMARY KEY,
    request_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_revision_execution_requests(request_id)
        ON DELETE RESTRICT,
    workspace_id TEXT NOT NULL,
    source_commit TEXT NOT NULL,
    source_tree TEXT NOT NULL,
    lfs_closure_manifest_digest TEXT NOT NULL,
    binding_digest TEXT NOT NULL,
    repository_policy_digest TEXT NOT NULL,
    target_inventory_generation INTEGER NOT NULL
        CHECK (target_inventory_generation > 0),
    target_inventory_digest TEXT NOT NULL,
    owner_identity_digest TEXT NOT NULL,
    entries_json TEXT NOT NULL CHECK (
        json_valid(entries_json) AND json_array_length(entries_json) > 0
    ),
    created_at TEXT NOT NULL,
    manifest_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'compute_source_manifest@2'
        CHECK (schema_version = 'compute_source_manifest@2')
);

CREATE TABLE session_run_records (
    run_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    invocation_id TEXT NOT NULL REFERENCES engine_invocations(invocation_id) ON DELETE CASCADE,
    approval_id TEXT REFERENCES approval_requests(approval_id) ON DELETE SET NULL,
    engine_name TEXT NOT NULL,
    runner_run_id TEXT NOT NULL,
    status TEXT NOT NULL,
    execution_mode TEXT NOT NULL,
    remote_run_dir TEXT NOT NULL,
    summary TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    finished_at TEXT
);

CREATE TABLE workspace_external_job_handles (
    handle_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL UNIQUE,
    operation_id TEXT NOT NULL UNIQUE,
    dispatch_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_job_dispatch_intents(dispatch_id) ON DELETE RESTRICT,
    runner_run_id TEXT NOT NULL UNIQUE,
    job_root_token TEXT NOT NULL UNIQUE,
    target_profile_digest TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    remote_workspace_generation INTEGER NOT NULL
        CHECK (remote_workspace_generation > 0),
    source_commit TEXT NOT NULL,
    source_manifest_digest TEXT NOT NULL,
    backend TEXT NOT NULL CHECK (backend IN ('direct', 'slurm')),
    raw_handle_ciphertext TEXT NOT NULL,
    acceptance_receipt_digest TEXT NOT NULL UNIQUE,
    accepted_at TEXT NOT NULL,
    handle_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'external_job_handle@1'
        CHECK (schema_version = 'external_job_handle@1')
);

CREATE TABLE workspace_external_job_observations (
    observation_id TEXT PRIMARY KEY,
    handle_id TEXT NOT NULL
        REFERENCES workspace_external_job_handles(handle_id) ON DELETE RESTRICT,
    execution_id TEXT NOT NULL,
    dispatch_id TEXT NOT NULL,
    observation_index INTEGER NOT NULL CHECK (observation_index > 0),
    state TEXT NOT NULL CHECK (
        state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled', 'unknown')
    ),
    exit_code INTEGER,
    terminal_receipt_digest TEXT UNIQUE,
    bounded_stdout TEXT,
    bounded_stderr TEXT,
    observed_at TEXT NOT NULL,
    observation_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'external_job_observation@1'
        CHECK (schema_version = 'external_job_observation@1'),
    UNIQUE(handle_id, observation_index),
    CHECK (
        (state IN ('succeeded', 'failed', 'cancelled')
         AND terminal_receipt_digest IS NOT NULL)
        OR
        (state NOT IN ('succeeded', 'failed', 'cancelled')
         AND terminal_receipt_digest IS NULL)
    )
);

CREATE TABLE workspace_job_cancellation_intents (
    cancellation_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL UNIQUE,
    handle_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_external_job_handles(handle_id) ON DELETE RESTRICT,
    execution_state_version INTEGER NOT NULL CHECK (execution_state_version > 0),
    execution_fencing_token INTEGER NOT NULL CHECK (execution_fencing_token >= 0),
    idempotency_key TEXT NOT NULL UNIQUE,
    reason_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    intent_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_job_cancellation_intent@1'
        CHECK (schema_version = 'workspace_job_cancellation_intent@1')
);

CREATE TABLE workspace_job_cancellation_receipts (
    receipt_id TEXT PRIMARY KEY,
    cancellation_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_job_cancellation_intents(cancellation_id)
        ON DELETE RESTRICT,
    handle_id TEXT NOT NULL UNIQUE,
    cancellation_requested INTEGER NOT NULL CHECK (cancellation_requested = 1),
    terminal_settlement_proven INTEGER NOT NULL CHECK (terminal_settlement_proven = 0),
    backend_receipt_digest TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_job_cancellation_receipt@1'
        CHECK (schema_version = 'workspace_job_cancellation_receipt@1')
);

CREATE TABLE workspace_job_dispatch_intents (
    dispatch_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL UNIQUE
        REFERENCES controlled_operation_execution_records(execution_id)
        ON DELETE RESTRICT,
    operation_id TEXT NOT NULL UNIQUE
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    execution_state_version INTEGER NOT NULL CHECK (execution_state_version > 0),
    execution_fencing_token INTEGER NOT NULL CHECK (execution_fencing_token >= 0),
    request_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_revision_execution_requests(request_id)
        ON DELETE RESTRICT,
    request_digest TEXT NOT NULL,
    runner_run_id TEXT NOT NULL UNIQUE,
    workspace_id TEXT NOT NULL,
    remote_workspace_generation INTEGER NOT NULL
        CHECK (remote_workspace_generation > 0),
    source_manifest_digest TEXT NOT NULL,
    selected_mode TEXT NOT NULL CHECK (selected_mode IN ('ssh', 'sbatch')),
    command_digest TEXT NOT NULL,
    resource_digest TEXT NOT NULL,
    target_profile_digest TEXT NOT NULL,
    scheduler_marker TEXT NOT NULL UNIQUE,
    payload_digest TEXT NOT NULL,
    absolute_deadline TEXT NOT NULL,
    created_at TEXT NOT NULL,
    intent_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_job_dispatch_intent@1'
        CHECK (schema_version = 'workspace_job_dispatch_intent@1')
);

CREATE TABLE workspace_job_result_revision_links (
    link_id TEXT PRIMARY KEY,
    result_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_job_results(result_id) ON DELETE RESTRICT,
    checkpoint_id TEXT NOT NULL UNIQUE
        REFERENCES verified_workspace_checkpoint_records(checkpoint_id)
        ON DELETE RESTRICT,
    workspace_id TEXT NOT NULL,
    result_commit TEXT NOT NULL,
    result_tree TEXT NOT NULL,
    lfs_closure_manifest_digest TEXT NOT NULL,
    linked_by_agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    linked_at TEXT NOT NULL,
    link_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_job_result_revision_link@1'
        CHECK (schema_version = 'workspace_job_result_revision_link@1')
);

CREATE TABLE workspace_job_results (
    result_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL UNIQUE,
    operation_id TEXT NOT NULL UNIQUE,
    handle_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_external_job_handles(handle_id) ON DELETE RESTRICT,
    runner_run_id TEXT NOT NULL UNIQUE,
    terminal_observation_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_external_job_observations(observation_id)
        ON DELETE RESTRICT,
    terminal_observation_digest TEXT NOT NULL,
    terminal_state TEXT NOT NULL CHECK (
        terminal_state IN ('succeeded', 'failed', 'cancelled')
    ),
    exit_code INTEGER,
    source_commit TEXT NOT NULL,
    source_manifest_digest TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    remote_workspace_generation INTEGER NOT NULL
        CHECK (remote_workspace_generation > 0),
    job_root_token TEXT NOT NULL,
    cwd TEXT NOT NULL,
    command_digest TEXT NOT NULL,
    resource_digest TEXT NOT NULL,
    target_profile_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    result_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_job_result@1'
        CHECK (schema_version = 'workspace_job_result@1')
);

CREATE TABLE workspace_revision_clean_observations (
    observation_id TEXT PRIMARY KEY,
    request_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_revision_execution_requests(request_id)
        ON DELETE RESTRICT,
    workspace_id TEXT NOT NULL,
    remote_workspace_generation INTEGER NOT NULL
        CHECK (remote_workspace_generation > 0),
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL
        CHECK (repository_binding_version > 0),
    source_commit TEXT NOT NULL,
    source_tree TEXT NOT NULL,
    lfs_closure_manifest_digest TEXT NOT NULL,
    head_matches INTEGER NOT NULL CHECK (head_matches IN (0, 1)),
    index_clean INTEGER NOT NULL CHECK (index_clean IN (0, 1)),
    tracked_tree_clean INTEGER NOT NULL CHECK (tracked_tree_clean IN (0, 1)),
    untracked_policy_clean INTEGER NOT NULL CHECK (untracked_policy_clean IN (0, 1)),
    attributes_digest TEXT NOT NULL,
    cwd_present INTEGER NOT NULL CHECK (cwd_present IN (0, 1)),
    observed_at TEXT NOT NULL,
    observation_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_revision_clean_observation@1'
        CHECK (schema_version = 'workspace_revision_clean_observation@1'),
    CHECK (
        head_matches = 1 AND index_clean = 1 AND tracked_tree_clean = 1
        AND untracked_policy_clean = 1 AND cwd_present = 1
    )
);

CREATE TABLE "workspace_revision_execution_requests" ("request_id" TEXT PRIMARY KEY, "execution_id" TEXT NOT NULL, "operation_id" TEXT NOT NULL, "operation_digest" TEXT NOT NULL, "session_id" TEXT NOT NULL, "executor_agent_member_id" TEXT NOT NULL, "capability_lease_id" TEXT NOT NULL, "capability_lease_version" INTEGER NOT NULL, "remote_workspace_generation" INTEGER NOT NULL, "repository_binding_id" TEXT NOT NULL, "repository_binding_version" INTEGER NOT NULL, "source_class" TEXT NOT NULL, "source_revision_id" TEXT NOT NULL, "source_ref" TEXT NOT NULL, "source_commit" TEXT NOT NULL, "source_tree" TEXT NOT NULL, "lfs_closure_manifest_digest" TEXT NOT NULL, "clean_observation_digest" TEXT NOT NULL, "cwd" TEXT NOT NULL, "command_json" TEXT NOT NULL, "command_digest" TEXT NOT NULL, "environment_policy_digest" TEXT NOT NULL, "resources_json" TEXT NOT NULL, "resource_digest" TEXT NOT NULL, "requested_mode" TEXT NOT NULL, "target_profile_id" TEXT NOT NULL, "target_profile_digest" TEXT NOT NULL, "runner_policy_digest" TEXT NOT NULL, "runtime_identity_digest" TEXT NOT NULL, "scientific_attempt_id" TEXT, "scientific_attempt_state_version" INTEGER, "scientific_admission_request_id" TEXT, "scientific_admission_request_digest" TEXT, "scientific_source_envelope_id" TEXT, "scientific_workflow_contract_digest" TEXT, "scientific_scope_digest" TEXT, "scientific_effect_class_digest" TEXT, "scientific_hpc_target_digest" TEXT, "operation_approval_digest" TEXT, "absolute_deadline" TEXT NOT NULL, "created_at" TEXT NOT NULL, "request_digest" TEXT NOT NULL, "schema_version" TEXT NOT NULL DEFAULT 'workspace_revision_execution_request@1');
