-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.hpc
-- phase: tables

CREATE TABLE executor_hpc_credential_claims (
    claim_id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL
        REFERENCES executor_hpc_workspace_records(workspace_id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    executor_agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    local_workspace_generation INTEGER NOT NULL CHECK (local_workspace_generation > 0),
    remote_workspace_generation INTEGER NOT NULL CHECK (remote_workspace_generation > 0),
    target_profile_id TEXT NOT NULL,
    target_profile_digest TEXT NOT NULL,
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    capability_lease_version INTEGER NOT NULL CHECK (capability_lease_version > 0),
    credential_provider_id TEXT NOT NULL,
    authenticator_id TEXT NOT NULL,
    login_alias TEXT NOT NULL,
    remote_workspace_path TEXT NOT NULL,
    remote_root_digest TEXT NOT NULL,
    os_principal_identity_digest TEXT NOT NULL,
    operations_json TEXT NOT NULL CHECK (json_valid(operations_json)),
    credential_fingerprint TEXT NOT NULL UNIQUE,
    authentication_receipt_digest TEXT NOT NULL,
    issued_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked_at TEXT,
    schema_version TEXT NOT NULL DEFAULT 'executor_hpc_credential_claim@1'
        CHECK (schema_version = 'executor_hpc_credential_claim@1')
);

CREATE TABLE executor_hpc_target_qualifications (
    target_profile_id TEXT PRIMARY KEY,
    target_profile_digest TEXT NOT NULL UNIQUE,
    root_policy_digest TEXT NOT NULL,
    os_principal_policy_id TEXT NOT NULL,
    credential_provider_id TEXT NOT NULL,
    authenticator_id TEXT NOT NULL,
    login_alias TEXT NOT NULL,
    workspace_root TEXT NOT NULL,
    sidecar_root_digest TEXT NOT NULL,
    inventory_generation INTEGER NOT NULL CHECK (inventory_generation > 0),
    inventory_digest TEXT NOT NULL,
    native_positive_proof_digest TEXT NOT NULL,
    native_negative_proof_digest TEXT NOT NULL,
    scheduler_submit_enabled INTEGER NOT NULL DEFAULT 0
        CHECK (scheduler_submit_enabled = 0),
    activated INTEGER NOT NULL CHECK (activated IN (0, 1)),
    qualified_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'executor_hpc_target_qualification@2'
        CHECK (schema_version = 'executor_hpc_target_qualification@2')
);

CREATE TABLE executor_hpc_workspace_cleanup_intents (
    cleanup_intent_id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL UNIQUE
        REFERENCES executor_hpc_workspace_records(workspace_id) ON DELETE RESTRICT,
    workspace_state_version INTEGER NOT NULL CHECK (workspace_state_version > 0),
    runner_handle TEXT NOT NULL,
    remote_root_digest TEXT NOT NULL,
    settlement_proof_digest TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    intent_digest TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'executor_hpc_workspace_cleanup_intent@1'
        CHECK (schema_version = 'executor_hpc_workspace_cleanup_intent@1')
);

CREATE TABLE executor_hpc_workspace_cleanup_receipts (
    cleanup_receipt_id TEXT PRIMARY KEY,
    cleanup_intent_id TEXT NOT NULL UNIQUE
        REFERENCES executor_hpc_workspace_cleanup_intents(cleanup_intent_id)
        ON DELETE RESTRICT,
    cleanup_intent_digest TEXT NOT NULL,
    workspace_id TEXT NOT NULL UNIQUE
        REFERENCES executor_hpc_workspace_records(workspace_id) ON DELETE RESTRICT,
    runner_handle TEXT NOT NULL,
    remote_root_digest TEXT NOT NULL,
    disposition TEXT NOT NULL CHECK (disposition IN ('deleted', 'retained', 'uncertain')),
    unsettled_effect_count INTEGER NOT NULL CHECK (unsettled_effect_count >= 0),
    settlement_proof_digest TEXT NOT NULL,
    isolation_cleanup_receipt_digest TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'executor_hpc_workspace_cleanup_receipt@1'
        CHECK (schema_version = 'executor_hpc_workspace_cleanup_receipt@1')
);

CREATE TABLE executor_hpc_workspace_provision_intents (
    intent_id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL UNIQUE,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    executor_agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    local_workspace_id TEXT NOT NULL
        REFERENCES agent_git_workspace_records(workspace_id) ON DELETE RESTRICT,
    local_workspace_generation INTEGER NOT NULL CHECK (local_workspace_generation > 0),
    remote_workspace_generation INTEGER NOT NULL CHECK (remote_workspace_generation > 0),
    repository_binding_id TEXT NOT NULL
        REFERENCES project_repository_binding_versions(binding_id) ON DELETE RESTRICT,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version > 0),
    repository_id TEXT NOT NULL,
    base_commit TEXT NOT NULL,
    target_profile_id TEXT NOT NULL
        REFERENCES executor_hpc_target_qualifications(target_profile_id) ON DELETE RESTRICT,
    target_profile_digest TEXT NOT NULL,
    root_policy_digest TEXT NOT NULL,
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    capability_lease_version INTEGER NOT NULL CHECK (capability_lease_version > 0),
    idempotency_key TEXT NOT NULL,
    absolute_deadline TEXT NOT NULL,
    intent_digest TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'executor_hpc_workspace_provision_intent@1'
        CHECK (schema_version = 'executor_hpc_workspace_provision_intent@1'),
    UNIQUE (session_id, executor_agent_member_id, idempotency_key),
    UNIQUE (
        session_id,
        executor_agent_member_id,
        local_workspace_generation,
        target_profile_id,
        remote_workspace_generation
    )
);

CREATE TABLE executor_hpc_workspace_provision_receipts (
    receipt_id TEXT PRIMARY KEY,
    intent_id TEXT NOT NULL UNIQUE
        REFERENCES executor_hpc_workspace_provision_intents(intent_id) ON DELETE RESTRICT,
    intent_digest TEXT NOT NULL,
    workspace_id TEXT NOT NULL UNIQUE
        REFERENCES executor_hpc_workspace_records(workspace_id) ON DELETE RESTRICT,
    runner_handle TEXT NOT NULL UNIQUE,
    target_profile_digest TEXT NOT NULL,
    login_alias TEXT NOT NULL,
    remote_workspace_path TEXT NOT NULL UNIQUE,
    remote_root_digest TEXT NOT NULL UNIQUE,
    repository_remote_digest TEXT NOT NULL,
    clone_head_commit TEXT NOT NULL,
    owner_identity_digest TEXT NOT NULL,
    os_principal_identity_digest TEXT NOT NULL,
    isolation_receipt_digest TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'executor_hpc_workspace_provision_receipt@1'
        CHECK (schema_version = 'executor_hpc_workspace_provision_receipt@1')
);

CREATE TABLE executor_hpc_workspace_records (
    workspace_id TEXT PRIMARY KEY REFERENCES executor_hpc_workspace_provision_intents(workspace_id)
        ON DELETE RESTRICT,
    project_id TEXT NOT NULL,
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version > 0),
    repository_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    executor_agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    executor_agent_id TEXT NOT NULL,
    local_workspace_id TEXT NOT NULL
        REFERENCES agent_git_workspace_records(workspace_id) ON DELETE RESTRICT,
    local_workspace_generation INTEGER NOT NULL CHECK (local_workspace_generation > 0),
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    capability_lease_version INTEGER NOT NULL CHECK (capability_lease_version > 0),
    target_profile_id TEXT NOT NULL
        REFERENCES executor_hpc_target_qualifications(target_profile_id) ON DELETE RESTRICT,
    target_profile_digest TEXT NOT NULL,
    remote_workspace_generation INTEGER NOT NULL CHECK (remote_workspace_generation > 0),
    provision_intent_id TEXT NOT NULL UNIQUE
        REFERENCES executor_hpc_workspace_provision_intents(intent_id) ON DELETE RESTRICT,
    runner_handle TEXT UNIQUE,
    provision_receipt_id TEXT UNIQUE,
    login_alias TEXT,
    remote_workspace_path TEXT,
    remote_root_digest TEXT,
    os_principal_identity_digest TEXT,
    isolation_receipt_digest TEXT,
    state TEXT NOT NULL CHECK (state IN (
        'provisioning',
        'ready',
        'invalid',
        'missing',
        'provision_reconciliation_required',
        'retention_eligible',
        'cleaning',
        'cleanup_reconciliation_required',
        'cleaned'
    )),
    state_version INTEGER NOT NULL CHECK (state_version > 0),
    invalid_reason TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'executor_hpc_workspace@1'
        CHECK (schema_version = 'executor_hpc_workspace@1'),
    FOREIGN KEY (session_id, executor_agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    UNIQUE (
        session_id,
        executor_agent_member_id,
        local_workspace_generation,
        target_profile_id,
        remote_workspace_generation
    ),
    CHECK (
        (state IN ('provisioning', 'provision_reconciliation_required')
         AND runner_handle IS NULL
         AND provision_receipt_id IS NULL
         AND login_alias IS NULL
         AND remote_workspace_path IS NULL
         AND remote_root_digest IS NULL
         AND os_principal_identity_digest IS NULL
         AND isolation_receipt_digest IS NULL)
        OR state NOT IN ('provisioning', 'provision_reconciliation_required')
    ),
    CHECK (
        (state = 'ready'
         AND runner_handle IS NOT NULL
         AND provision_receipt_id IS NOT NULL
         AND login_alias IS NOT NULL
         AND remote_workspace_path IS NOT NULL
         AND remote_root_digest IS NOT NULL
         AND os_principal_identity_digest IS NOT NULL
         AND isolation_receipt_digest IS NOT NULL)
        OR state <> 'ready'
    )
);

CREATE TABLE scheduler_credential_occurrences (
    occurrence_id TEXT PRIMARY KEY,
    dispatch_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_job_dispatch_intents(dispatch_id) ON DELETE RESTRICT,
    execution_id TEXT NOT NULL UNIQUE,
    execution_fencing_token INTEGER NOT NULL CHECK (execution_fencing_token >= 0),
    target_profile_digest TEXT NOT NULL,
    reservation_nonce_digest TEXT NOT NULL UNIQUE,
    scheduler_marker TEXT NOT NULL UNIQUE,
    payload_digest TEXT NOT NULL,
    protected_wrapper_audience TEXT NOT NULL,
    credential_fingerprint TEXT UNIQUE,
    authentication_receipt_digest TEXT UNIQUE,
    consumption_receipt_digest TEXT UNIQUE,
    state TEXT NOT NULL CHECK (
        state IN ('reserved', 'issued', 'consumed', 'rejected', 'expired')
    ),
    reserved_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    issued_at TEXT,
    consumed_at TEXT,
    rejection_code TEXT,
    schema_version TEXT NOT NULL DEFAULT 'scheduler_credential_occurrence@1'
        CHECK (schema_version = 'scheduler_credential_occurrence@1'),
    CHECK (
        (state = 'reserved' AND credential_fingerprint IS NULL
         AND authentication_receipt_digest IS NULL AND issued_at IS NULL
         AND consumption_receipt_digest IS NULL
         AND consumed_at IS NULL AND rejection_code IS NULL)
        OR
        (state = 'issued' AND credential_fingerprint IS NOT NULL
         AND authentication_receipt_digest IS NOT NULL AND issued_at IS NOT NULL
         AND consumption_receipt_digest IS NULL
         AND consumed_at IS NULL AND rejection_code IS NULL)
        OR
        (state = 'consumed' AND credential_fingerprint IS NOT NULL
         AND authentication_receipt_digest IS NOT NULL AND issued_at IS NOT NULL
         AND consumption_receipt_digest IS NOT NULL
         AND consumed_at IS NOT NULL AND rejection_code IS NULL)
        OR
        (state IN ('rejected', 'expired') AND rejection_code IS NOT NULL)
    )
);

CREATE TABLE workspace_job_target_qualifications (
    target_profile_id TEXT PRIMARY KEY
        REFERENCES executor_hpc_target_qualifications(target_profile_id)
        ON DELETE RESTRICT,
    target_profile_digest TEXT NOT NULL UNIQUE,
    runner_policy_digest TEXT NOT NULL,
    protected_submit_wrapper_digest TEXT NOT NULL,
    dispatch_ledger_digest TEXT NOT NULL,
    scheduler_credential_provider_id TEXT NOT NULL,
    scheduler_credential_audience TEXT NOT NULL,
    scheduler_marker_policy_digest TEXT NOT NULL,
    scheduler_accounting_proof_digest TEXT NOT NULL,
    ambient_submit_denial_proof_digest TEXT NOT NULL,
    direct_process_ledger_proof_digest TEXT NOT NULL,
    slurm_enabled INTEGER NOT NULL CHECK (slurm_enabled IN (0, 1)),
    direct_enabled INTEGER NOT NULL CHECK (direct_enabled IN (0, 1)),
    qualified_at TEXT NOT NULL,
    qualification_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_job_target_qualification@1'
        CHECK (schema_version = 'workspace_job_target_qualification@1'),
    CHECK (slurm_enabled = 1 OR direct_enabled = 1)
);

CREATE TABLE openzyme_hpc_software_qualification_receipts (
    receipt_id TEXT PRIMARY KEY,
    target_id TEXT NOT NULL,
    capability_id TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json))
);

CREATE TABLE openzyme_hpc_target_toolchain_inventories (
    target_id TEXT NOT NULL,
    generation INTEGER NOT NULL CHECK (generation > 0),
    target_profile_digest TEXT NOT NULL,
    previous_inventory_digest TEXT,
    inventory_digest TEXT NOT NULL UNIQUE,
    valid_until TEXT NOT NULL,
    created_at TEXT NOT NULL,
    published_by_actor_id TEXT NOT NULL,
    published_at TEXT NOT NULL,
    generation_digest TEXT NOT NULL UNIQUE,
    inventory_json TEXT NOT NULL CHECK (json_valid(inventory_json)),
    PRIMARY KEY (target_id, generation),
    UNIQUE (target_id, previous_inventory_digest)
);

CREATE TABLE openzyme_hpc_scheduler_occurrences (
    provider_id TEXT NOT NULL,
    operation_kind TEXT NOT NULL CHECK (operation_kind IN ('submit', 'cancel')),
    operation_id TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    ledger_version INTEGER NOT NULL CHECK (ledger_version > 0),
    opaque_handle_id TEXT,
    raw_scheduler_id TEXT,
    record_digest TEXT NOT NULL UNIQUE,
    record_json TEXT NOT NULL CHECK (json_valid(record_json)),
    updated_at TEXT NOT NULL,
    PRIMARY KEY (provider_id, operation_id),
    UNIQUE (provider_id, opaque_handle_id),
    CHECK (
        (opaque_handle_id IS NULL AND raw_scheduler_id IS NULL)
        OR (operation_kind = 'submit' AND opaque_handle_id IS NOT NULL AND raw_scheduler_id IS NOT NULL)
    )
);
