-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.kernel
-- phase: tables

CREATE TABLE agent_capability_lease_lifecycle_events (
    event_id TEXT PRIMARY KEY,
    lease_id TEXT NOT NULL REFERENCES agent_capability_lease_records(lease_id)
        ON DELETE RESTRICT,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    event_kind TEXT NOT NULL CHECK (event_kind IN ('issued', 'activated', 'revoked')),
    previous_status TEXT CHECK (
        previous_status IS NULL OR previous_status IN (
            'pending_workspace',
            'active',
            'revoked'
        )
    ),
    status TEXT NOT NULL CHECK (status IN ('pending_workspace', 'active', 'revoked')),
    state_version INTEGER NOT NULL CHECK (state_version > 0),
    actor_ref TEXT NOT NULL,
    revocation_scope TEXT CHECK (
        revocation_scope IS NULL OR revocation_scope IN (
            'exact',
            'session',
            'policy',
            'agent',
            'workspace_generation',
            'derived_subtree'
        )
    ),
    revocation_reason TEXT CHECK (
        revocation_reason IS NULL OR revocation_reason IN (
            'explicit',
            'session_ended',
            'policy_invalidated',
            'agent_retired',
            'workspace_replaced',
            'operator_subtree'
        )
    ),
    occurred_at TEXT NOT NULL,
    event_digest TEXT NOT NULL UNIQUE CHECK (
        length(event_digest) = 71
        AND substr(event_digest, 1, 7) = 'sha256:'
        AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    schema_version TEXT NOT NULL DEFAULT 'agent_capability_lease_event@1'
        CHECK (schema_version = 'agent_capability_lease_event@1'),
    UNIQUE (lease_id, state_version),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    CHECK (
        (event_kind = 'issued'
         AND previous_status IS NULL
         AND status = 'pending_workspace'
         AND state_version = 1
         AND revocation_scope IS NULL
         AND revocation_reason IS NULL)
        OR
        (event_kind = 'activated'
         AND previous_status = 'pending_workspace'
         AND status = 'active'
         AND revocation_scope IS NULL
         AND revocation_reason IS NULL)
        OR
        (event_kind = 'revoked'
         AND previous_status IN ('pending_workspace', 'active')
         AND status = 'revoked'
         AND revocation_scope IS NOT NULL
         AND revocation_reason IS NOT NULL)
    )
);

CREATE TABLE agent_capability_lease_records (
    lease_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT,
    workspace_generation INTEGER CHECK (
        workspace_generation IS NULL OR workspace_generation > 0
    ),
    profile TEXT CHECK (profile IS NULL OR profile IN ('general', 'executor')),
    capabilities_json TEXT CHECK (
        capabilities_json IS NULL OR json_valid(capabilities_json)
    ),
    capability_set_digest TEXT CHECK (
        capability_set_digest IS NULL OR (length(capability_set_digest) = 71
        AND substr(capability_set_digest, 1, 7) = 'sha256:'
        AND substr(capability_set_digest, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    target_ids_json TEXT CHECK (
        target_ids_json IS NULL OR (
            json_valid(target_ids_json) AND json_array_length(target_ids_json) > 0
        )
    ),
    target_scope_digest TEXT CHECK (
        target_scope_digest IS NULL OR (length(target_scope_digest) = 71
        AND substr(target_scope_digest, 1, 7) = 'sha256:'
        AND substr(target_scope_digest, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    policy_version TEXT,
    policy_digest TEXT CHECK (
        policy_digest IS NULL OR (length(policy_digest) = 71
        AND substr(policy_digest, 1, 7) = 'sha256:'
        AND substr(policy_digest, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    parent_lease_id TEXT REFERENCES agent_capability_lease_records(lease_id)
        ON DELETE RESTRICT,
    idempotency_key TEXT,
    status TEXT CHECK (
        status IS NULL OR status IN ('pending_workspace', 'active', 'revoked')
    ),
    state_version INTEGER CHECK (state_version IS NULL OR state_version > 0),
    issued_at TEXT NOT NULL,
    updated_at TEXT,
    activated_at TEXT,
    revoked_at TEXT,
    revocation_scope TEXT CHECK (
        revocation_scope IS NULL OR revocation_scope IN (
            'exact',
            'session',
            'policy',
            'agent',
            'workspace_generation',
            'derived_subtree'
        )
    ),
    revocation_reason TEXT CHECK (
        revocation_reason IS NULL OR revocation_reason IN (
            'explicit',
            'session_ended',
            'policy_invalidated',
            'agent_retired',
            'workspace_replaced',
            'operator_subtree'
        )
    ),
    immutable_fingerprint TEXT UNIQUE CHECK (
        immutable_fingerprint IS NULL OR (length(immutable_fingerprint) = 71
        AND substr(immutable_fingerprint, 1, 7) = 'sha256:'
        AND substr(immutable_fingerprint, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    canonical_digest TEXT UNIQUE CHECK (
        canonical_digest IS NULL OR (length(canonical_digest) = 71
        AND substr(canonical_digest, 1, 7) = 'sha256:'
        AND substr(canonical_digest, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    schema_version TEXT DEFAULT 'agent_capability_lease@1'
        CHECK (schema_version IS NULL OR schema_version = 'agent_capability_lease@1'),
    record_kind TEXT NOT NULL DEFAULT 'legacy_capability_lease'
        CHECK (record_kind IN ('legacy_capability_lease', 'agent_authority_lease')),
    authority_grants_json TEXT CHECK (
        authority_grants_json IS NULL OR json_valid(authority_grants_json)
    ),
    authority_generation INTEGER CHECK (
        authority_generation IS NULL OR authority_generation > 0
    ),
    authority_fence INTEGER CHECK (
        authority_fence IS NULL OR authority_fence > 0
    ),
    authority_state TEXT CHECK (
        authority_state IS NULL OR authority_state IN (
            'pending', 'active', 'expired', 'superseded', 'revoked'
        )
    ),
    authority_expires_at TEXT,
    authority_lease_digest TEXT UNIQUE CHECK (
        authority_lease_digest IS NULL OR (length(authority_lease_digest) = 71
        AND substr(authority_lease_digest, 1, 7) = 'sha256:'
        AND substr(authority_lease_digest, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    authority_schema_version TEXT CHECK (
        authority_schema_version IS NULL
        OR authority_schema_version = 'agent_authority_lease@1'
    ),
    UNIQUE (session_id, agent_member_id, workspace_generation),
    UNIQUE (session_id, idempotency_key),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    FOREIGN KEY (
        session_id,
        agent_member_id,
        workspace_generation
    ) REFERENCES workspace_generation_records(
        session_id,
        owner_member_id,
        generation
    ) ON DELETE RESTRICT,
    CHECK (
        record_kind = 'agent_authority_lease'
        OR (profile = 'general'
         AND capabilities_json = '["filesystem_read","filesystem_write","shell_process","git","git_lfs","ordinary_network","upload","download"]')
        OR
        (profile = 'executor'
         AND capabilities_json = '["filesystem_read","filesystem_write","shell_process","git","git_lfs","ordinary_network","upload","download","ssh","rsync_scp","hpc_login_workspace_crud","slurm_operations"]')
    ),
    CHECK (
        record_kind = 'agent_authority_lease'
        OR (status = 'pending_workspace'
         AND state_version = 1
         AND activated_at IS NULL
         AND revoked_at IS NULL
         AND revocation_scope IS NULL
         AND revocation_reason IS NULL)
        OR
        (status = 'active'
         AND state_version = 2
         AND activated_at IS NOT NULL
         AND revoked_at IS NULL
         AND revocation_scope IS NULL
         AND revocation_reason IS NULL)
        OR
        (status = 'revoked'
         AND revoked_at IS NOT NULL
         AND revocation_scope IS NOT NULL
         AND revocation_reason IS NOT NULL
         AND (
             (activated_at IS NULL AND state_version = 2)
             OR
             (activated_at IS NOT NULL AND state_version = 3)
         ))
    ),
    CHECK (
        (record_kind = 'legacy_capability_lease'
         AND agent_id IS NOT NULL
         AND workspace_generation IS NOT NULL
         AND profile IS NOT NULL
         AND capabilities_json IS NOT NULL
         AND capability_set_digest IS NOT NULL
         AND target_ids_json IS NOT NULL
         AND target_scope_digest IS NOT NULL
         AND policy_version IS NOT NULL
         AND policy_digest IS NOT NULL
         AND idempotency_key IS NOT NULL
         AND status IS NOT NULL
         AND state_version IS NOT NULL
         AND updated_at IS NOT NULL
         AND immutable_fingerprint IS NOT NULL
         AND canonical_digest IS NOT NULL
         AND schema_version = 'agent_capability_lease@1'
         AND authority_grants_json IS NULL
         AND authority_generation IS NULL
         AND authority_fence IS NULL
         AND authority_state IS NULL
         AND authority_expires_at IS NULL
         AND authority_lease_digest IS NULL
         AND authority_schema_version IS NULL)
        OR
        (record_kind = 'agent_authority_lease'
         AND profile IS NULL
         AND capabilities_json IS NULL
         AND capability_set_digest IS NULL
         AND target_ids_json IS NULL
         AND target_scope_digest IS NULL
         AND policy_version IS NULL
         AND status IS NULL
         AND state_version IS NULL
         AND activated_at IS NULL
         AND revoked_at IS NULL
         AND revocation_scope IS NULL
         AND revocation_reason IS NULL
         AND immutable_fingerprint IS NULL
         AND canonical_digest IS NULL
         AND schema_version IS NULL
         AND authority_grants_json IS NOT NULL
         AND json_type(authority_grants_json) = 'array'
         AND authority_generation IS NOT NULL
         AND authority_fence IS NOT NULL
         AND authority_state IS NOT NULL
         AND authority_lease_digest IS NOT NULL
         AND authority_schema_version = 'agent_authority_lease@1')
    )
);

CREATE TABLE "agent_members" (
    member_id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    status TEXT NOT NULL,
    parent_agent_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    runtime_state TEXT,
    current_correlation_id TEXT,
    wakeup_reason TEXT,
    last_active_at TEXT,
    idle_since TEXT,
    shutdown_requested_at TEXT, nickname TEXT, display_name TEXT, handle TEXT,
    process_epoch INTEGER NOT NULL DEFAULT 1 CHECK (process_epoch > 0),
    active_authority_lease_id TEXT,
    workspace_generation INTEGER CHECK (
        workspace_generation IS NULL OR workspace_generation > 0
    ),
    owned_task_ids_json TEXT NOT NULL DEFAULT '[]'
        CHECK (json_valid(owned_task_ids_json)),
    retirement_reason TEXT,
    terminal_proof_digest TEXT,
    retirement_settled INTEGER NOT NULL DEFAULT 0
        CHECK (retirement_settled IN (0, 1)),
    retired_at TEXT,
    UNIQUE(session_id, agent_id)
);

CREATE TABLE agent_retirement_cleanup_proofs (
    proof_id TEXT PRIMARY KEY,
    retirement_request_id TEXT NOT NULL UNIQUE
        REFERENCES agent_retirement_requests(request_id) ON DELETE RESTRICT,
    retirement_request_digest TEXT NOT NULL CHECK (
        length(retirement_request_digest) = 71
        AND substr(retirement_request_digest, 1, 7) = 'sha256:'
        AND substr(retirement_request_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    shutdown_request_ref TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    cleanup_proof_digest TEXT NOT NULL CHECK (
        length(cleanup_proof_digest) = 71
        AND substr(cleanup_proof_digest, 1, 7) = 'sha256:'
        AND substr(cleanup_proof_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    reason TEXT NOT NULL CHECK (reason IN (
        'shutdown_completed',
        'operator_shutdown_completed',
        'session_shutdown_completed'
    )),
    observed_at TEXT NOT NULL,
    canonical_digest TEXT NOT NULL UNIQUE CHECK (
        length(canonical_digest) = 71
        AND substr(canonical_digest, 1, 7) = 'sha256:'
        AND substr(canonical_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    schema_version TEXT NOT NULL DEFAULT 'agent_retirement_cleanup_proof@1'
        CHECK (schema_version = 'agent_retirement_cleanup_proof@1'),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT
);

CREATE TABLE agent_retirement_records (
    retirement_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    retirement_request_id TEXT NOT NULL UNIQUE
        REFERENCES agent_retirement_requests(request_id) ON DELETE RESTRICT,
    retirement_request_digest TEXT NOT NULL CHECK (
        length(retirement_request_digest) = 71
        AND substr(retirement_request_digest, 1, 7) = 'sha256:'
        AND substr(retirement_request_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    shutdown_request_ref TEXT NOT NULL,
    cleanup_proof_id TEXT NOT NULL UNIQUE
        REFERENCES agent_retirement_cleanup_proofs(proof_id) ON DELETE RESTRICT,
    cleanup_proof_digest TEXT NOT NULL CHECK (
        length(cleanup_proof_digest) = 71
        AND substr(cleanup_proof_digest, 1, 7) = 'sha256:'
        AND substr(cleanup_proof_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    cleanup_proof_record_digest TEXT NOT NULL CHECK (
        length(cleanup_proof_record_digest) = 71
        AND substr(cleanup_proof_record_digest, 1, 7) = 'sha256:'
        AND substr(cleanup_proof_record_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    actor_ref TEXT NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN (
        'shutdown_completed',
        'operator_shutdown_completed',
        'session_shutdown_completed'
    )),
    retired_at TEXT NOT NULL,
    canonical_digest TEXT NOT NULL UNIQUE CHECK (
        length(canonical_digest) = 71
        AND substr(canonical_digest, 1, 7) = 'sha256:'
        AND substr(canonical_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    schema_version TEXT NOT NULL DEFAULT 'agent_retirement_record@1'
        CHECK (schema_version = 'agent_retirement_record@1'),
    UNIQUE (session_id, agent_member_id),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT
);

CREATE TABLE agent_retirement_requests (
    request_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    shutdown_request_ref TEXT NOT NULL,
    cleanup_provider_id TEXT NOT NULL,
    actor_ref TEXT NOT NULL,
    requested_at TEXT NOT NULL,
    canonical_digest TEXT NOT NULL UNIQUE CHECK (
        length(canonical_digest) = 71
        AND substr(canonical_digest, 1, 7) = 'sha256:'
        AND substr(canonical_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    schema_version TEXT NOT NULL DEFAULT 'agent_retirement_request@1'
        CHECK (schema_version = 'agent_retirement_request@1'),
    UNIQUE (session_id, agent_member_id),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT
);

CREATE TABLE "agent_runtime_signals" (
    signal_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    correlation_id TEXT,
    reason TEXT NOT NULL,
    source_ref TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    claimed_at TEXT,
    completed_at TEXT,
    error_message TEXT,
    claimed_by TEXT,
    claim_expires_at TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, session_lease_token TEXT, session_fencing_token INTEGER, capability_lease_id TEXT
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT, workspace_generation INTEGER CHECK (
        workspace_generation IS NULL OR workspace_generation > 0
    ),
    record_kind TEXT NOT NULL DEFAULT 'legacy_runtime_signal'
        CHECK (record_kind IN ('legacy_runtime_signal', 'kernel_runtime_signal')),
    agent_member_id TEXT REFERENCES agent_members(member_id) ON DELETE CASCADE,
    claim_token TEXT,
    runtime_lease_generation INTEGER,
    capability_lease_digest TEXT,
    process_epoch INTEGER,
    enqueue_command_digest TEXT,
    claim_command_digest TEXT,
    CHECK (
        record_kind = 'legacy_runtime_signal'
        OR (
            agent_member_id IS NOT NULL
            AND capability_lease_digest IS NOT NULL
            AND process_epoch > 0
            AND enqueue_command_digest IS NOT NULL
        )
    ),
    FOREIGN KEY (session_id, agent_id) REFERENCES agent_members(session_id, agent_id) ON DELETE CASCADE
);

CREATE TABLE approval_requests (
    approval_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    kind TEXT NOT NULL,
    requested_action TEXT NOT NULL,
    status TEXT NOT NULL,
    request_ref TEXT,
    resolution_ref TEXT,
    created_at TEXT NOT NULL,
    resolved_at TEXT,
    record_kind TEXT NOT NULL DEFAULT 'legacy_approval_request'
        CHECK (record_kind IN ('legacy_approval_request', 'kernel_approval_request')),
    requester_actor_id TEXT,
    intent_digest TEXT,
    scope_id TEXT,
    reason TEXT,
    expires_at TEXT,
    resolver_actor_id TEXT,
    operation_dispatched INTEGER CHECK (operation_dispatched IN (0, 1)),
    CHECK (
        record_kind = 'legacy_approval_request'
        OR (
            requester_actor_id IS NOT NULL
            AND intent_digest IS NOT NULL
            AND scope_id IS NOT NULL
            AND expires_at IS NOT NULL
            AND operation_dispatched IS NOT NULL
        )
    )
);

CREATE TABLE command_receipt_records (
    command_receipt_id TEXT PRIMARY KEY,
    scope_ref TEXT NOT NULL,
    session_id TEXT REFERENCES sessions(session_id) ON DELETE CASCADE,
    command_type TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    status TEXT NOT NULL,
    response_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    completed_at TEXT NOT NULL,
    CHECK (status = 'completed'),
    UNIQUE(scope_ref, command_type, idempotency_key)
);

CREATE TABLE "continuation_state_records" (
    "continuation_id" TEXT PRIMARY KEY,
    "session_id" TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    "operation_id" TEXT REFERENCES controlled_operation_records(operation_id) ON DELETE CASCADE,
    "sandbox_run_id" TEXT REFERENCES sandbox_run_records(sandbox_run_id) ON DELETE CASCADE,
    "approval_id" TEXT REFERENCES approval_requests(approval_id) ON DELETE CASCADE,
    "status" TEXT,
    "claimed_at" TEXT,
    "claimed_by" TEXT,
    "claim_expires_at" TEXT,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "completed_at" TEXT,
    "error_code" TEXT,
    "error_message" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "originating_signal_id" TEXT,
    "originating_agent_id" TEXT,
    "originating_task_id" TEXT,
    "originating_lane_id" TEXT,
    "originating_tool_call_id" TEXT,
    "originating_invocation_id" TEXT,
    "sandbox_workspace_id" TEXT REFERENCES sandbox_workspace_records(sandbox_workspace_id) ON DELETE RESTRICT,
    "sandbox_runtime_identity" TEXT,
    "process_epoch" INTEGER,
    "resume_strategy" TEXT NOT NULL DEFAULT 'legacy_non_resumable',
    "delivery_state" TEXT NOT NULL DEFAULT 'legacy_unavailable',
    "delivery_generation" INTEGER NOT NULL DEFAULT 0,
    "delivery_result_digest" TEXT,
    "state_version" INTEGER NOT NULL DEFAULT 0,
    "delivery_claim_owner" TEXT,
    "delivery_lease_token" TEXT,
    "delivery_lease_expires_at" TEXT,
    "delivery_fencing_token" INTEGER NOT NULL DEFAULT 0,
    "record_kind" TEXT NOT NULL DEFAULT 'legacy_continuation'
        CHECK (record_kind IN ('legacy_continuation', 'kernel_continuation')),
    "owner_actor_id" TEXT,
    "source_version" TEXT,
    "source_ref" TEXT,
    "source_digest" TEXT,
    "recipient_actor_id" TEXT REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    "kernel_state" TEXT,
    "delivery_attempt" INTEGER,
    "delivery_receipt_digest" TEXT,
    "failure_id" TEXT,
    "task_transition_performed" INTEGER CHECK (
        task_transition_performed IN (0, 1)
    ),
    CHECK (
        (record_kind = 'legacy_continuation'
         AND operation_id IS NOT NULL
         AND sandbox_run_id IS NOT NULL
         AND approval_id IS NOT NULL
         AND status IS NOT NULL)
        OR
        (record_kind = 'kernel_continuation'
         AND owner_actor_id IS NOT NULL
         AND source_version IS NOT NULL
         AND source_ref IS NOT NULL
         AND source_digest IS NOT NULL
         AND recipient_actor_id IS NOT NULL
         AND process_epoch > 0
         AND kernel_state IN ('ready', 'delivered', 'failed')
         AND delivery_attempt >= 0
         AND task_transition_performed = 0)
    )
);

CREATE TABLE controlled_operation_dispatch_requests (
    request_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL UNIQUE
        REFERENCES controlled_operation_execution_records(execution_id) ON DELETE CASCADE,
    operation_id TEXT NOT NULL
        REFERENCES controlled_operation_records(operation_id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    schema_version TEXT NOT NULL DEFAULT 'controlled_operation_dispatch_request@1'
        CHECK (schema_version = 'controlled_operation_dispatch_request@1'),
    request_digest TEXT NOT NULL,
    request_envelope_json TEXT NOT NULL CHECK (json_valid(request_envelope_json)),
    request_size_bytes INTEGER NOT NULL
        CHECK (request_size_bytes > 0 AND request_size_bytes <= 4194304),
    created_at TEXT NOT NULL
);

CREATE TABLE controlled_operation_execution_events (
    event_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL
        REFERENCES controlled_operation_execution_records(execution_id) ON DELETE CASCADE,
    operation_id TEXT NOT NULL
        REFERENCES controlled_operation_records(operation_id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    schema_version TEXT NOT NULL DEFAULT 'controlled_operation_execution_event@1'
        CHECK (schema_version = 'controlled_operation_execution_event@1'),
    state_version INTEGER NOT NULL CHECK (state_version >= 1),
    dispatch_generation INTEGER NOT NULL CHECK (dispatch_generation >= 0),
    phase TEXT NOT NULL CHECK (
        phase IN (
            'admission',
            'approval',
            'claim',
            'dispatch',
            'poll',
            'reconcile',
            'result_staging',
            'terminal'
        )
    ),
    previous_lifecycle_state TEXT CHECK (
        previous_lifecycle_state IS NULL OR previous_lifecycle_state IN (
            'awaiting_approval',
            'ready',
            'claimed',
            'dispatching',
            'waiting_external',
            'result_staging',
            'result_ready',
            'reconcile_required',
            'terminal'
        )
    ),
    lifecycle_state TEXT NOT NULL CHECK (
        lifecycle_state IN (
            'awaiting_approval',
            'ready',
            'claimed',
            'dispatching',
            'waiting_external',
            'result_staging',
            'result_ready',
            'reconcile_required',
            'terminal'
        )
    ),
    terminal_outcome TEXT CHECK (
        terminal_outcome IS NULL OR terminal_outcome IN (
            'succeeded', 'failed', 'cancelled', 'recovery_failed'
        )
    ),
    effect_certainty TEXT NOT NULL CHECK (
        effect_certainty IN (
            'no_effect', 'dispatch_in_doubt', 'effect_known', 'terminal_known'
        )
    ),
    retry_eligibility TEXT NOT NULL CHECK (
        retry_eligibility IN (
            'same_phase_safe',
            'verify_then_retry',
            'reconcile_required',
            'terminal'
        )
    ),
    fencing_token INTEGER NOT NULL CHECK (fencing_token >= 0),
    safe_receipt_digest TEXT,
    safe_summary TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(execution_id, state_version)
);

CREATE TABLE "controlled_operation_execution_records" ("execution_id" TEXT PRIMARY KEY, "operation_id" TEXT NOT NULL, "session_id" TEXT NOT NULL, "task_id" TEXT, "lane_id" TEXT, "approval_id" TEXT, "schema_version" TEXT NOT NULL DEFAULT 'controlled_operation_execution@1', "owner_mode" TEXT NOT NULL, "operation_digest" TEXT NOT NULL, "approval_digest" TEXT, "route_policy_id" TEXT NOT NULL, "selected_backend" TEXT NOT NULL, "adapter_policy_id" TEXT NOT NULL, "input_identity_digest" TEXT NOT NULL, "expected_output_contract_digest" TEXT NOT NULL, "runtime_identity_digest" TEXT NOT NULL, "lifecycle_state" TEXT NOT NULL, "terminal_outcome" TEXT, "effect_certainty" TEXT NOT NULL, "retry_eligibility" TEXT NOT NULL, "dispatch_generation" INTEGER NOT NULL DEFAULT 0, "state_version" INTEGER NOT NULL DEFAULT 1, "lease_owner" TEXT, "lease_token" TEXT, "lease_expires_at" TEXT, "fencing_token" INTEGER NOT NULL DEFAULT 0, "backend_handle_ref" TEXT, "result_handle_ref" TEXT, "result_digest" TEXT, "error_code" TEXT, "safe_error_summary" TEXT, "created_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "terminal_at" TEXT);

CREATE TABLE controlled_operation_provider_dispatch_receipts (
    receipt_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL UNIQUE
        REFERENCES controlled_operation_execution_records(execution_id) ON DELETE RESTRICT,
    operation_id TEXT NOT NULL
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    schema_version TEXT NOT NULL DEFAULT 'controlled_operation_provider_dispatch_receipt@1'
        CHECK (schema_version = 'controlled_operation_provider_dispatch_receipt@1'),
    dispatch_generation INTEGER NOT NULL CHECK (dispatch_generation > 0),
    provider_request_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    external_handle_ref TEXT NOT NULL,
    receipt_digest TEXT NOT NULL,
    receipt_envelope_json TEXT NOT NULL CHECK (json_valid(receipt_envelope_json)),
    receipt_size_bytes INTEGER NOT NULL
        CHECK (receipt_size_bytes > 0 AND receipt_size_bytes <= 4194304),
    created_at TEXT NOT NULL
);

CREATE TABLE controlled_operation_provider_observation_receipts (
    observation_id TEXT PRIMARY KEY,
    dispatch_receipt_id TEXT NOT NULL
        REFERENCES controlled_operation_provider_dispatch_receipts(receipt_id) ON DELETE RESTRICT,
    execution_id TEXT NOT NULL
        REFERENCES controlled_operation_execution_records(execution_id) ON DELETE RESTRICT,
    operation_id TEXT NOT NULL
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    schema_version TEXT NOT NULL DEFAULT 'controlled_operation_provider_observation_receipt@1'
        CHECK (schema_version = 'controlled_operation_provider_observation_receipt@1'),
    dispatch_generation INTEGER NOT NULL CHECK (dispatch_generation > 0),
    observation_index INTEGER NOT NULL CHECK (observation_index > 0),
    provider_request_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    external_handle_ref TEXT NOT NULL,
    observation_digest TEXT NOT NULL,
    observation_envelope_json TEXT NOT NULL CHECK (json_valid(observation_envelope_json)),
    observation_size_bytes INTEGER NOT NULL
        CHECK (observation_size_bytes > 0 AND observation_size_bytes <= 4194304),
    created_at TEXT NOT NULL,
    UNIQUE (execution_id, observation_index)
);

CREATE TABLE "controlled_operation_records" (
    "operation_id" TEXT PRIMARY KEY,
    "session_id" TEXT NOT NULL,
    "task_id" TEXT,
    "lane_id" TEXT,
    "approval_id" TEXT,
    "approval_state" TEXT,
    "logical_operation_key" TEXT,
    "operation_digest" TEXT,
    "params_digest" TEXT,
    "backend_category" TEXT,
    "route_reason" TEXT,
    "resource_estimate_json" TEXT NOT NULL DEFAULT '{}',
    "result_summary_json" TEXT NOT NULL DEFAULT '{}',
    "error_code" TEXT,
    "error_summary" TEXT,
    "idempotency_key" TEXT,
    "status" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "adapter_envelope_schema_version" TEXT,
    "sdk_module" TEXT,
    "function_name" TEXT,
    "route_policy_id" TEXT,
    "placement" TEXT,
    "selected_backend" TEXT,
    "resource_class" TEXT,
    "runtime_packaging_id" TEXT,
    "toolchain_id" TEXT,
    "provider_config_digest" TEXT,
    "approval_requirement_json" TEXT NOT NULL DEFAULT '{}',
    "adapter_approval_envelope_json" TEXT NOT NULL DEFAULT '{}',
    "adapter_result_envelope_json" TEXT NOT NULL DEFAULT '{}',
    "adapter_result_origin" TEXT,
    "owner_mode" TEXT NOT NULL DEFAULT 'durable_async_v1',
    "record_kind" TEXT NOT NULL DEFAULT 'legacy_controlled_operation'
        CHECK (
            record_kind IN (
                'legacy_controlled_operation',
                'kernel_controlled_operation'
            )
        ),
    "actor_id" TEXT,
    "owner_plugin_id" TEXT,
    "intent_digest" TEXT,
    "target_route_id" TEXT,
    "authority_lease_id" TEXT
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    "authority_generation" INTEGER,
    "authority_fence" INTEGER,
    "authority_operation" TEXT,
    "scope_id" TEXT,
    "dispatch_generation" INTEGER,
    "kernel_state" TEXT,
    "effect_certainty" TEXT,
    "mutation_applied" INTEGER CHECK (mutation_applied IN (0, 1)),
    "deadline" TEXT,
    "approval_required" INTEGER CHECK (approval_required IN (0, 1)),
    "cancel_intent_digest" TEXT,
    "result_handle" TEXT,
    "terminal_receipt_digest" TEXT,
    "last_observation_digest" TEXT,
    "safe_intent_json" TEXT CHECK (
        safe_intent_json IS NULL OR json_valid(safe_intent_json)
    ),
    "fallback_performed" INTEGER CHECK (fallback_performed IN (0, 1)),
    "diagnostic_id" TEXT,
    CHECK (
        (record_kind = 'legacy_controlled_operation'
         AND logical_operation_key IS NOT NULL
         AND operation_digest IS NOT NULL
         AND params_digest IS NOT NULL
         AND backend_category IS NOT NULL
         AND status IS NOT NULL)
        OR
        (record_kind = 'kernel_controlled_operation'
         AND actor_id IS NOT NULL
         AND owner_plugin_id IS NOT NULL
         AND intent_digest IS NOT NULL
         AND authority_lease_id IS NOT NULL
         AND authority_generation > 0
         AND authority_fence > 0
         AND authority_operation IS NOT NULL
         AND scope_id IS NOT NULL
         AND dispatch_generation > 0
         AND kernel_state IN (
             'admitted', 'active', 'reconcile_required', 'settled',
             'cancel_requested', 'cancelled'
         )
         AND effect_certainty IN (
             'no_effect', 'dispatch_in_doubt', 'effect_known', 'terminal_known'
         )
         AND approval_required IS NOT NULL
         AND safe_intent_json IS NOT NULL
         AND fallback_performed = 0)
    )
);

CREATE TABLE "controlled_operation_result_handles" ("result_handle_id" TEXT PRIMARY KEY, "execution_id" TEXT NOT NULL, "operation_id" TEXT NOT NULL, "session_id" TEXT NOT NULL, "schema_version" TEXT NOT NULL DEFAULT 'controlled_operation_result_handle@1', "dispatch_generation" INTEGER NOT NULL, "terminal_outcome" TEXT NOT NULL, "bounded_result_envelope_json" TEXT NOT NULL, "result_digest" TEXT NOT NULL, "origin" TEXT NOT NULL, "created_at" TEXT NOT NULL);

CREATE TABLE durable_event_records (
    cursor INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL UNIQUE,
    session_id TEXT NOT NULL REFERENCES sessions(session_id),
    event_type TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    visibility TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    command_id TEXT,
    correlation_id TEXT,
    causation_id TEXT,
    actor_ref TEXT,
    created_at TEXT NOT NULL,
    CHECK (cursor > 0),
    CHECK (visibility IN ('public', 'audit', 'internal'))
);

CREATE TABLE engine_documents (
    document_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    invocation_id TEXT REFERENCES engine_invocations(invocation_id) ON DELETE SET NULL,
    document_kind TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE engine_invocations (
    invocation_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    engine_name TEXT NOT NULL,
    status TEXT NOT NULL,
    input_ref TEXT,
    output_ref TEXT,
    approval_id TEXT REFERENCES approval_requests(approval_id) ON DELETE SET NULL,
    idempotency_key TEXT NOT NULL,
    started_at TEXT NOT NULL,
    finished_at TEXT
);

CREATE TABLE failure_hypothesis_records (
    hypothesis_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'failure_hypothesis@1'
        CHECK (schema_version = 'failure_hypothesis@1'),
    failure_id TEXT NOT NULL
        REFERENCES failure_observation_records(failure_id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL
        REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    hypothesis TEXT NOT NULL,
    confidence TEXT NOT NULL CHECK (
        confidence IN ('low', 'medium', 'high')
    ),
    evidence_refs_json TEXT NOT NULL,
    idempotency_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (session_id, agent_id, idempotency_digest)
);

CREATE TABLE failure_observation_records (
    failure_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'failure_observation@2'
        CHECK (schema_version = 'failure_observation@2'),
    session_id TEXT NOT NULL
        REFERENCES sessions(session_id) ON DELETE RESTRICT,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE RESTRICT,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE RESTRICT,
    agent_id TEXT,
    source_kind TEXT NOT NULL,
    source_ref TEXT NOT NULL,
    source_version TEXT NOT NULL,
    phase TEXT NOT NULL,
    failure_class TEXT NOT NULL CHECK (
        failure_class IN (
            'validation',
            'tool',
            'provider',
            'controlled_effect',
            'harness',
            'runtime',
            'system'
        )
    ),
    recoverability TEXT NOT NULL CHECK (
        recoverability IN (
            'agent_can_retry',
            'agent_can_replan',
            'reconciliation_required',
            'authorization_required',
            'runtime_retry',
            'terminal'
        )
    ),
    effect_certainty TEXT NOT NULL CHECK (
        effect_certainty IN (
            'no_effect',
            'dispatch_in_doubt',
            'effect_known',
            'terminal_known'
        )
    ),
    retry_eligibility TEXT NOT NULL CHECK (
        retry_eligibility IN (
            'same_phase_safe',
            'verify_then_retry',
            'reconcile_required',
            'terminal'
        )
    ),
    actor_kind TEXT NOT NULL CHECK (
        actor_kind IN ('harness', 'system', 'agent')
    ),
    error_code TEXT NOT NULL,
    safe_summary TEXT NOT NULL,
    safe_hint TEXT,
    facts_json TEXT NOT NULL,
    likely_causes_json TEXT NOT NULL,
    evidence_refs_json TEXT NOT NULL,
    agent_hypothesis TEXT,
    agent_hypothesis_confidence TEXT,
    agent_hypothesis_evidence_refs_json TEXT NOT NULL DEFAULT '[]',
    private_diagnostic_digest TEXT,
    component TEXT NOT NULL,
    operation TEXT NOT NULL,
    identities_json TEXT NOT NULL,
    mutation_applied INTEGER NOT NULL CHECK (mutation_applied IN (0, 1)),
    fallback_performed INTEGER NOT NULL CHECK (fallback_performed IN (0, 1)),
    cause_chain_json TEXT NOT NULL,
    diagnostic_id TEXT NOT NULL UNIQUE,
    next_action TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (
        session_id,
        source_kind,
        source_ref,
        source_version,
        phase,
        error_code
    )
);

CREATE TABLE private_diagnostic_records (
    diagnostic_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'private_diagnostic_record@1'
        CHECK (schema_version = 'private_diagnostic_record@1'),
    failure_id TEXT NOT NULL UNIQUE
        REFERENCES failure_observation_records(failure_id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL
        REFERENCES sessions(session_id) ON DELETE RESTRICT,
    component TEXT NOT NULL,
    operation TEXT NOT NULL,
    phase TEXT NOT NULL,
    exception_type TEXT NOT NULL,
    exception_message TEXT NOT NULL,
    traceback_text TEXT NOT NULL,
    cause_chain_json TEXT NOT NULL,
    errno INTEGER,
    return_code INTEGER,
    bounded_stdout TEXT,
    bounded_stderr TEXT,
    private_context_json TEXT NOT NULL,
    source_kind TEXT NOT NULL,
    source_ref TEXT NOT NULL,
    source_version TEXT NOT NULL,
    correlation_id TEXT,
    created_at TEXT NOT NULL,
    record_digest TEXT NOT NULL UNIQUE
);

CREATE TABLE failure_recovery_disposition_records (
    disposition_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'failure_recovery_disposition@1'
        CHECK (schema_version = 'failure_recovery_disposition@1'),
    failure_id TEXT NOT NULL
        REFERENCES failure_observation_records(failure_id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL
        REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    disposition TEXT NOT NULL CHECK (
        disposition = 'defer_until_task_dependencies_complete'
    ),
    condition_task_ids_json TEXT NOT NULL,
    rationale TEXT NOT NULL,
    idempotency_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (session_id, agent_id, idempotency_digest)
);

CREATE TABLE "file_workspace_contract_epoch_records" ("epoch" INTEGER PRIMARY KEY, "contract_id" TEXT NOT NULL, "state" TEXT NOT NULL, "candidate_tool_catalog_digest" TEXT NOT NULL, "pipeline_sdk_digest" TEXT NOT NULL, "gateway_schema_digest" TEXT NOT NULL, "revision_execution_schema_digest" TEXT NOT NULL, "surface_inventory_digest" TEXT NOT NULL, "prerequisite_gate_digest" TEXT NOT NULL, "freeze_receipt_digest" TEXT, "public_activation" INTEGER NOT NULL DEFAULT 0, "stage_writer_enabled" INTEGER NOT NULL DEFAULT 0, "prepared_at" TEXT NOT NULL, "activation_ready_at" TEXT, "epoch_digest" TEXT NOT NULL);

CREATE TABLE file_workspace_public_epoch_records (
    epoch INTEGER PRIMARY KEY CHECK (epoch > 0),
    contract_id TEXT NOT NULL CHECK (contract_id = 'file_workspace_public@1'),
    state TEXT NOT NULL CHECK (state IN ('prepared', 'active', 'retired')),
    tool_catalog_digest TEXT NOT NULL,
    executor_tool_catalog_digest TEXT NOT NULL,
    schema_bundle_digest TEXT NOT NULL,
    host_build_digest TEXT NOT NULL,
    cli_build_digest TEXT NOT NULL,
    sdk_build_digest TEXT NOT NULL,
    ui_build_digest TEXT NOT NULL,
    restore_schema_digest TEXT NOT NULL,
    event_schema_digest TEXT NOT NULL,
    predecessor_receipt_digest TEXT NOT NULL,
    activation_receipt_digest TEXT,
    prepared_at TEXT NOT NULL,
    activated_at TEXT,
    epoch_digest TEXT NOT NULL UNIQUE,
    CHECK (
        (state = 'prepared' AND activation_receipt_digest IS NULL
         AND activated_at IS NULL)
        OR
        (state IN ('active', 'retired') AND activation_receipt_digest IS NOT NULL
         AND activated_at IS NOT NULL)
    )
);

CREATE TABLE file_workspace_session_contract_records (
    session_id TEXT PRIMARY KEY REFERENCES sessions(session_id) ON DELETE RESTRICT,
    public_epoch INTEGER REFERENCES file_workspace_public_epoch_records(epoch)
        ON DELETE RESTRICT,
    contract_id TEXT NOT NULL,
    disposition TEXT NOT NULL CHECK (
        disposition IN ('current', 'closed_historical', 'unsupported_online')
    ),
    tool_catalog_digest TEXT NOT NULL,
    schema_bundle_digest TEXT NOT NULL,
    mutation_allowed INTEGER NOT NULL CHECK (mutation_allowed IN (0, 1)),
    disposition_receipt_digest TEXT NOT NULL,
    classified_at TEXT NOT NULL,
    CHECK (
        (disposition = 'current' AND contract_id = 'file_workspace_public@1'
         AND public_epoch IS NOT NULL AND mutation_allowed = 1)
        OR
        (disposition IN ('closed_historical', 'unsupported_online')
         AND public_epoch IS NULL AND mutation_allowed = 0)
    )
);

CREATE TABLE file_workspace_surface_freeze_records (
    freeze_id TEXT PRIMARY KEY,
    epoch INTEGER NOT NULL UNIQUE
        REFERENCES file_workspace_contract_epoch_records(epoch) ON DELETE RESTRICT,
    active_old_writers INTEGER NOT NULL CHECK (active_old_writers = 0),
    active_old_processes INTEGER NOT NULL CHECK (active_old_processes = 0),
    active_old_continuations INTEGER NOT NULL CHECK (active_old_continuations = 0),
    unsettled_old_external_effects INTEGER NOT NULL
        CHECK (unsettled_old_external_effects = 0),
    candidate_tool_catalog_digest TEXT NOT NULL,
    surface_inventory_digest TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    freeze_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'file_workspace_surface_freeze@1'
        CHECK (schema_version = 'file_workspace_surface_freeze@1')
);

CREATE TABLE inbox_messages (
    message_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    sender TEXT NOT NULL,
    sender_kind TEXT NOT NULL,
    recipient TEXT NOT NULL,
    recipient_kind TEXT NOT NULL,
    message_type TEXT NOT NULL,
    correlation_id TEXT,
    payload_ref TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE lane_lifecycle_events (
    event_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    lane_id TEXT NOT NULL REFERENCES lanes(lane_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE lanes (
    lane_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    cwd TEXT NOT NULL,
    branch_name TEXT,
    claimed_ref TEXT,
    workspace_binding_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE memory_entries (
    memory_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    scope_kind TEXT NOT NULL,
    scope_ref TEXT NOT NULL,
    kind TEXT NOT NULL,
    summary TEXT NOT NULL,
    source_range TEXT,
    author_actor_id TEXT,
    importance INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE mutation_scope_records (
    scope_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'mutation_scope@1'
        CHECK (schema_version = 'mutation_scope@1'),
    scope_kind TEXT NOT NULL CHECK (scope_kind IN ('session', 'attempt')),
    scope_ref TEXT NOT NULL,
    parent_scope_id TEXT REFERENCES mutation_scope_records(scope_id) ON DELETE RESTRICT,
    state TEXT NOT NULL CHECK (
        state IN ('open', 'freezing', 'quiescent', 'sealed', 'failed')
    ),
    generation INTEGER NOT NULL CHECK (generation >= 1),
    mutation_fencing_token INTEGER NOT NULL CHECK (mutation_fencing_token >= 1),
    state_version INTEGER NOT NULL DEFAULT 1 CHECK (state_version >= 1),
    policy_id TEXT NOT NULL,
    writer_coverage_manifest_digest TEXT NOT NULL,
    opened_at TEXT NOT NULL,
    freeze_requested_at TEXT,
    quiescent_at TEXT,
    sealed_at TEXT,
    failed_at TEXT,
    safe_error_summary TEXT, session_id TEXT REFERENCES sessions(session_id) ON DELETE RESTRICT, sealed_receipt_digest TEXT,
    UNIQUE(scope_kind, scope_ref, generation)
);

CREATE TABLE "mutation_writer_records" ("writer_id" TEXT PRIMARY KEY, "schema_version" TEXT NOT NULL DEFAULT 'mutation_writer@1', "scope_id" TEXT NOT NULL, "scope_generation" INTEGER NOT NULL, "owner_kind" TEXT NOT NULL, "owner_ref" TEXT NOT NULL, "process_epoch" INTEGER, "state" TEXT NOT NULL, "parent_writer_id" TEXT, "fencing_token" INTEGER NOT NULL, "state_version" INTEGER NOT NULL DEFAULT 1, "registered_at" TEXT NOT NULL, "retired_at" TEXT, "terminal_proof_digest" TEXT, "safe_error_summary" TEXT);

CREATE TABLE project_repository_active_bindings (
    project_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    activation_generation INTEGER NOT NULL CHECK (activation_generation > 0),
    activated_at TEXT NOT NULL,
    activated_by TEXT NOT NULL,
    FOREIGN KEY (project_id, binding_id, binding_version)
        REFERENCES project_repository_binding_versions(
            project_id,
            binding_id,
            binding_version
        ) ON DELETE RESTRICT
);

CREATE TABLE project_repository_binding_lifecycle_events (
    event_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    status TEXT NOT NULL CHECK (status IN ('registered', 'active', 'retired')),
    actor_ref TEXT NOT NULL,
    reason TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (project_id, binding_id, binding_version)
        REFERENCES project_repository_binding_versions(
            project_id,
            binding_id,
            binding_version
        ) ON DELETE RESTRICT
);

CREATE TABLE project_repository_binding_retirement_receipts (
    receipt_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    project_id TEXT NOT NULL,
    reference_audit_digest TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    FOREIGN KEY (project_id, binding_id, binding_version)
        REFERENCES project_repository_binding_versions(
            project_id,
            binding_id,
            binding_version
        ) ON DELETE RESTRICT
);

CREATE TABLE project_repository_binding_versions (
    binding_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    internal_git_service_id TEXT NOT NULL,
    internal_git_endpoint TEXT NOT NULL,
    lfs_service_id TEXT NOT NULL,
    lfs_endpoint TEXT NOT NULL,
    upstream_identity TEXT NOT NULL,
    upstream_url TEXT NOT NULL,
    object_format TEXT NOT NULL CHECK (object_format IN ('sha1', 'sha256')),
    default_base_ref TEXT NOT NULL,
    default_base_commit TEXT NOT NULL,
    private_ref_prefix TEXT NOT NULL,
    publication_ref_prefix TEXT NOT NULL,
    historical_ref_prefix TEXT NOT NULL,
    repository_policy_version TEXT NOT NULL,
    repository_policy_digest TEXT NOT NULL,
    canonical_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'project_repository_binding@1'
        CHECK (schema_version = 'project_repository_binding@1'),
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    UNIQUE (project_id, binding_version),
    UNIQUE (binding_id, binding_version),
    UNIQUE (project_id, binding_id, binding_version)
);

CREATE TABLE project_repository_binding_heads (
    project_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    binding_canonical_digest TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (project_id, binding_id, binding_version)
        REFERENCES project_repository_binding_versions(
            project_id,
            binding_id,
            binding_version
        ) ON DELETE RESTRICT
);

CREATE TABLE protocol_file_handoff_entries (
    handoff_id TEXT NOT NULL
        REFERENCES protocol_file_handoff_records(handoff_id) ON DELETE RESTRICT,
    ordinal INTEGER NOT NULL CHECK (ordinal BETWEEN 0 AND 31),
    ref_id TEXT NOT NULL REFERENCES revision_path_refs(ref_id) ON DELETE RESTRICT,
    PRIMARY KEY (handoff_id, ordinal),
    UNIQUE (handoff_id, ref_id)
);

CREATE TABLE protocol_file_handoff_records (
    handoff_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    producer_agent_id TEXT NOT NULL,
    recipient_agent_id TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK (length(CAST(purpose AS BLOB)) BETWEEN 1 AND 512),
    created_at TEXT NOT NULL,
    handoff_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'protocol_file_handoff@1'
        CHECK (schema_version = 'protocol_file_handoff@1')
);

CREATE TABLE published_revisions (
    publication_id TEXT PRIMARY KEY,
    intent_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_publication_intents(intent_id) ON DELETE RESTRICT,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version > 0),
    repository_id TEXT NOT NULL,
    commit_id TEXT NOT NULL,
    tree_id TEXT NOT NULL,
    git_parent_commits_json TEXT NOT NULL CHECK (json_valid(git_parent_commits_json)),
    declared_base_commit TEXT NOT NULL,
    parent_publication_id TEXT REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    publisher_agent_member_id TEXT NOT NULL,
    publisher_agent_id TEXT NOT NULL,
    publisher_workspace_id TEXT NOT NULL,
    publisher_workspace_generation INTEGER NOT NULL CHECK (publisher_workspace_generation > 0),
    publication_ref TEXT NOT NULL UNIQUE,
    manifest_json TEXT NOT NULL CHECK (json_valid(manifest_json)),
    manifest_digest TEXT NOT NULL,
    repository_policy_version TEXT NOT NULL,
    repository_policy_digest TEXT NOT NULL,
    controlled_execution_id TEXT NOT NULL UNIQUE
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    remote_receipt_id TEXT NOT NULL UNIQUE,
    supersedes_publication_id TEXT REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    created_at TEXT NOT NULL,
    revision_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'published_revision@1'
        CHECK (schema_version = 'published_revision@1'),
    FOREIGN KEY (session_id, publisher_agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    CHECK (publication_ref LIKE 'refs/%/' || publication_id)
);

CREATE TABLE "quiescence_receipt_records" ("receipt_id" TEXT PRIMARY KEY, "schema_version" TEXT NOT NULL DEFAULT 'quiescence_receipt@1', "scope_id" TEXT NOT NULL REFERENCES mutation_scope_records(scope_id) ON DELETE RESTRICT, "seal_generation" INTEGER NOT NULL CHECK (seal_generation >= 1), "policy_digest" TEXT NOT NULL, "coverage_digest" TEXT NOT NULL, "writer_set_digest" TEXT NOT NULL, "terminal_proof_digest" TEXT NOT NULL, "sqlite_high_watermark" TEXT NOT NULL, "event_high_watermark" TEXT NOT NULL, "file_high_watermark" TEXT NOT NULL, "snapshot_digest" TEXT NOT NULL, "receipt_digest" TEXT NOT NULL UNIQUE, "issued_at" TEXT NOT NULL, UNIQUE(scope_id, seal_generation));

CREATE TABLE quiescence_snapshot_records (
    snapshot_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'quiescence_snapshot@1'
        CHECK (schema_version = 'quiescence_snapshot@1'),
    receipt_id TEXT NOT NULL UNIQUE
        REFERENCES quiescence_receipt_records(receipt_id) ON DELETE RESTRICT,
    scope_id TEXT NOT NULL REFERENCES mutation_scope_records(scope_id) ON DELETE RESTRICT,
    seal_generation INTEGER NOT NULL CHECK (seal_generation >= 1),
    evidence_json TEXT NOT NULL,
    evidence_digest TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    UNIQUE(scope_id, seal_generation),
    FOREIGN KEY (scope_id, seal_generation)
        REFERENCES quiescence_receipt_records(scope_id, seal_generation)
        ON DELETE RESTRICT
);

CREATE TABLE repository_binding_mapping_receipts (
    receipt_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    project_id TEXT NOT NULL,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    resolved_base_commit TEXT NOT NULL,
    binding_canonical_digest TEXT NOT NULL,
    operator_ref TEXT NOT NULL,
    mapping_reason TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),
    created_at TEXT NOT NULL,
    FOREIGN KEY (project_id, binding_id, binding_version)
        REFERENCES project_repository_binding_versions(
            project_id,
            binding_id,
            binding_version
        ) ON DELETE RESTRICT
);

CREATE TABLE revision_path_refs (
    ref_id TEXT PRIMARY KEY,
    publication_id TEXT NOT NULL
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version >= 1),
    repository_id TEXT NOT NULL,
    commit_oid TEXT NOT NULL,
    tree_oid TEXT NOT NULL,
    repository_path TEXT NOT NULL,
    entry_kind TEXT NOT NULL CHECK (
        entry_kind IN ('file', 'lfs_file', 'directory', 'symlink', 'gitlink')
    ),
    object_id TEXT NOT NULL,
    size_bytes INTEGER CHECK (size_bytes IS NULL OR size_bytes >= 0),
    lfs_oid TEXT,
    lfs_size_bytes INTEGER CHECK (lfs_size_bytes IS NULL OR lfs_size_bytes >= 0),
    path_manifest_digest TEXT,
    created_at TEXT NOT NULL,
    ref_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'revision_path_ref@1'
        CHECK (schema_version = 'revision_path_ref@1'),
    CHECK (repository_path <> ''),
    CHECK (length(CAST(repository_path AS BLOB)) <= 1024),
    CHECK (substr(repository_path, 1, 1) <> '/'),
    CHECK (instr(repository_path, '\\') = 0),
    CHECK (instr('/' || repository_path || '/', '/../') = 0),
    CHECK (instr('/' || repository_path || '/', '/./') = 0),
    CHECK (
        (entry_kind = 'lfs_file' AND size_bytes IS NOT NULL
            AND lfs_oid IS NOT NULL AND lfs_size_bytes IS NOT NULL
            AND path_manifest_digest IS NULL)
        OR (entry_kind = 'directory' AND lfs_oid IS NULL AND lfs_size_bytes IS NULL
            AND size_bytes IS NULL AND path_manifest_digest IS NOT NULL)
        OR (entry_kind IN ('file', 'symlink', 'gitlink') AND lfs_oid IS NULL
            AND lfs_size_bytes IS NULL AND path_manifest_digest IS NULL)
    )
);

CREATE TABLE runtime_command_records (
    command_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    schema_version TEXT NOT NULL DEFAULT 'runtime_command@1'
        CHECK (schema_version = 'runtime_command@1'),
    command_type TEXT NOT NULL CHECK (command_type = 'runtime.drain'),
    request_digest TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('accepted', 'claimed', 'completed', 'failed', 'locked', 'cancelled')
    ),
    max_signals INTEGER NOT NULL CHECK (max_signals >= 1),
    max_steps_per_agent INTEGER NOT NULL CHECK (max_steps_per_agent >= 1),
    auto_enqueue_ready_tasks INTEGER NOT NULL DEFAULT 0
        CHECK (auto_enqueue_ready_tasks IN (0, 1)),
    claim_owner TEXT,
    lease_token TEXT,
    lease_expires_at TEXT,
    fencing_token INTEGER NOT NULL DEFAULT 0 CHECK (fencing_token >= 0),
    state_version INTEGER NOT NULL DEFAULT 1 CHECK (state_version >= 1),
    bounded_outcome_summary_json TEXT CHECK (
        bounded_outcome_summary_json IS NULL OR json_valid(bounded_outcome_summary_json)
    ),
    error_code TEXT,
    safe_error_summary TEXT,
    safe_retry_hint TEXT,
    accepted_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    UNIQUE(session_id, command_type, idempotency_key),
    CHECK (
        status <> 'claimed'
        OR (
            claim_owner IS NOT NULL
            AND lease_token IS NOT NULL
            AND lease_expires_at IS NOT NULL
        )
    )
);

-- Target bounded-turn coordination records.  These are deliberately separate
-- from runtime_command_records, whose retained contract is runtime.drain@1.
CREATE TABLE runtime_turn_command_records (
    command_id TEXT PRIMARY KEY,
    turn_id TEXT NOT NULL UNIQUE,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    signal_id TEXT NOT NULL
        REFERENCES agent_runtime_signals(signal_id) ON DELETE RESTRICT,
    signal_attempt INTEGER NOT NULL CHECK (signal_attempt >= 1),
    signal_claim_token TEXT NOT NULL,
    runtime_lease_token TEXT NOT NULL,
    runtime_lease_generation INTEGER NOT NULL CHECK (runtime_lease_generation >= 1),
    runtime_fence INTEGER NOT NULL CHECK (runtime_fence >= 1),
    process_epoch INTEGER NOT NULL CHECK (process_epoch >= 1),
    distribution_id TEXT NOT NULL,
    distribution_manifest_digest TEXT NOT NULL,
    release_digest TEXT NOT NULL,
    adapter_bundle_digest TEXT NOT NULL,
    extension_bundle_digest TEXT NOT NULL,
    declared_tool_catalog_digest TEXT NOT NULL,
    capability_binding_id TEXT NOT NULL,
    capability_binding_revision INTEGER NOT NULL
        CHECK (capability_binding_revision >= 1),
    capability_binding_digest TEXT NOT NULL,
    affordance_snapshot_id TEXT NOT NULL,
    affordance_snapshot_digest TEXT NOT NULL,
    runtime_adapter_id TEXT NOT NULL,
    runtime_adapter_contract_digest TEXT NOT NULL,
    max_steps INTEGER NOT NULL CHECK (max_steps >= 1),
    max_duration_seconds INTEGER NOT NULL CHECK (max_duration_seconds >= 1),
    max_input_units INTEGER NOT NULL CHECK (max_input_units >= 1),
    max_output_units INTEGER NOT NULL CHECK (max_output_units >= 1),
    messages_json TEXT NOT NULL CHECK (json_valid(messages_json)),
    task_id TEXT REFERENCES tasks(task_id) ON DELETE RESTRICT,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE RESTRICT,
    continuation_id TEXT,
    command_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'runtime_turn_command@1'
        CHECK (schema_version = 'runtime_turn_command@1'),
    UNIQUE (signal_id, signal_attempt)
);

CREATE TABLE runtime_continuation_intent_records (
    continuation_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    source_command_id TEXT NOT NULL UNIQUE
        REFERENCES runtime_turn_command_records(command_id) ON DELETE RESTRICT,
    source_command_digest TEXT NOT NULL,
    source_outcome_id TEXT NOT NULL UNIQUE,
    source_outcome_digest TEXT NOT NULL,
    process_epoch INTEGER NOT NULL CHECK (process_epoch >= 1),
    release_digest TEXT NOT NULL,
    extension_bundle_digest TEXT NOT NULL,
    declared_tool_catalog_digest TEXT NOT NULL,
    capability_binding_id TEXT NOT NULL,
    capability_binding_revision INTEGER NOT NULL
        CHECK (capability_binding_revision >= 1),
    capability_binding_digest TEXT NOT NULL,
    affordance_snapshot_id TEXT NOT NULL,
    affordance_snapshot_digest TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'runtime_continuation_intent@1'
        CHECK (schema_version = 'runtime_continuation_intent@1')
);

CREATE TABLE runtime_settlement_intent_records (
    settlement_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    signal_id TEXT NOT NULL
        REFERENCES agent_runtime_signals(signal_id) ON DELETE RESTRICT,
    signal_attempt INTEGER NOT NULL CHECK (signal_attempt >= 1),
    source_command_id TEXT NOT NULL UNIQUE
        REFERENCES runtime_turn_command_records(command_id) ON DELETE RESTRICT,
    source_command_digest TEXT NOT NULL,
    source_outcome_id TEXT NOT NULL UNIQUE,
    source_outcome_digest TEXT NOT NULL,
    disposition TEXT NOT NULL CHECK (disposition IN (
        'ready_for_next_step', 'waiting_approval', 'waiting_continuation',
        'idle', 'step_limit_reached', 'failed'
    )),
    waiting_approval_id TEXT
        REFERENCES approval_requests(approval_id) ON DELETE RESTRICT,
    failure_id TEXT
        REFERENCES failure_observation_records(failure_id) ON DELETE RESTRICT,
    task_transition_performed INTEGER NOT NULL DEFAULT 0
        CHECK (task_transition_performed = 0),
    schema_version TEXT NOT NULL DEFAULT 'runtime_settlement_intent@1'
        CHECK (schema_version = 'runtime_settlement_intent@1')
);

CREATE TABLE runtime_outcome_consumption_records (
    command_id TEXT PRIMARY KEY
        REFERENCES runtime_turn_command_records(command_id) ON DELETE RESTRICT,
    consumption_id TEXT NOT NULL UNIQUE,
    command_digest TEXT NOT NULL,
    outcome_id TEXT NOT NULL UNIQUE,
    outcome_digest TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    signal_id TEXT NOT NULL
        REFERENCES agent_runtime_signals(signal_id) ON DELETE RESTRICT,
    signal_attempt INTEGER NOT NULL CHECK (signal_attempt >= 1),
    continuation_intent_id TEXT UNIQUE
        REFERENCES runtime_continuation_intent_records(continuation_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    continuation_intent_json TEXT CHECK (
        continuation_intent_json IS NULL OR json_valid(continuation_intent_json)
    ),
    settlement_intent_id TEXT NOT NULL UNIQUE
        REFERENCES runtime_settlement_intent_records(settlement_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    settlement_intent_json TEXT NOT NULL CHECK (json_valid(settlement_intent_json)),
    consumed_at TEXT NOT NULL,
    consumption_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'runtime_outcome_consumption@1'
        CHECK (schema_version = 'runtime_outcome_consumption@1'),
    CHECK (
        (continuation_intent_id IS NULL AND continuation_intent_json IS NULL)
        OR (continuation_intent_id IS NOT NULL AND continuation_intent_json IS NOT NULL)
    )
);

CREATE TABLE workspace_generation_records (
    workspace_id TEXT PRIMARY KEY,
    workspace_kind TEXT NOT NULL CHECK (
        workspace_kind IN ('agent_local', 'executor_remote')
    ),
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    owner_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    generation INTEGER NOT NULL CHECK (generation >= 1),
    workspace_state_version INTEGER NOT NULL CHECK (workspace_state_version >= 1),
    status TEXT NOT NULL CHECK (status IN (
        'reserved', 'provisioning', 'ready', 'retiring', 'retired', 'failed'
    )),
    provider_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    root_identity_digest TEXT,
    target_qualification_digest TEXT,
    transition_receipt_digest TEXT,
    controlled_operation_id TEXT,
    retired_at TEXT,
    schema_version TEXT NOT NULL DEFAULT 'workspace_generation@1'
        CHECK (schema_version = 'workspace_generation@1'),
    UNIQUE (workspace_id, generation),
    UNIQUE (session_id, owner_member_id, generation)
);

CREATE TABLE workspace_runtime_binding_records (
    workspace_id TEXT PRIMARY KEY,
    workspace_kind TEXT NOT NULL CHECK (
        workspace_kind IN ('agent_local', 'executor_remote')
    ),
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    owner_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    generation INTEGER NOT NULL CHECK (generation >= 1),
    workspace_state_version INTEGER NOT NULL CHECK (workspace_state_version >= 1),
    root_identity_digest TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    target_qualification_digest TEXT,
    schema_version TEXT NOT NULL DEFAULT 'workspace_runtime_binding@1'
        CHECK (schema_version = 'workspace_runtime_binding@1'),
    FOREIGN KEY (workspace_id, generation)
        REFERENCES workspace_generation_records(workspace_id, generation)
        ON DELETE RESTRICT
);

CREATE TABLE task_evidence_records (
    evidence_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT,
    registered_by_actor_id TEXT NOT NULL,
    evidence_digest TEXT NOT NULL UNIQUE,
    evidence_ref_json TEXT NOT NULL CHECK (json_valid(evidence_ref_json)),
    created_at TEXT NOT NULL,
    task_transition_performed INTEGER NOT NULL DEFAULT 0
        CHECK (task_transition_performed = 0),
    schema_version TEXT NOT NULL DEFAULT 'task_evidence_registration@1'
        CHECK (schema_version = 'task_evidence_registration@1')
);

CREATE TABLE revision_path_verification_records (
    ref_id TEXT PRIMARY KEY,
    publication_id TEXT NOT NULL
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version >= 1),
    commit_oid TEXT NOT NULL,
    tree_oid TEXT NOT NULL,
    repository_path TEXT NOT NULL,
    object_id TEXT NOT NULL,
    actual_size_bytes INTEGER CHECK (actual_size_bytes IS NULL OR actual_size_bytes >= 0),
    actual_content_digest TEXT,
    lfs_oid TEXT,
    lfs_size_bytes INTEGER CHECK (lfs_size_bytes IS NULL OR lfs_size_bytes >= 0),
    verified_at TEXT NOT NULL,
    verification_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'revision_path_verification_receipt@1'
        CHECK (schema_version = 'revision_path_verification_receipt@1'),
    FOREIGN KEY (repository_binding_id, repository_binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
        ON DELETE RESTRICT,
    CHECK ((lfs_oid IS NULL) = (lfs_size_bytes IS NULL))
);

CREATE TABLE session_access_records (
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    principal_id TEXT NOT NULL,
    access_role TEXT NOT NULL CHECK (access_role IN ('owner', 'collaborator', 'viewer')),
    created_at TEXT NOT NULL,
    PRIMARY KEY (session_id, principal_id)
);

CREATE TABLE session_repository_binding_pins (
    session_id TEXT PRIMARY KEY REFERENCES sessions(session_id) ON DELETE RESTRICT,
    project_id TEXT NOT NULL,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    resolved_base_commit TEXT NOT NULL,
    binding_canonical_digest TEXT NOT NULL,
    mapping_receipt_id TEXT REFERENCES repository_binding_mapping_receipts(receipt_id)
        ON DELETE RESTRICT,
    schema_version TEXT NOT NULL DEFAULT 'session_repository_binding_pin@1'
        CHECK (schema_version = 'session_repository_binding_pin@1'),
    pinned_at TEXT NOT NULL,
    FOREIGN KEY (project_id, binding_id, binding_version)
        REFERENCES project_repository_binding_versions(
            project_id,
            binding_id,
            binding_version
        ) ON DELETE RESTRICT
);

CREATE TABLE session_runtime_leases (
    lease_token TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    owner_id TEXT NOT NULL,
    mode TEXT NOT NULL,
    acquired_at TEXT NOT NULL,
    heartbeat_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    released_at TEXT,
    last_error TEXT,
    fencing_token INTEGER NOT NULL,
    record_kind TEXT NOT NULL DEFAULT 'legacy_session_runtime_lease'
        CHECK (
            record_kind IN (
                'legacy_session_runtime_lease',
                'kernel_session_runtime_lease'
            )
        ),
    kernel_entity_id TEXT UNIQUE,
    generation INTEGER,
    acquire_command_digest TEXT,
    CHECK (
        record_kind = 'legacy_session_runtime_lease'
        OR (
            kernel_entity_id = session_id
            AND generation > 0
            AND acquire_command_digest IS NOT NULL
        )
    )
);

CREATE TABLE sessions (
    session_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    title TEXT NOT NULL,
    objective TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
, repository_binding_status TEXT NOT NULL
    DEFAULT 'repository_binding_required'
    CHECK (repository_binding_status IN ('repository_binding_required', 'pinned')));

CREATE TABLE task_dependencies (
    task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
    blocked_by_task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, blocked_by_task_id),
    CHECK (task_id <> blocked_by_task_id)
);

CREATE TABLE task_finish_evidence_records (
    finish_ref TEXT NOT NULL REFERENCES task_finish_records(finish_ref) ON DELETE RESTRICT,
    ordinal INTEGER NOT NULL CHECK (ordinal BETWEEN 0 AND 63),
    kind TEXT NOT NULL CHECK (
        kind IN ('revision_path', 'report', 'controlled_operation_result', 'scientific_deliverable')
    ),
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    owner_digest TEXT NOT NULL,
    revision_path_ref_id TEXT REFERENCES revision_path_refs(ref_id) ON DELETE RESTRICT,
    evidence_json TEXT NOT NULL CHECK (json_valid(evidence_json)),
    schema_version TEXT NOT NULL DEFAULT 'task_evidence_ref@1'
        CHECK (schema_version = 'task_evidence_ref@1'),
    PRIMARY KEY (finish_ref, ordinal),
    UNIQUE (finish_ref, kind, owner_id),
    CHECK (
        (kind = 'revision_path' AND revision_path_ref_id IS NOT NULL)
        OR (kind <> 'revision_path' AND revision_path_ref_id IS NULL)
    )
);

CREATE TABLE task_finish_records (
    finish_ref TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT,
    terminal_status TEXT NOT NULL CHECK (
        terminal_status IN ('completed', 'failed', 'blocked', 'cancelled')
    ),
    summary TEXT NOT NULL,
    failure_summary TEXT,
    failure_ref TEXT,
    blocked_reason TEXT,
    recovery_hint TEXT,
    next_owner TEXT,
    finished_by TEXT NOT NULL,
    correlation_id TEXT,
    signal_id TEXT,
    created_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'task_finish_record@1'
        CHECK (schema_version = 'task_finish_record@1')
);

CREATE TABLE tasks (
    task_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL,
    priority TEXT NOT NULL,
    kind TEXT NOT NULL,
    assigned_ref TEXT,
    owner_actor_id TEXT,
    finish_validator_ids_json TEXT NOT NULL DEFAULT '[]'
        CHECK (json_valid(finish_validator_ids_json)),
    evidence_refs_json TEXT NOT NULL DEFAULT '[]'
        CHECK (json_valid(evidence_refs_json)),
    finish_evidence_refs_json TEXT NOT NULL DEFAULT '[]'
        CHECK (json_valid(finish_evidence_refs_json)),
    finish_validation_digest TEXT,
    finished_by_actor_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
, lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL, failure_summary TEXT, failure_ref TEXT);

CREATE TABLE verified_workspace_checkpoint_records (
    checkpoint_id TEXT PRIMARY KEY,
    boundary TEXT NOT NULL CHECK (
        boundary IN (
            'durable_checkpoint', 'publication', 'handoff',
            'external_job', 'task_terminal'
        )
    ),
    workspace_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    agent_member_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version > 0),
    repository_id TEXT NOT NULL,
    commit_oid TEXT NOT NULL,
    tree_oid TEXT NOT NULL,
    private_ref TEXT NOT NULL,
    prior_commit_oid TEXT,
    advance_kind TEXT NOT NULL CHECK (advance_kind IN ('create', 'fast_forward')),
    remote_observed_at TEXT NOT NULL,
    verified_at TEXT NOT NULL,
    checkpoint_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL CHECK (
        schema_version = 'verified_workspace_checkpoint@1'
    ),
    UNIQUE (workspace_id, boundary, private_ref, commit_oid),
    FOREIGN KEY (workspace_id, workspace_generation)
        REFERENCES workspace_generation_records(workspace_id, generation)
        ON DELETE RESTRICT,
    FOREIGN KEY (repository_binding_id, repository_binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
);

CREATE TABLE workspace_publication_execution_events (
    event_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL
        REFERENCES workspace_publication_execution_records(execution_id) ON DELETE RESTRICT,
    operation_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    state_version INTEGER NOT NULL CHECK (state_version >= 1),
    dispatch_generation INTEGER NOT NULL CHECK (dispatch_generation >= 0),
    phase TEXT NOT NULL CHECK (
        phase IN ('admission', 'claim', 'dispatch', 'reconcile', 'result_staging', 'terminal')
    ),
    previous_lifecycle_state TEXT,
    lifecycle_state TEXT NOT NULL,
    terminal_outcome TEXT,
    effect_certainty TEXT NOT NULL,
    retry_eligibility TEXT NOT NULL,
    fencing_token INTEGER NOT NULL CHECK (fencing_token >= 0),
    safe_receipt_digest TEXT,
    safe_summary TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(execution_id, state_version)
);

CREATE TABLE "workspace_publication_execution_records" ("execution_id" TEXT PRIMARY KEY, "operation_id" TEXT NOT NULL, "intent_id" TEXT NOT NULL, "publication_id" TEXT NOT NULL, "session_id" TEXT NOT NULL, "task_id" TEXT, "lane_id" TEXT, "schema_version" TEXT NOT NULL DEFAULT 'controlled_operation_execution@1', "owner_mode" TEXT NOT NULL, "operation_digest" TEXT NOT NULL, "approval_digest" TEXT, "route_policy_id" TEXT NOT NULL, "selected_backend" TEXT NOT NULL, "adapter_policy_id" TEXT NOT NULL, "input_identity_digest" TEXT NOT NULL, "expected_output_contract_digest" TEXT NOT NULL, "runtime_identity_digest" TEXT NOT NULL, "lifecycle_state" TEXT NOT NULL, "terminal_outcome" TEXT, "effect_certainty" TEXT NOT NULL, "retry_eligibility" TEXT NOT NULL, "dispatch_generation" INTEGER NOT NULL, "state_version" INTEGER NOT NULL, "lease_owner" TEXT, "lease_token" TEXT, "lease_expires_at" TEXT, "fencing_token" INTEGER NOT NULL, "backend_handle_ref" TEXT, "result_handle_ref" TEXT, "result_digest" TEXT, "error_code" TEXT, "safe_error_summary" TEXT, "created_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "terminal_at" TEXT);

CREATE TABLE workspace_publication_intents (
    intent_id TEXT PRIMARY KEY,
    publication_id TEXT NOT NULL UNIQUE,
    idempotency_key TEXT NOT NULL,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version > 0),
    repository_id TEXT NOT NULL,
    expected_head_commit TEXT NOT NULL,
    expected_tree TEXT NOT NULL,
    git_parent_commits_json TEXT NOT NULL CHECK (json_valid(git_parent_commits_json)),
    declared_base_commit TEXT NOT NULL,
    parent_publication_id TEXT REFERENCES published_revisions(publication_id) DEFERRABLE INITIALLY DEFERRED,
    supersedes_publication_id TEXT REFERENCES published_revisions(publication_id) DEFERRABLE INITIALLY DEFERRED,
    publication_ref TEXT NOT NULL UNIQUE,
    manifest_json TEXT NOT NULL CHECK (json_valid(manifest_json)),
    manifest_digest TEXT NOT NULL,
    repository_policy_version TEXT NOT NULL,
    repository_policy_digest TEXT NOT NULL,
    checkpoint_id TEXT NOT NULL REFERENCES verified_workspace_checkpoint_records(checkpoint_id) ON DELETE RESTRICT,
    state TEXT NOT NULL CHECK (state = 'frozen'),
    created_at TEXT NOT NULL,
    canonical_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_publication_intent@1'
        CHECK (schema_version = 'workspace_publication_intent@1'),
    UNIQUE(session_id, idempotency_key),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    FOREIGN KEY (workspace_id, workspace_generation)
        REFERENCES workspace_generation_records(workspace_id, generation)
        ON DELETE RESTRICT,
    FOREIGN KEY (repository_binding_id, repository_binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
        ON DELETE RESTRICT,
    CHECK (publication_ref LIKE 'refs/%/' || publication_id)
);

CREATE TABLE workspace_publication_outbox_records (
    outbox_id TEXT PRIMARY KEY,
    publication_id TEXT NOT NULL UNIQUE
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    event_type TEXT NOT NULL CHECK (event_type = 'workspace.publication.materialized'),
    event_digest TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'delivered')),
    created_at TEXT NOT NULL,
    delivered_at TEXT
    ,CHECK (
        (status = 'pending' AND delivered_at IS NULL)
        OR (status = 'delivered' AND delivered_at IS NOT NULL)
    )
);

CREATE TABLE workspace_publication_remote_receipts (
    receipt_id TEXT PRIMARY KEY,
    intent_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_publication_intents(intent_id) ON DELETE RESTRICT,
    publication_id TEXT NOT NULL UNIQUE,
    execution_id TEXT NOT NULL UNIQUE
        REFERENCES workspace_publication_execution_records(execution_id) ON DELETE RESTRICT,
    execution_dispatch_generation INTEGER NOT NULL CHECK (execution_dispatch_generation > 0),
    execution_fencing_token INTEGER NOT NULL CHECK (execution_fencing_token > 0),
    internal_git_service_id TEXT NOT NULL,
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version > 0),
    repository_id TEXT NOT NULL,
    publication_ref TEXT NOT NULL UNIQUE,
    expected_previous_commit TEXT CHECK (expected_previous_commit IS NULL),
    new_commit TEXT NOT NULL,
    new_tree TEXT NOT NULL,
    server_observed_commit TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'workspace_publication_remote_receipt@1'
        CHECK (schema_version = 'workspace_publication_remote_receipt@1'),
    CHECK (server_observed_commit = new_commit),
    CHECK (publication_ref LIKE 'refs/%/' || publication_id)
);

CREATE TABLE workspace_publication_supersedes_links (
    successor_publication_id TEXT PRIMARY KEY
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    predecessor_publication_id TEXT NOT NULL
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    created_at TEXT NOT NULL,
    CHECK (successor_publication_id <> predecessor_publication_id)
);
