-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.process.podman
-- phase: tables

CREATE TABLE sandbox_image_records (
    image_ref TEXT PRIMARY KEY,
    image_digest TEXT,
    image_family TEXT NOT NULL,
    image_version TEXT NOT NULL,
    sandbox_protocol_version TEXT NOT NULL,
    manifest_schema_version TEXT NOT NULL,
    capabilities_declared_json TEXT NOT NULL CHECK (json_valid(capabilities_declared_json)),
    compatibility TEXT NOT NULL,
    compatibility_error TEXT,
    is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE sandbox_workspace_records (
    sandbox_workspace_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    focus_task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    focus_lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    status TEXT NOT NULL,
    image_ref TEXT NOT NULL REFERENCES sandbox_image_records(image_ref) ON DELETE RESTRICT,
    image_digest TEXT,
    image_version TEXT,
    sandbox_protocol_version TEXT,
    image_compatibility TEXT NOT NULL,
    manifest_version TEXT NOT NULL,
    volume_digest TEXT,
    quota_summary_json TEXT NOT NULL CHECK (json_valid(quota_summary_json)),
    directory_summary_json TEXT NOT NULL CHECK (json_valid(directory_summary_json)),
    last_command_summary_json TEXT CHECK (
        last_command_summary_json IS NULL OR json_valid(last_command_summary_json)
    ),
    last_error_json TEXT CHECK (last_error_json IS NULL OR json_valid(last_error_json)),
    created_at TEXT NOT NULL,
    last_attached_at TEXT NOT NULL,
    UNIQUE(session_id, agent_member_id),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE CASCADE
);

CREATE TABLE sandbox_run_records (
    sandbox_run_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    sandbox_workspace_id TEXT NOT NULL
        REFERENCES sandbox_workspace_records(sandbox_workspace_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    argv_json TEXT NOT NULL CHECK (json_valid(argv_json)),
    argv_digest TEXT NOT NULL,
    cwd TEXT NOT NULL,
    env_digest TEXT NOT NULL,
    resource_policy_json TEXT NOT NULL CHECK (json_valid(resource_policy_json)),
    source_tree_digest TEXT,
    status TEXT NOT NULL,
    stdout_summary TEXT,
    stderr_summary TEXT,
    stdout_metadata_json TEXT CHECK (
        stdout_metadata_json IS NULL OR json_valid(stdout_metadata_json)
    ),
    stderr_metadata_json TEXT CHECK (
        stderr_metadata_json IS NULL OR json_valid(stderr_metadata_json)
    ),
    exit_code INTEGER,
    duration_ms INTEGER,
    changed_files_summary_json TEXT NOT NULL
        CHECK (json_valid(changed_files_summary_json)),
    error_code TEXT,
    compatibility_json TEXT NOT NULL CHECK (json_valid(compatibility_json)),
    created_at TEXT NOT NULL,
    started_at TEXT,
    ended_at TEXT,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE CASCADE
);
