-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.research
-- phase: tables

CREATE TABLE research_file_index_records (
    index_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    invocation_id TEXT NOT NULL
        REFERENCES engine_invocations(invocation_id) ON DELETE RESTRICT,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE RESTRICT,
    research_kind TEXT NOT NULL CHECK (
        research_kind IN ('source_snapshot', 'citations', 'notes', 'analysis', 'dossier', 'tool_result')
    ),
    ref_id TEXT NOT NULL REFERENCES revision_path_refs(ref_id) ON DELETE RESTRICT,
    bounded_summary TEXT NOT NULL CHECK (length(CAST(bounded_summary AS BLOB)) <= 2048),
    created_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'research_file_index@1'
        CHECK (schema_version = 'research_file_index@1'),
    UNIQUE (invocation_id, research_kind, ref_id)
);

CREATE TABLE session_research_evidence (
    evidence_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    invocation_id TEXT NOT NULL REFERENCES engine_invocations(invocation_id) ON DELETE CASCADE,
    summary_id TEXT NOT NULL REFERENCES session_research_summaries(summary_id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    query TEXT NOT NULL,
    confidence_label TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE session_research_gaps (
    gap_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    invocation_id TEXT NOT NULL REFERENCES engine_invocations(invocation_id) ON DELETE CASCADE,
    summary_id TEXT NOT NULL REFERENCES session_research_summaries(summary_id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE "session_research_source_refs" ("source_ref_id" TEXT PRIMARY KEY, "session_id" TEXT NOT NULL, "task_id" TEXT, "lane_id" TEXT, "invocation_id" TEXT NOT NULL, "evidence_id" TEXT NOT NULL, "title" TEXT NOT NULL, "locator" TEXT NOT NULL, "kind" TEXT NOT NULL, "snippet" TEXT, "created_at" TEXT NOT NULL, "provider" TEXT, "external_id" TEXT, "pmid" TEXT, "doi" TEXT, "authors_json" TEXT NOT NULL DEFAULT '[]', "venue" TEXT, "publication_date" TEXT, "retrieved_at" TEXT, "request_digest" TEXT, "response_digest" TEXT, "provider_provenance_json" TEXT NOT NULL DEFAULT '{}');

CREATE TABLE session_research_summaries (
    summary_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    lane_id TEXT REFERENCES lanes(lane_id) ON DELETE SET NULL,
    invocation_id TEXT NOT NULL REFERENCES engine_invocations(invocation_id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    completion_reason TEXT NOT NULL,
    research_brief TEXT NOT NULL,
    summary TEXT NOT NULL,
    clarification_question TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
