-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.reporting
-- phase: tables

CREATE TABLE "session_report_draft_records" (
    draft_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    task_id TEXT REFERENCES tasks(task_id) ON DELETE SET NULL,
    owner_agent_id TEXT,
    status TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    content_ref TEXT,
    published_report_id TEXT REFERENCES session_report_records(report_id) ON DELETE SET NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "session_report_records" ("report_id" TEXT PRIMARY KEY, "session_id" TEXT NOT NULL, "task_id" TEXT, "lane_id" TEXT, "invocation_id" TEXT, "run_id" TEXT, "status" TEXT NOT NULL, "title" TEXT NOT NULL, "summary" TEXT NOT NULL, "stage_summary" TEXT NOT NULL, "created_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "content_ref_id" TEXT, "report_version" INTEGER NOT NULL DEFAULT 1, "supersedes_report_id" TEXT);
