-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.science
-- phase: tables

CREATE TABLE scientific_attempt_admission_request_records (
    admission_request_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'scientific_attempt_admission_request@1'
        CHECK (schema_version = 'scientific_attempt_admission_request@1'),
    envelope_id TEXT NOT NULL
        REFERENCES scientific_attempt_authorization_records(envelope_id)
        ON DELETE RESTRICT,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT,
    lane_id TEXT NOT NULL REFERENCES lanes(lane_id) ON DELETE RESTRICT,
    campaign_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('formal', 'probe', 'fault')),
    workflow_contract_digest TEXT NOT NULL,
    requested_effect_classes_json TEXT NOT NULL
        CHECK (json_valid(requested_effect_classes_json)),
    provider TEXT,
    hpc_target TEXT,
    reserved_micu INTEGER NOT NULL CHECK (reserved_micu >= 0),
    reserved_cost_microunits INTEGER NOT NULL
        CHECK (reserved_cost_microunits >= 0),
    reserved_wall_time_seconds INTEGER NOT NULL
        CHECK (reserved_wall_time_seconds >= 0),
    actor_ref TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(envelope_id, idempotency_key)
);

CREATE TABLE scientific_attempt_authorization_records (
    envelope_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'scientific_attempt_authorization@1'
        CHECK (schema_version = 'scientific_attempt_authorization@1'),
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT,
    campaign_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    root_ref TEXT NOT NULL,
    grantor_kind TEXT NOT NULL,
    grantor_ref TEXT NOT NULL,
    allowed_scopes_json TEXT NOT NULL CHECK (json_valid(allowed_scopes_json)),
    allowed_effect_classes_json TEXT NOT NULL
        CHECK (json_valid(allowed_effect_classes_json)),
    allowed_providers_json TEXT NOT NULL CHECK (json_valid(allowed_providers_json)),
    allowed_hpc_targets_json TEXT NOT NULL
        CHECK (json_valid(allowed_hpc_targets_json)),
    max_attempts INTEGER NOT NULL CHECK (max_attempts >= 1),
    max_micu INTEGER NOT NULL CHECK (max_micu >= 0),
    max_cost_microunits INTEGER NOT NULL CHECK (max_cost_microunits >= 0),
    max_wall_time_seconds INTEGER NOT NULL CHECK (max_wall_time_seconds >= 0),
    consumed_attempts INTEGER NOT NULL DEFAULT 0
        CHECK (consumed_attempts >= 0 AND consumed_attempts <= max_attempts),
    reserved_micu INTEGER NOT NULL DEFAULT 0
        CHECK (reserved_micu >= 0 AND reserved_micu <= max_micu),
    reserved_cost_microunits INTEGER NOT NULL DEFAULT 0
        CHECK (
            reserved_cost_microunits >= 0
            AND reserved_cost_microunits <= max_cost_microunits
        ),
    reserved_wall_time_seconds INTEGER NOT NULL DEFAULT 0
        CHECK (
            reserved_wall_time_seconds >= 0
            AND reserved_wall_time_seconds <= max_wall_time_seconds
        ),
    expires_at TEXT NOT NULL,
    policy_digest TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('active', 'exhausted', 'expired', 'revoked')
    ),
    state_version INTEGER NOT NULL DEFAULT 1 CHECK (state_version >= 1),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(session_id, grantor_ref, idempotency_key)
);

CREATE TABLE "scientific_attempt_closure_records" ("closure_id" TEXT PRIMARY KEY, "schema_version" TEXT NOT NULL DEFAULT 'scientific_attempt_closure@1', "closure_request_id" TEXT NOT NULL, "attempt_id" TEXT NOT NULL, "selection_id" TEXT NOT NULL, "operation_universe_digest" TEXT NOT NULL, "disposition_digest" TEXT NOT NULL, "adoption_digest" TEXT NOT NULL, "authority_consumption_digest" TEXT NOT NULL, "quiescence_receipt_id" TEXT NOT NULL, "quiescence_receipt_digest" TEXT NOT NULL, "closure_digest" TEXT NOT NULL, "actor_ref" TEXT NOT NULL, "idempotency_key" TEXT NOT NULL, "request_digest" TEXT NOT NULL, "created_at" TEXT NOT NULL);

CREATE TABLE scientific_attempt_closure_request_records (
    closure_request_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL
        DEFAULT 'scientific_attempt_closure_request@1'
        CHECK (schema_version = 'scientific_attempt_closure_request@1'),
    attempt_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    selection_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_chain_selection_records(selection_id)
        ON DELETE RESTRICT,
    actor_ref TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(attempt_id, actor_ref, idempotency_key)
);

CREATE TABLE scientific_attempt_closure_response_records (
    closure_response_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL
        DEFAULT 'scientific_attempt_closure_response@1'
        CHECK (schema_version = 'scientific_attempt_closure_response@1'),
    closure_request_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_attempt_closure_request_records(closure_request_id)
        ON DELETE RESTRICT,
    attempt_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    message_id TEXT NOT NULL UNIQUE
        REFERENCES inbox_messages(message_id) ON DELETE RESTRICT,
    document_id TEXT NOT NULL UNIQUE
        REFERENCES engine_documents(document_id) ON DELETE RESTRICT,
    recipient TEXT NOT NULL,
    recipient_kind TEXT NOT NULL,
    response_digest TEXT NOT NULL,
    binding_digest TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE "scientific_attempt_operation_bindings" ("attempt_id" TEXT NOT NULL, "operation_id" TEXT PRIMARY KEY, "sandbox_run_id" TEXT NOT NULL REFERENCES sandbox_run_records(sandbox_run_id) ON DELETE RESTRICT, "session_id" TEXT NOT NULL, "bound_by" TEXT NOT NULL, "created_at" TEXT NOT NULL);

CREATE TABLE scientific_attempt_records (
    attempt_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'scientific_attempt@1'
        CHECK (schema_version = 'scientific_attempt@1'),
    admission_request_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_attempt_admission_request_records(admission_request_id)
        ON DELETE RESTRICT,
    envelope_id TEXT NOT NULL
        REFERENCES scientific_attempt_authorization_records(envelope_id)
        ON DELETE RESTRICT,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT,
    lane_id TEXT NOT NULL REFERENCES lanes(lane_id) ON DELETE RESTRICT,
    campaign_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('formal', 'probe', 'fault')),
    root_ref TEXT NOT NULL,
    mutation_scope_id TEXT NOT NULL UNIQUE
        REFERENCES mutation_scope_records(scope_id) ON DELETE RESTRICT,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 1),
    request_digest TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    workflow_contract_digest TEXT NOT NULL,
    requested_effect_classes_json TEXT NOT NULL
        CHECK (json_valid(requested_effect_classes_json)),
    provider TEXT,
    hpc_target TEXT,
    reserved_micu INTEGER NOT NULL CHECK (reserved_micu >= 0),
    reserved_cost_microunits INTEGER NOT NULL
        CHECK (reserved_cost_microunits >= 0),
    reserved_wall_time_seconds INTEGER NOT NULL
        CHECK (reserved_wall_time_seconds >= 0),
    status TEXT NOT NULL CHECK (
        status IN ('active', 'closing', 'closed', 'blocked')
    ),
    state_version INTEGER NOT NULL DEFAULT 1 CHECK (state_version >= 1),
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(envelope_id, idempotency_key),
    UNIQUE(envelope_id, ordinal)
);

CREATE TABLE "scientific_attempt_run_bindings" ("sandbox_run_id" TEXT PRIMARY KEY REFERENCES sandbox_run_records(sandbox_run_id) ON DELETE RESTRICT, "attempt_id" TEXT NOT NULL, "session_id" TEXT NOT NULL, "bound_by" TEXT NOT NULL, "created_at" TEXT NOT NULL, UNIQUE("attempt_id", "sandbox_run_id"));

CREATE TABLE scientific_chain_selection_records (
    selection_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'scientific_chain_selection@1'
        CHECK (schema_version = 'scientific_chain_selection@1'),
    attempt_id TEXT NOT NULL
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    revision INTEGER NOT NULL CHECK (revision >= 1),
    parent_selection_id TEXT
        REFERENCES scientific_chain_selection_records(selection_id)
        ON DELETE RESTRICT,
    state TEXT NOT NULL CHECK (state IN ('draft', 'sealed', 'invalidated')),
    operation_universe_digest TEXT NOT NULL,
    operation_count INTEGER NOT NULL CHECK (operation_count >= 0),
    disposition_digest TEXT NOT NULL,
    adoption_digest TEXT NOT NULL,
    workflow_contract_digest TEXT NOT NULL,
    actor_ref TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    sealed_at TEXT,
    UNIQUE(attempt_id, revision),
    UNIQUE(attempt_id, actor_ref, idempotency_key),
    CHECK (
        (revision = 1 AND parent_selection_id IS NULL)
        OR (revision > 1 AND parent_selection_id IS NOT NULL)
    ),
    CHECK (
        (state = 'sealed' AND sealed_at IS NOT NULL)
        OR (state <> 'sealed' AND sealed_at IS NULL)
    )
);

CREATE TABLE "scientific_contract_epoch_records" ("epoch" INTEGER PRIMARY KEY, "contract_id" TEXT NOT NULL, "contract_digest" TEXT NOT NULL, "state" TEXT NOT NULL, "scientific_file_writer_enabled" INTEGER NOT NULL, "prerequisite_receipt_digest" TEXT NOT NULL, "quiescence_receipt_digest" TEXT NOT NULL, "activation_receipt_digest" TEXT, "prepared_at" TEXT NOT NULL, "activated_at" TEXT);

CREATE TABLE scientific_deliverable_bundle_entry_records (
    bundle_id TEXT NOT NULL
        REFERENCES scientific_deliverable_bundle_records(bundle_id) ON DELETE RESTRICT,
    ref_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_deliverable_ref_records(ref_id) ON DELETE RESTRICT,
    scientific_role TEXT NOT NULL,
    repository_path TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal > 0),
    PRIMARY KEY (bundle_id, scientific_role),
    UNIQUE (bundle_id, repository_path),
    UNIQUE (bundle_id, ordinal)
);

CREATE TABLE scientific_deliverable_bundle_records (
    bundle_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    attempt_id TEXT NOT NULL
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    selection_id TEXT NOT NULL
        REFERENCES scientific_chain_selection_records(selection_id) ON DELETE RESTRICT,
    publication_id TEXT NOT NULL
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    publication_digest TEXT NOT NULL,
    contract_id TEXT NOT NULL,
    contract_digest TEXT NOT NULL,
    ref_ids_json TEXT NOT NULL CHECK (json_valid(ref_ids_json)),
    role_manifest_digest TEXT NOT NULL,
    validation_preimage_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    bundle_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'scientific_deliverable_bundle@1'
        CHECK (schema_version = 'scientific_deliverable_bundle@1'),
    UNIQUE (attempt_id, selection_id, contract_id)
);

CREATE TABLE scientific_deliverable_ref_records (
    ref_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    repository_binding_id TEXT NOT NULL,
    repository_binding_version INTEGER NOT NULL CHECK (repository_binding_version > 0),
    repository_policy_digest TEXT NOT NULL,
    publication_id TEXT NOT NULL
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    publication_digest TEXT NOT NULL,
    publication_ref TEXT NOT NULL,
    published_commit TEXT NOT NULL,
    published_tree TEXT NOT NULL,
    repository_path TEXT NOT NULL CHECK (
        repository_path <> ''
        AND substr(repository_path, 1, 1) <> '/'
        AND substr(repository_path, -1, 1) <> '/'
        AND instr(repository_path, '\\') = 0
        AND instr('/' || repository_path || '/', '/../') = 0
        AND instr('/' || repository_path || '/', '/./') = 0
        AND repository_path <> '.git'
        AND substr(repository_path, 1, 5) <> '.git/'
    ),
    storage TEXT NOT NULL CHECK (storage IN ('git_blob', 'git_lfs')),
    git_blob_oid TEXT,
    lfs_oid TEXT,
    lfs_declared_size INTEGER CHECK (lfs_declared_size >= 0),
    actual_size INTEGER NOT NULL CHECK (actual_size >= 0),
    content_digest TEXT NOT NULL,
    scientific_role TEXT NOT NULL,
    format_contract_id TEXT NOT NULL,
    format_contract_digest TEXT NOT NULL,
    deliverable_contract_id TEXT NOT NULL,
    deliverable_contract_digest TEXT NOT NULL,
    producer_operation_id TEXT NOT NULL
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    producer_execution_id TEXT NOT NULL
        REFERENCES controlled_operation_execution_records(execution_id) ON DELETE RESTRICT,
    producer_result_id TEXT NOT NULL,
    producer_result_digest TEXT NOT NULL,
    attempt_id TEXT NOT NULL
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    attempt_state_version INTEGER NOT NULL CHECK (attempt_state_version > 0),
    selection_id TEXT NOT NULL
        REFERENCES scientific_chain_selection_records(selection_id) ON DELETE RESTRICT,
    selection_revision INTEGER NOT NULL CHECK (selection_revision > 0),
    producer_adoption_id TEXT NOT NULL
        REFERENCES scientific_file_effect_adoption_records(adoption_id) ON DELETE RESTRICT,
    selection_adoption_digest TEXT NOT NULL,
    publisher_workspace_id TEXT NOT NULL,
    publisher_workspace_generation INTEGER NOT NULL
        CHECK (publisher_workspace_generation > 0),
    publisher_agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    created_at TEXT NOT NULL,
    supersedes_ref_id TEXT
        REFERENCES scientific_deliverable_ref_records(ref_id) ON DELETE RESTRICT,
    ref_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'scientific_deliverable_ref@1'
        CHECK (schema_version = 'scientific_deliverable_ref@1'),
    UNIQUE (publication_id, repository_path, scientific_role),
    CHECK (
        (storage = 'git_blob' AND git_blob_oid IS NOT NULL
         AND lfs_oid IS NULL AND lfs_declared_size IS NULL)
        OR
        (storage = 'git_lfs' AND git_blob_oid IS NULL
         AND lfs_oid IS NOT NULL AND lfs_declared_size = actual_size)
    ),
    CHECK (supersedes_ref_id IS NULL OR supersedes_ref_id <> ref_id),
    FOREIGN KEY (repository_binding_id, repository_binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
        ON DELETE RESTRICT
);

CREATE TABLE scientific_deliverable_validation_receipt_records (
    receipt_id TEXT PRIMARY KEY,
    bundle_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_deliverable_bundle_records(bundle_id) ON DELETE RESTRICT,
    bundle_digest TEXT NOT NULL,
    publication_id TEXT NOT NULL
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    publication_digest TEXT NOT NULL,
    attempt_id TEXT NOT NULL
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    attempt_state_version INTEGER NOT NULL CHECK (attempt_state_version > 0),
    selection_id TEXT NOT NULL
        REFERENCES scientific_chain_selection_records(selection_id) ON DELETE RESTRICT,
    selection_revision INTEGER NOT NULL CHECK (selection_revision > 0),
    actor_ref TEXT NOT NULL,
    execution_fencing_token INTEGER NOT NULL CHECK (execution_fencing_token > 0),
    validation_preimage_digest TEXT NOT NULL,
    verified_ref_digests_json TEXT NOT NULL
        CHECK (json_valid(verified_ref_digests_json)),
    created_at TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL
        DEFAULT 'scientific_deliverable_validation_receipt@1'
        CHECK (schema_version = 'scientific_deliverable_validation_receipt@1')
);

CREATE TABLE "scientific_effect_adoption_records" ("adoption_id" TEXT PRIMARY KEY, "schema_version" TEXT NOT NULL DEFAULT 'scientific_effect_adoption@1', "selection_id" TEXT NOT NULL, "attempt_id" TEXT NOT NULL, "workflow_role" TEXT NOT NULL, "operation_id" TEXT NOT NULL, "execution_id" TEXT NOT NULL, "result_handle_id" TEXT NOT NULL, "result_digest" TEXT NOT NULL, "effect_certainty" TEXT NOT NULL, "approval_digest" TEXT, "actor_ref" TEXT NOT NULL, "idempotency_key" TEXT NOT NULL, "request_digest" TEXT NOT NULL, "created_at" TEXT NOT NULL);

CREATE TABLE scientific_file_effect_adoption_records (
    adoption_id TEXT PRIMARY KEY,
    selection_id TEXT NOT NULL
        REFERENCES scientific_chain_selection_records(selection_id) ON DELETE RESTRICT,
    selection_revision INTEGER NOT NULL CHECK (selection_revision > 0),
    attempt_id TEXT NOT NULL
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    workflow_role TEXT NOT NULL,
    operation_id TEXT NOT NULL
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    execution_id TEXT NOT NULL
        REFERENCES controlled_operation_execution_records(execution_id) ON DELETE RESTRICT,
    result_id TEXT NOT NULL
        REFERENCES workspace_job_results(result_id) ON DELETE RESTRICT,
    result_digest TEXT NOT NULL,
    effect_certainty TEXT NOT NULL CHECK (
        effect_certainty IN ('effect_known', 'terminal_known')
    ),
    actor_ref TEXT NOT NULL,
    execution_fencing_token INTEGER NOT NULL CHECK (execution_fencing_token > 0),
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    adoption_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'scientific_file_effect_adoption@1'
        CHECK (schema_version = 'scientific_file_effect_adoption@1'),
    UNIQUE (selection_id, workflow_role),
    UNIQUE (selection_id, operation_id),
    UNIQUE (selection_id, actor_ref, idempotency_key)
);

CREATE TABLE scientific_operation_disposition_records (
    disposition_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT 'scientific_operation_disposition@1'
        CHECK (schema_version = 'scientific_operation_disposition@1'),
    selection_id TEXT NOT NULL
        REFERENCES scientific_chain_selection_records(selection_id)
        ON DELETE RESTRICT,
    attempt_id TEXT NOT NULL
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    operation_id TEXT NOT NULL
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    kind TEXT NOT NULL CHECK (
        kind IN ('adopted', 'superseded', 'failed', 'abandoned')
    ),
    workflow_role TEXT,
    reason_code TEXT NOT NULL,
    replacement_operation_id TEXT
        REFERENCES controlled_operation_records(operation_id) ON DELETE RESTRICT,
    actor_ref TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(selection_id, operation_id),
    UNIQUE(selection_id, actor_ref, idempotency_key),
    CHECK (
        (kind = 'adopted' AND workflow_role IS NOT NULL
            AND replacement_operation_id IS NULL)
        OR (kind = 'superseded' AND replacement_operation_id IS NOT NULL
            AND replacement_operation_id <> operation_id)
        OR (kind IN ('failed', 'abandoned')
            AND replacement_operation_id IS NULL)
    )
);

CREATE TABLE scientific_selection_head_records (
    attempt_id TEXT PRIMARY KEY
        REFERENCES scientific_attempt_records(attempt_id) ON DELETE RESTRICT,
    selection_id TEXT NOT NULL UNIQUE
        REFERENCES scientific_chain_selection_records(selection_id)
        ON DELETE RESTRICT,
    revision INTEGER NOT NULL CHECK (revision >= 1),
    state_version INTEGER NOT NULL CHECK (state_version >= 1),
    updated_at TEXT NOT NULL
);

CREATE TABLE "scientific_selection_occurrence_records" ("selection_id" TEXT, "attempt_id" TEXT NOT NULL, "operation_id" TEXT, "sandbox_run_id" TEXT NOT NULL REFERENCES sandbox_run_records(sandbox_run_id) ON DELETE RESTRICT, "occurrence_digest" TEXT NOT NULL, "created_at" TEXT NOT NULL, PRIMARY KEY ("selection_id", "operation_id"));
