-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.workspace.git.lfs
-- phase: tables

CREATE TABLE agent_git_workspace_records (
    workspace_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    reservation_id TEXT NOT NULL,
    reservation_fingerprint TEXT NOT NULL CHECK (
        length(reservation_fingerprint) = 71
        AND substr(reservation_fingerprint, 1, 7) = 'sha256:'
        AND substr(reservation_fingerprint, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    capability_lease_intent_digest TEXT NOT NULL CHECK (
        length(capability_lease_intent_digest) = 71
        AND substr(capability_lease_intent_digest, 1, 7) = 'sha256:'
        AND substr(capability_lease_intent_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    repository_binding_id TEXT NOT NULL
        REFERENCES project_repository_binding_versions(binding_id) ON DELETE RESTRICT,
    repository_binding_version INTEGER NOT NULL
        CHECK (repository_binding_version > 0),
    repository_binding_digest TEXT NOT NULL CHECK (
        length(repository_binding_digest) = 71
        AND substr(repository_binding_digest, 1, 7) = 'sha256:'
        AND substr(repository_binding_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    repository_id TEXT NOT NULL,
    internal_git_service_id TEXT NOT NULL,
    internal_git_endpoint TEXT NOT NULL CHECK (
        substr(internal_git_endpoint, 1, 8) = 'https://'
    ),
    object_format TEXT NOT NULL CHECK (object_format IN ('sha1', 'sha256')),
    base_commit TEXT NOT NULL CHECK (
        (object_format = 'sha1'
         AND length(base_commit) = 40
         AND base_commit NOT GLOB '*[^0-9a-f]*')
        OR
        (object_format = 'sha256'
         AND length(base_commit) = 64
         AND base_commit NOT GLOB '*[^0-9a-f]*')
    ),
    volume_id TEXT NOT NULL UNIQUE,
    clone_logical_root TEXT NOT NULL CHECK (
        substr(clone_logical_root, 1, 1) = '/'
        AND clone_logical_root <> '/'
        AND substr(clone_logical_root, -1, 1) <> '/'
        AND instr(clone_logical_root, '..') = 0
        AND instr(clone_logical_root, '\\') = 0
    ),
    image_ref TEXT NOT NULL CHECK (
        instr(image_ref, '@sha256:') > 1
        AND length(substr(image_ref, instr(image_ref, '@sha256:') + 8)) = 64
        AND substr(image_ref, instr(image_ref, '@sha256:') + 8)
            NOT GLOB '*[^0-9a-f]*'
    ),
    image_manifest_digest TEXT NOT NULL CHECK (
        length(image_manifest_digest) = 71
        AND substr(image_manifest_digest, 1, 7) = 'sha256:'
        AND substr(image_manifest_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    image_qualification_digest TEXT NOT NULL CHECK (
        length(image_qualification_digest) = 71
        AND substr(image_qualification_digest, 1, 7) = 'sha256:'
        AND substr(image_qualification_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    private_ref_namespace TEXT NOT NULL CHECK (
        substr(private_ref_namespace, 1, 5) = 'refs/'
        AND substr(private_ref_namespace, -1, 1) <> '/'
    ),
    repository_policy_version TEXT NOT NULL,
    repository_policy_digest TEXT NOT NULL CHECK (
        length(repository_policy_digest) = 71
        AND substr(repository_policy_digest, 1, 7) = 'sha256:'
        AND substr(repository_policy_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    capability_policy_version TEXT NOT NULL,
    capability_policy_digest TEXT NOT NULL CHECK (
        length(capability_policy_digest) = 71
        AND substr(capability_policy_digest, 1, 7) = 'sha256:'
        AND substr(capability_policy_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    status TEXT NOT NULL CHECK (
        status IN ('provisioning', 'ready', 'blocked', 'frozen', 'replaced')
    ),
    state_version INTEGER NOT NULL CHECK (state_version > 0),
    head_commit TEXT CHECK (
        head_commit IS NULL
        OR (object_format = 'sha1'
            AND length(head_commit) = 40
            AND head_commit NOT GLOB '*[^0-9a-f]*')
        OR (object_format = 'sha256'
            AND length(head_commit) = 64
            AND head_commit NOT GLOB '*[^0-9a-f]*')
    ),
    head_tree TEXT CHECK (
        head_tree IS NULL
        OR (object_format = 'sha1'
            AND length(head_tree) = 40
            AND head_tree NOT GLOB '*[^0-9a-f]*')
        OR (object_format = 'sha256'
            AND length(head_tree) = 64
            AND head_tree NOT GLOB '*[^0-9a-f]*')
    ),
    readiness_observation_digest TEXT CHECK (
        readiness_observation_digest IS NULL
        OR (length(readiness_observation_digest) = 71
            AND substr(readiness_observation_digest, 1, 7) = 'sha256:'
            AND substr(readiness_observation_digest, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    ready_at TEXT,
    blocker_code TEXT CHECK (
        blocker_code IS NULL OR blocker_code IN (
            'missing_volume',
            'cross_agent_volume',
            'corrupt_git_directory',
            'shared_git_directory',
            'remote_identity_drift',
            'object_format_drift',
            'base_commit_drift',
            'generation_drift',
            'unreadable_head',
            'policy_drift',
            'lease_intent_mismatch',
            'repository_binding_drift',
            'image_unqualified',
            'clone_failed',
            'persistence_failed',
            'identity_drift',
            'infrastructure_unavailable',
            'permission_or_configuration_failure',
            'internal_invariant_failure'
        )
    ),
    blocker_detail_digest TEXT CHECK (
        blocker_detail_digest IS NULL
        OR (length(blocker_detail_digest) = 71
            AND substr(blocker_detail_digest, 1, 7) = 'sha256:'
            AND substr(blocker_detail_digest, 8) NOT GLOB '*[^0-9a-f]*')
    ),
    blocked_at TEXT,
    frozen_reason TEXT,
    frozen_at TEXT,
    replaced_by_generation INTEGER CHECK (
        replaced_by_generation IS NULL
        OR replaced_by_generation > workspace_generation
    ),
    replaced_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    workspace_identity_digest TEXT NOT NULL UNIQUE CHECK (
        length(workspace_identity_digest) = 71
        AND substr(workspace_identity_digest, 1, 7) = 'sha256:'
        AND substr(workspace_identity_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    canonical_digest TEXT NOT NULL UNIQUE CHECK (
        length(canonical_digest) = 71
        AND substr(canonical_digest, 1, 7) = 'sha256:'
        AND substr(canonical_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    schema_version TEXT NOT NULL DEFAULT 'agent_git_workspace@1'
        CHECK (schema_version = 'agent_git_workspace@1'),
    UNIQUE (session_id, agent_member_id, workspace_generation),
    UNIQUE (
        workspace_id,
        session_id,
        agent_member_id,
        agent_id,
        workspace_generation
    ),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    FOREIGN KEY (
        reservation_id,
        session_id,
        agent_member_id,
        agent_id,
        workspace_generation
    ) REFERENCES agent_workspace_generation_reservations(
        reservation_id,
        session_id,
        agent_member_id,
        agent_id,
        workspace_generation
    ) ON DELETE RESTRICT,
    CHECK (
        (status = 'provisioning'
         AND state_version = 1
         AND head_commit IS NULL
         AND head_tree IS NULL
         AND readiness_observation_digest IS NULL
         AND ready_at IS NULL
         AND blocker_code IS NULL
         AND blocker_detail_digest IS NULL
         AND blocked_at IS NULL
         AND frozen_reason IS NULL
         AND frozen_at IS NULL
         AND replaced_by_generation IS NULL
         AND replaced_at IS NULL)
        OR
        (status = 'ready'
         AND head_commit IS NOT NULL
         AND head_tree IS NOT NULL
         AND readiness_observation_digest IS NOT NULL
         AND ready_at IS NOT NULL
         AND blocker_code IS NULL
         AND blocker_detail_digest IS NULL
         AND blocked_at IS NULL
         AND frozen_reason IS NULL
         AND frozen_at IS NULL
         AND replaced_by_generation IS NULL
         AND replaced_at IS NULL)
        OR
        (status = 'blocked'
         AND blocker_code IS NOT NULL
         AND blocker_detail_digest IS NOT NULL
         AND blocked_at IS NOT NULL
         AND frozen_reason IS NULL
         AND frozen_at IS NULL
         AND replaced_by_generation IS NULL
         AND replaced_at IS NULL)
        OR
        (status = 'frozen'
         AND frozen_reason IS NOT NULL
         AND frozen_at IS NOT NULL
         AND replaced_by_generation IS NULL
         AND replaced_at IS NULL)
        OR
        (status = 'replaced'
         AND frozen_reason IS NOT NULL
         AND frozen_at IS NOT NULL
         AND replaced_by_generation IS NOT NULL
         AND replaced_at IS NOT NULL)
    )
);

CREATE TABLE agent_workspace_generation_reservations (
    reservation_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    status TEXT NOT NULL CHECK (status IN ('reserved', 'ready', 'replaced')),
    readiness_owner_kind TEXT CHECK (
        readiness_owner_kind IS NULL OR readiness_owner_kind = 'workspace_provisioner'
    ),
    readiness_owner_ref TEXT,
    readiness_ref TEXT,
    readiness_digest TEXT CHECK (
        readiness_digest IS NULL OR (
            length(readiness_digest) = 71
            AND substr(readiness_digest, 1, 7) = 'sha256:'
            AND substr(readiness_digest, 8) NOT GLOB '*[^0-9a-f]*'
        )
    ),
    ready_at TEXT,
    replaced_by_generation INTEGER,
    replaced_at TEXT,
    state_version INTEGER NOT NULL CHECK (state_version > 0),
    reserved_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    immutable_fingerprint TEXT NOT NULL UNIQUE CHECK (
        length(immutable_fingerprint) = 71
        AND substr(immutable_fingerprint, 1, 7) = 'sha256:'
        AND substr(immutable_fingerprint, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    canonical_digest TEXT NOT NULL UNIQUE CHECK (
        length(canonical_digest) = 71
        AND substr(canonical_digest, 1, 7) = 'sha256:'
        AND substr(canonical_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    schema_version TEXT NOT NULL DEFAULT 'agent_workspace_generation_reservation@1'
        CHECK (schema_version = 'agent_workspace_generation_reservation@1'),
    UNIQUE (session_id, agent_member_id, workspace_generation),
    UNIQUE (reservation_id, session_id, agent_member_id, agent_id, workspace_generation),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    CHECK (
        (status = 'reserved'
         AND state_version = 1
         AND readiness_owner_kind IS NULL
         AND readiness_owner_ref IS NULL
         AND readiness_ref IS NULL
         AND readiness_digest IS NULL
         AND ready_at IS NULL
         AND replaced_by_generation IS NULL
         AND replaced_at IS NULL)
        OR
        (status = 'ready'
         AND state_version = 2
         AND readiness_owner_kind IS NOT NULL
         AND readiness_owner_ref IS NOT NULL
         AND readiness_ref IS NOT NULL
         AND readiness_digest IS NOT NULL
         AND ready_at IS NOT NULL
         AND replaced_by_generation IS NULL
         AND replaced_at IS NULL)
        OR
        (status = 'replaced'
         AND replaced_by_generation > workspace_generation
         AND replaced_at IS NOT NULL
         AND (
             (state_version = 2
              AND readiness_owner_kind IS NULL
              AND readiness_owner_ref IS NULL
              AND readiness_ref IS NULL
              AND readiness_digest IS NULL
              AND ready_at IS NULL)
             OR
             (state_version = 3
              AND readiness_owner_kind IS NOT NULL
              AND readiness_owner_ref IS NOT NULL
              AND readiness_ref IS NOT NULL
              AND readiness_digest IS NOT NULL
              AND ready_at IS NOT NULL)
         ))
    )
);

CREATE TABLE "agent_workspace_state_observations" (
    observation_id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    agent_member_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    head_commit TEXT NOT NULL,
    head_tree TEXT NOT NULL,
    dirty_state TEXT NOT NULL CHECK (dirty_state IN ('clean', 'dirty', 'unknown')),
    staged INTEGER NOT NULL CHECK (staged IN (0, 1)),
    unstaged INTEGER NOT NULL CHECK (unstaged IN (0, 1)),
    untracked INTEGER NOT NULL CHECK (untracked IN (0, 1)),
    changed_paths_json TEXT NOT NULL CHECK (
        json_valid(changed_paths_json) AND json_type(changed_paths_json) = 'array'
    ),
    changed_paths_truncated INTEGER NOT NULL CHECK (changed_paths_truncated IN (0, 1)),
    observed_at TEXT NOT NULL,
    schema_version TEXT NOT NULL CHECK (
        schema_version = 'agent_workspace_state_observation@2'
    ),
    FOREIGN KEY (workspace_id) REFERENCES agent_git_workspace_records(workspace_id),
    FOREIGN KEY (session_id, agent_member_id, workspace_generation)
        REFERENCES agent_git_workspace_records(
            session_id, agent_member_id, workspace_generation
        )
);

CREATE TABLE git_lfs_binding_policies (
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    lfs_service_id TEXT NOT NULL,
    lfs_endpoint TEXT NOT NULL,
    object_format TEXT NOT NULL CHECK (object_format = 'sha256'),
    path_rules_json TEXT NOT NULL CHECK (json_valid(path_rules_json)),
    ordinary_blob_threshold_bytes INTEGER NOT NULL
        CHECK (ordinary_blob_threshold_bytes > 0),
    max_object_bytes INTEGER NOT NULL CHECK (max_object_bytes > 0),
    max_workspace_bytes INTEGER NOT NULL CHECK (max_workspace_bytes > 0),
    max_repository_bytes INTEGER NOT NULL CHECK (max_repository_bytes > 0),
    published_retention_class TEXT NOT NULL CHECK (
        published_retention_class = 'published'
    ),
    private_retention_class TEXT NOT NULL CHECK (
        private_retention_class = 'private'
    ),
    private_retention_seconds INTEGER NOT NULL CHECK (private_retention_seconds > 0),
    policy_version TEXT NOT NULL,
    policy_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'git_lfs_binding_policy@1'
        CHECK (schema_version = 'git_lfs_binding_policy@1'),
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (binding_id, binding_version),
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
        ON DELETE RESTRICT,
    UNIQUE (repository_id, binding_version),
    CHECK (max_object_bytes <= max_workspace_bytes),
    CHECK (max_workspace_bytes <= max_repository_bytes)
);

CREATE TABLE git_lfs_closure_entries (
    manifest_digest TEXT NOT NULL
        REFERENCES git_lfs_closure_manifests(manifest_digest) ON DELETE RESTRICT,
    repository_path TEXT NOT NULL,
    file_mode TEXT NOT NULL CHECK (file_mode IN ('100644', '100755')),
    pointer_blob_oid TEXT NOT NULL,
    lfs_oid TEXT NOT NULL CHECK (length(lfs_oid) = 64),
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    object_read_receipt_id TEXT NOT NULL
        REFERENCES git_lfs_object_read_receipts(receipt_id) ON DELETE RESTRICT,
    PRIMARY KEY (manifest_digest, repository_path)
);

CREATE TABLE git_lfs_closure_manifests (
    manifest_digest TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    commit_id TEXT NOT NULL,
    tree_id TEXT NOT NULL,
    policy_digest TEXT NOT NULL,
    lfs_endpoint_identity TEXT NOT NULL,
    authorization_scope_digest TEXT NOT NULL,
    manifest_json TEXT NOT NULL CHECK (json_valid(manifest_json)),
    verified_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'git_lfs_closure_manifest@1'
        CHECK (schema_version = 'git_lfs_closure_manifest@1'),
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES git_lfs_binding_policies(binding_id, binding_version)
        ON DELETE RESTRICT,
    UNIQUE (
        binding_id, binding_version, commit_id, tree_id, policy_digest,
        lfs_endpoint_identity, authorization_scope_digest
    )
);

CREATE TABLE git_lfs_closure_verification_entries (
    verification_id TEXT NOT NULL
        REFERENCES git_lfs_closure_verifications(verification_id) ON DELETE RESTRICT,
    manifest_digest TEXT NOT NULL,
    repository_path TEXT NOT NULL,
    object_read_receipt_id TEXT NOT NULL
        REFERENCES git_lfs_object_read_receipts(receipt_id) ON DELETE RESTRICT,
    PRIMARY KEY (verification_id, repository_path),
    FOREIGN KEY (manifest_digest, repository_path)
        REFERENCES git_lfs_closure_entries(manifest_digest, repository_path)
        ON DELETE RESTRICT
);

CREATE TABLE git_lfs_closure_verifications (
    verification_id TEXT PRIMARY KEY,
    verification_digest TEXT NOT NULL UNIQUE,
    manifest_digest TEXT NOT NULL
        REFERENCES git_lfs_closure_manifests(manifest_digest) ON DELETE RESTRICT,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    authorization_scope_digest TEXT NOT NULL,
    object_read_receipt_ids_json TEXT NOT NULL
        CHECK (json_valid(object_read_receipt_ids_json)),
    observed_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'git_lfs_closure_verification@1'
        CHECK (schema_version = 'git_lfs_closure_verification@1'),
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES git_lfs_binding_policies(binding_id, binding_version)
        ON DELETE RESTRICT
);

CREATE TABLE git_lfs_gc_candidate_items (
    receipt_id TEXT NOT NULL
        REFERENCES git_lfs_gc_candidate_receipts(receipt_id) ON DELETE RESTRICT,
    oid TEXT NOT NULL CHECK (length(oid) = 64),
    PRIMARY KEY (receipt_id, oid)
);

CREATE TABLE git_lfs_gc_candidate_receipts (
    receipt_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    policy_digest TEXT NOT NULL,
    reachability_digest TEXT NOT NULL,
    retirement_receipts_digest TEXT NOT NULL,
    dry_run INTEGER NOT NULL CHECK (dry_run = 1),
    created_at TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'git_lfs_gc_candidate_receipt@1'
        CHECK (schema_version = 'git_lfs_gc_candidate_receipt@1'),
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES git_lfs_binding_policies(binding_id, binding_version)
        ON DELETE RESTRICT
);

CREATE TABLE git_lfs_gc_deletion_receipts (
    deletion_receipt_id TEXT PRIMARY KEY,
    candidate_receipt_id TEXT NOT NULL UNIQUE
        REFERENCES git_lfs_gc_candidate_receipts(receipt_id) ON DELETE RESTRICT,
    exact_revalidation_digest TEXT NOT NULL,
    deleted_oids_json TEXT NOT NULL CHECK (json_valid(deleted_oids_json)),
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE
);

CREATE TABLE git_lfs_object_read_receipts (
    receipt_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    lfs_endpoint_identity TEXT NOT NULL,
    authorization_scope_digest TEXT NOT NULL,
    oid TEXT NOT NULL CHECK (length(oid) = 64),
    declared_size INTEGER NOT NULL CHECK (declared_size >= 0),
    observed_size INTEGER NOT NULL CHECK (observed_size = declared_size),
    observed_sha256 TEXT NOT NULL CHECK (observed_sha256 = oid),
    observed_at TEXT NOT NULL,
    receipt_digest TEXT NOT NULL UNIQUE,
    schema_version TEXT NOT NULL DEFAULT 'git_lfs_object_read_receipt@1'
        CHECK (schema_version = 'git_lfs_object_read_receipt@1'),
    FOREIGN KEY (binding_id, binding_version, oid)
        REFERENCES git_lfs_object_records(binding_id, binding_version, oid)
        ON DELETE RESTRICT
);

CREATE TABLE git_lfs_object_records (
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    oid TEXT NOT NULL CHECK (length(oid) = 64),
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    first_upload_session_id TEXT NOT NULL,
    retention_class TEXT NOT NULL CHECK (retention_class IN ('private', 'published')),
    retained_until TEXT,
    object_receipt_digest TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    deleted_at TEXT,
    deletion_receipt_id TEXT,
    PRIMARY KEY (binding_id, binding_version, oid),
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES git_lfs_binding_policies(binding_id, binding_version)
        ON DELETE RESTRICT,
    FOREIGN KEY (first_upload_session_id)
        REFERENCES git_lfs_upload_sessions(upload_session_id)
        ON DELETE RESTRICT,
    UNIQUE (binding_id, binding_version, repository_id, oid)
);

CREATE TABLE git_lfs_private_reachability_receipts (
    receipt_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    namespace_id TEXT NOT NULL
        REFERENCES repository_private_namespace_records(namespace_id)
        ON DELETE RESTRICT,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    terminal_refs_digest TEXT NOT NULL,
    terminal_commits_digest TEXT NOT NULL,
    reachable_oids_json TEXT NOT NULL CHECK (json_valid(reachable_oids_json)),
    reachability_digest TEXT NOT NULL UNIQUE,
    retirement_receipt_id TEXT NOT NULL
        REFERENCES repository_private_namespace_retirement_receipts(receipt_id)
        ON DELETE RESTRICT,
    created_at TEXT NOT NULL,
    schema_version TEXT NOT NULL DEFAULT 'git_lfs_private_reachability_receipt@1'
        CHECK (schema_version = 'git_lfs_private_reachability_receipt@1'),
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES git_lfs_binding_policies(binding_id, binding_version)
        ON DELETE RESTRICT
);

CREATE TABLE git_lfs_publication_closures (
    publication_id TEXT PRIMARY KEY
        REFERENCES published_revisions(publication_id) ON DELETE RESTRICT,
    manifest_digest TEXT NOT NULL
        REFERENCES git_lfs_closure_manifests(manifest_digest) ON DELETE RESTRICT,
    verification_id TEXT NOT NULL
        REFERENCES git_lfs_closure_verifications(verification_id) ON DELETE RESTRICT,
    verification_digest TEXT NOT NULL,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    pinned_at TEXT NOT NULL,
    UNIQUE (publication_id, manifest_digest)
);

CREATE TABLE git_lfs_publication_intent_proofs (
    intent_id TEXT PRIMARY KEY
        REFERENCES workspace_publication_intents(intent_id) ON DELETE RESTRICT,
    publication_id TEXT NOT NULL UNIQUE,
    manifest_digest TEXT NOT NULL
        REFERENCES git_lfs_closure_manifests(manifest_digest) ON DELETE RESTRICT,
    verification_id TEXT NOT NULL
        REFERENCES git_lfs_closure_verifications(verification_id) ON DELETE RESTRICT,
    verification_digest TEXT NOT NULL,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    commit_id TEXT NOT NULL,
    tree_id TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE git_lfs_publication_pins (
    publication_id TEXT NOT NULL
        REFERENCES git_lfs_publication_closures(publication_id) ON DELETE RESTRICT,
    manifest_digest TEXT NOT NULL
        REFERENCES git_lfs_closure_manifests(manifest_digest) ON DELETE RESTRICT,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    lfs_oid TEXT NOT NULL CHECK (length(lfs_oid) = 64),
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    pinned_at TEXT NOT NULL,
    PRIMARY KEY (publication_id, lfs_oid),
    FOREIGN KEY (binding_id, binding_version, lfs_oid)
        REFERENCES git_lfs_object_records(binding_id, binding_version, oid)
        ON DELETE RESTRICT
);

CREATE TABLE git_lfs_quota_reservations (
    reservation_id TEXT PRIMARY KEY,
    upload_session_id TEXT NOT NULL UNIQUE,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    oid TEXT NOT NULL CHECK (length(oid) = 64),
    reserved_bytes INTEGER NOT NULL CHECK (reserved_bytes >= 0),
    state TEXT NOT NULL CHECK (state IN ('reserved', 'committed', 'released')),
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    settled_at TEXT,
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES git_lfs_binding_policies(binding_id, binding_version)
        ON DELETE RESTRICT,
    FOREIGN KEY (upload_session_id)
        REFERENCES git_lfs_upload_sessions(upload_session_id)
        ON DELETE RESTRICT
);

CREATE TABLE git_lfs_upload_sessions (
    upload_session_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    credential_id TEXT NOT NULL
        REFERENCES repository_credential_issuance_records(credential_id)
        ON DELETE RESTRICT,
    oid TEXT NOT NULL CHECK (length(oid) = 64),
    declared_size INTEGER NOT NULL CHECK (declared_size >= 0),
    reserved_bytes INTEGER NOT NULL CHECK (reserved_bytes = declared_size),
    status TEXT NOT NULL CHECK (status IN ('reserved', 'committed', 'aborted')),
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    completed_at TEXT,
    schema_version TEXT NOT NULL DEFAULT 'git_lfs_upload_session@1'
        CHECK (schema_version = 'git_lfs_upload_session@1'),
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES git_lfs_binding_policies(binding_id, binding_version)
        ON DELETE RESTRICT,
    UNIQUE (
        binding_id, binding_version, session_id, agent_member_id,
        workspace_generation, credential_id, oid, declared_size
    )
);

CREATE TABLE git_lfs_workspace_object_links (
    link_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    credential_id TEXT NOT NULL
        REFERENCES repository_credential_issuance_records(credential_id)
        ON DELETE RESTRICT,
    oid TEXT NOT NULL CHECK (length(oid) = 64),
    observed_via TEXT NOT NULL CHECK (observed_via IN ('upload', 'download')),
    created_at TEXT NOT NULL,
    FOREIGN KEY (binding_id, binding_version, oid)
        REFERENCES git_lfs_object_records(binding_id, binding_version, oid)
        ON DELETE RESTRICT,
    UNIQUE (
        binding_id, binding_version, session_id, agent_member_id,
        workspace_generation, oid
    )
);

CREATE TABLE repository_credential_issuance_records (
    credential_id TEXT PRIMARY KEY,
    token_digest TEXT NOT NULL UNIQUE,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    capability_lease_id TEXT NOT NULL,
    protocols_json TEXT NOT NULL CHECK (json_valid(protocols_json)),
    ref_classes_json TEXT NOT NULL CHECK (json_valid(ref_classes_json)),
    claims_digest TEXT NOT NULL,
    issued_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked_at TEXT,
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
        ON DELETE RESTRICT
);

CREATE TABLE repository_private_namespace_holds (
    hold_id TEXT PRIMARY KEY,
    namespace_id TEXT NOT NULL
        REFERENCES repository_private_namespace_records(namespace_id) ON DELETE RESTRICT,
    hold_kind TEXT NOT NULL CHECK (
        hold_kind IN (
            'active_capability_lease',
            'publication_pin',
            'historical_migration_pin',
            'legal_hold',
            'audit_hold',
            'retained_reference'
        )
    ),
    owner_ref TEXT NOT NULL,
    created_at TEXT NOT NULL,
    released_at TEXT
);

CREATE TABLE repository_private_namespace_records (
    namespace_id TEXT PRIMARY KEY,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    namespace_prefix TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('open', 'closed', 'retired')),
    retention_deadline TEXT NOT NULL,
    opened_at TEXT NOT NULL,
    closed_at TEXT,
    retired_at TEXT,
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
        ON DELETE RESTRICT,
    UNIQUE (session_id, agent_member_id, workspace_generation)
);

CREATE TABLE repository_private_namespace_retirement_receipts (
    receipt_id TEXT PRIMARY KEY,
    namespace_id TEXT NOT NULL UNIQUE
        REFERENCES repository_private_namespace_records(namespace_id) ON DELETE RESTRICT,
    binding_id TEXT NOT NULL,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    namespace_prefix TEXT NOT NULL,
    terminal_refs_json TEXT NOT NULL CHECK (json_valid(terminal_refs_json)),
    terminal_commits_json TEXT NOT NULL CHECK (json_valid(terminal_commits_json)),
    receipt_digest TEXT NOT NULL UNIQUE,
    receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    FOREIGN KEY (binding_id, binding_version)
        REFERENCES project_repository_binding_versions(binding_id, binding_version)
        ON DELETE RESTRICT
);

CREATE TABLE repository_provision_credential_records (
    credential_id TEXT PRIMARY KEY,
    token_digest TEXT NOT NULL UNIQUE CHECK (
        length(token_digest) = 71
        AND substr(token_digest, 1, 7) = 'sha256:'
        AND substr(token_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    workspace_id TEXT NOT NULL
        REFERENCES agent_git_workspace_records(workspace_id) ON DELETE RESTRICT,
    binding_id TEXT NOT NULL
        REFERENCES project_repository_binding_versions(binding_id) ON DELETE RESTRICT,
    binding_version INTEGER NOT NULL CHECK (binding_version > 0),
    repository_id TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
    agent_member_id TEXT NOT NULL
        REFERENCES agent_members(member_id) ON DELETE RESTRICT,
    agent_id TEXT NOT NULL,
    workspace_generation INTEGER NOT NULL CHECK (workspace_generation > 0),
    capability_lease_id TEXT NOT NULL
        REFERENCES agent_capability_lease_records(lease_id) ON DELETE RESTRICT,
    protocols_json TEXT NOT NULL
        DEFAULT '["git_read","lfs_read"]'
        CHECK (protocols_json = '["git_read","lfs_read"]'),
    claims_digest TEXT NOT NULL CHECK (
        length(claims_digest) = 71
        AND substr(claims_digest, 1, 7) = 'sha256:'
        AND substr(claims_digest, 8) NOT GLOB '*[^0-9a-f]*'
    ),
    issued_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked_at TEXT,
    schema_version TEXT NOT NULL DEFAULT 'repository_provision_credential@1'
        CHECK (schema_version = 'repository_provision_credential@1'),
    FOREIGN KEY (session_id, agent_id)
        REFERENCES agent_members(session_id, agent_id) ON DELETE RESTRICT,
    FOREIGN KEY (
        workspace_id,
        session_id,
        agent_member_id,
        agent_id,
        workspace_generation
    ) REFERENCES agent_git_workspace_records(
        workspace_id,
        session_id,
        agent_member_id,
        agent_id,
        workspace_generation
    ) ON DELETE RESTRICT
);
