-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.compute
-- phase: indexes

CREATE INDEX idx_session_run_records_invocation_id ON session_run_records(invocation_id);

CREATE UNIQUE INDEX idx_session_run_records_runner_key
    ON session_run_records(session_id, invocation_id, runner_run_id);

CREATE INDEX idx_session_run_records_session_id ON session_run_records(session_id);

CREATE INDEX idx_session_run_records_task_id ON session_run_records(task_id);
