-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.kernel
-- phase: indexes

CREATE UNIQUE INDEX idx_file_workspace_public_single_active
    ON file_workspace_public_epoch_records(state) WHERE state = 'active';

CREATE INDEX idx_agent_capability_lease_events_owner
    ON agent_capability_lease_lifecycle_events(lease_id, state_version);

CREATE UNIQUE INDEX idx_agent_capability_lease_one_active
    ON agent_capability_lease_records(session_id, agent_member_id)
    WHERE status = 'active';

CREATE INDEX idx_agent_capability_lease_parent
    ON agent_capability_lease_records(parent_lease_id);

CREATE INDEX idx_agent_capability_lease_policy
    ON agent_capability_lease_records(
        session_id,
        policy_version,
        policy_digest,
        status
    );

CREATE INDEX idx_agent_members_session_handle
ON agent_members(session_id, handle);

CREATE INDEX idx_agent_members_session_id ON agent_members(session_id);

CREATE INDEX idx_agent_runtime_signals_agent_id ON agent_runtime_signals(agent_id);

CREATE INDEX idx_agent_runtime_signals_capability_lease
    ON agent_runtime_signals(capability_lease_id, workspace_generation, status);

CREATE INDEX idx_agent_runtime_signals_claim_expires_at
    ON agent_runtime_signals(claim_expires_at);

CREATE INDEX idx_agent_runtime_signals_created_at ON agent_runtime_signals(created_at);

CREATE INDEX idx_agent_runtime_signals_session_id ON agent_runtime_signals(session_id);

CREATE INDEX idx_agent_runtime_signals_session_lease_token
    ON agent_runtime_signals(session_lease_token);

CREATE INDEX idx_agent_runtime_signals_session_status_created
    ON agent_runtime_signals(session_id, status, created_at);

CREATE INDEX idx_agent_runtime_signals_source_ref ON agent_runtime_signals(source_ref);

CREATE INDEX idx_agent_runtime_signals_status ON agent_runtime_signals(status);

CREATE INDEX idx_approval_requests_session_id ON approval_requests(session_id);

CREATE INDEX idx_command_receipts_session
    ON command_receipt_records(session_id, created_at);

CREATE INDEX idx_continuation_delivery_claim
    ON continuation_state_records(delivery_state, delivery_lease_expires_at, updated_at);

CREATE INDEX idx_continuation_originating_signal
    ON continuation_state_records(originating_signal_id);

CREATE INDEX idx_continuation_states_approval
    ON continuation_state_records(approval_id);

CREATE INDEX idx_continuation_states_claim
    ON continuation_state_records(status, claim_expires_at);

CREATE UNIQUE INDEX idx_continuation_states_operation
    ON continuation_state_records(operation_id);

CREATE INDEX idx_continuation_states_session
    ON continuation_state_records(session_id, created_at);

CREATE INDEX idx_controlled_operation_dispatch_requests_session
    ON controlled_operation_dispatch_requests(session_id, created_at);

CREATE INDEX idx_controlled_operation_execution_events_operation
    ON controlled_operation_execution_events(operation_id, state_version);

CREATE INDEX idx_controlled_operation_execution_events_session
    ON controlled_operation_execution_events(session_id, created_at);

CREATE INDEX idx_controlled_operation_executions_approval
    ON controlled_operation_execution_records(approval_id);

CREATE INDEX idx_controlled_operation_executions_claim
    ON controlled_operation_execution_records(
        lifecycle_state,
        lease_expires_at,
        updated_at
    );

CREATE INDEX idx_controlled_operation_executions_session_state
    ON controlled_operation_execution_records(session_id, lifecycle_state, updated_at);

CREATE INDEX idx_controlled_operation_provider_dispatch_session
    ON controlled_operation_provider_dispatch_receipts(session_id, created_at);

CREATE INDEX idx_controlled_operation_provider_observation_session
    ON controlled_operation_provider_observation_receipts(
        session_id,
        execution_id,
        observation_index
    );

CREATE INDEX idx_controlled_operation_result_handles_operation
    ON controlled_operation_result_handles(operation_id);

CREATE INDEX idx_controlled_operation_result_handles_session
    ON controlled_operation_result_handles(session_id, created_at);

CREATE INDEX idx_controlled_operations_approval
    ON controlled_operation_records(approval_id);

CREATE INDEX idx_controlled_operations_digest
    ON controlled_operation_records(session_id, operation_digest);

CREATE INDEX idx_controlled_operations_route_policy
    ON controlled_operation_records(route_policy_id);

CREATE INDEX idx_controlled_operations_sdk_module
    ON controlled_operation_records(sdk_module, function_name);

CREATE INDEX idx_controlled_operations_session
    ON controlled_operation_records(session_id, created_at);

CREATE INDEX idx_durable_events_session_cursor
    ON durable_event_records(session_id, cursor);

CREATE INDEX idx_durable_events_session_type_cursor
    ON durable_event_records(session_id, event_type, cursor);

CREATE UNIQUE INDEX idx_durable_events_trace_id
    ON durable_event_records(
        session_id,
        json_extract(payload_json, '$.trace_id')
    )
    WHERE event_type = 'llm.response.created'
      AND json_extract(payload_json, '$.trace_id') IS NOT NULL;

CREATE INDEX idx_engine_documents_invocation_id ON engine_documents(invocation_id);

CREATE INDEX idx_engine_documents_session_id ON engine_documents(session_id);

CREATE UNIQUE INDEX idx_engine_invocations_idempotency_key ON engine_invocations(session_id, idempotency_key);

CREATE INDEX idx_engine_invocations_session_id ON engine_invocations(session_id);

CREATE INDEX idx_failure_hypotheses_failure_created
    ON failure_hypothesis_records(failure_id, created_at, hypothesis_id);

CREATE INDEX idx_failure_hypotheses_session_created
    ON failure_hypothesis_records(session_id, created_at, hypothesis_id);

CREATE INDEX idx_failure_observations_session_created
    ON failure_observation_records(session_id, created_at, failure_id);

CREATE INDEX idx_failure_observations_source
    ON failure_observation_records(source_kind, source_ref, source_version);

CREATE INDEX idx_failure_observations_task_created
    ON failure_observation_records(task_id, created_at, failure_id);

CREATE INDEX idx_failure_recovery_dispositions_failure_created
    ON failure_recovery_disposition_records(
        failure_id, created_at, disposition_id
    );

CREATE INDEX idx_failure_recovery_dispositions_session_created
    ON failure_recovery_disposition_records(
        session_id, created_at, disposition_id
    );

CREATE UNIQUE INDEX idx_file_workspace_public_one_active
    ON file_workspace_public_epoch_records(state) WHERE state = 'active';

CREATE INDEX idx_inbox_messages_session_id ON inbox_messages(session_id);

CREATE INDEX idx_lane_lifecycle_events_lane_id ON lane_lifecycle_events(lane_id);

CREATE INDEX idx_lane_lifecycle_events_session_id ON lane_lifecycle_events(session_id);

CREATE INDEX idx_lanes_session_id ON lanes(session_id);

CREATE INDEX idx_memory_entries_session_id ON memory_entries(session_id);

CREATE UNIQUE INDEX idx_mutation_scopes_one_active_per_session
    ON mutation_scope_records(session_id)
    WHERE session_id IS NOT NULL
      AND state IN ('open', 'freezing', 'quiescent');

CREATE INDEX idx_mutation_scopes_parent
    ON mutation_scope_records(parent_scope_id, state);

CREATE INDEX idx_mutation_scopes_ref_state
    ON mutation_scope_records(scope_kind, scope_ref, state, generation);

CREATE INDEX idx_mutation_scopes_session_generation
    ON mutation_scope_records(session_id, generation, state);

CREATE INDEX idx_mutation_writers_parent
    ON mutation_writer_records(parent_writer_id, state);

CREATE INDEX idx_mutation_writers_scope_state
    ON mutation_writer_records(scope_id, scope_generation, state, registered_at);

CREATE INDEX idx_project_repository_bindings_repository
    ON project_repository_binding_versions(repository_id, binding_version);

CREATE INDEX idx_published_revisions_session
    ON published_revisions(session_id, created_at, publication_id);

CREATE INDEX idx_quiescence_receipts_scope
    ON quiescence_receipt_records(scope_id, seal_generation);

CREATE INDEX idx_repository_binding_lifecycle_identity
    ON project_repository_binding_lifecycle_events(
        project_id,
        binding_version,
        created_at
    );

CREATE INDEX idx_runtime_commands_claim
    ON runtime_command_records(status, lease_expires_at, accepted_at);

CREATE INDEX idx_runtime_commands_session_status
    ON runtime_command_records(session_id, status, accepted_at);

CREATE INDEX idx_session_access_principal
ON session_access_records(principal_id, session_id);

CREATE UNIQUE INDEX idx_session_access_single_owner
ON session_access_records(session_id)
WHERE access_role = 'owner';

CREATE INDEX idx_session_repository_binding_identity
    ON session_repository_binding_pins(binding_id, binding_version, session_id);

CREATE INDEX idx_session_runtime_leases_expires_at
    ON session_runtime_leases(expires_at);

CREATE INDEX idx_session_runtime_leases_fencing
    ON session_runtime_leases(session_id, fencing_token);

CREATE UNIQUE INDEX idx_session_runtime_leases_one_unreleased
    ON session_runtime_leases(session_id)
    WHERE released_at IS NULL;

CREATE INDEX idx_session_runtime_leases_session_id
    ON session_runtime_leases(session_id);

CREATE INDEX idx_task_dependencies_task_id ON task_dependencies(task_id);

CREATE INDEX idx_tasks_lane_id ON tasks(lane_id);

CREATE INDEX idx_tasks_session_id ON tasks(session_id);

CREATE INDEX idx_verified_workspace_checkpoint_latest
    ON verified_workspace_checkpoint_records(
        session_id, agent_member_id, workspace_generation, verified_at DESC,
        checkpoint_id DESC
    );

CREATE INDEX idx_workspace_publication_executions_claim
    ON workspace_publication_execution_records(
        lifecycle_state, lease_expires_at, updated_at, execution_id
    );

CREATE INDEX idx_workspace_publication_intents_session
    ON workspace_publication_intents(session_id, created_at, publication_id);

CREATE INDEX idx_workspace_publication_intents_workspace
    ON workspace_publication_intents(workspace_id, workspace_generation, created_at);

CREATE UNIQUE INDEX revision_path_refs_publication_path_identity
    ON revision_path_refs(publication_id, repository_path, entry_kind, object_id);

CREATE INDEX revision_path_refs_session_publication
    ON revision_path_refs(session_id, publication_id, repository_path);
