-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.process.podman
-- phase: indexes

CREATE UNIQUE INDEX idx_sandbox_image_default
    ON sandbox_image_records(is_default) WHERE is_default = 1;

CREATE INDEX idx_sandbox_workspace_session
    ON sandbox_workspace_records(session_id);

CREATE INDEX idx_sandbox_workspace_agent_member
    ON sandbox_workspace_records(agent_member_id);

CREATE INDEX idx_sandbox_run_records_session
    ON sandbox_run_records(session_id, created_at);

CREATE INDEX idx_sandbox_run_records_workspace
    ON sandbox_run_records(sandbox_workspace_id, created_at);

CREATE UNIQUE INDEX idx_sandbox_run_records_active_workspace
    ON sandbox_run_records(sandbox_workspace_id)
    WHERE status IN ('queued', 'running');
