-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.research
-- phase: indexes

CREATE INDEX idx_session_research_evidence_invocation_id ON session_research_evidence(invocation_id);

CREATE INDEX idx_session_research_evidence_session_id ON session_research_evidence(session_id);

CREATE INDEX idx_session_research_gaps_invocation_id ON session_research_gaps(invocation_id);

CREATE INDEX idx_session_research_gaps_session_id ON session_research_gaps(session_id);

CREATE INDEX idx_session_research_source_refs_doi
    ON session_research_source_refs(doi);

CREATE INDEX idx_session_research_source_refs_evidence_id ON session_research_source_refs(evidence_id);

CREATE INDEX idx_session_research_source_refs_invocation_id ON session_research_source_refs(invocation_id);

CREATE INDEX idx_session_research_source_refs_pmid
    ON session_research_source_refs(pmid);

CREATE INDEX idx_session_research_source_refs_session_id ON session_research_source_refs(session_id);

CREATE UNIQUE INDEX idx_session_research_summaries_invocation_id ON session_research_summaries(invocation_id);

CREATE INDEX idx_session_research_summaries_session_id ON session_research_summaries(session_id);
