-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.reporting
-- phase: indexes

CREATE INDEX idx_session_report_draft_records_owner_agent_id
    ON session_report_draft_records(owner_agent_id);

CREATE INDEX idx_session_report_draft_records_session_id
    ON session_report_draft_records(session_id);

CREATE INDEX idx_session_report_draft_records_task_id
    ON session_report_draft_records(task_id);

CREATE UNIQUE INDEX idx_session_report_draft_records_task_id_active
    ON session_report_draft_records(session_id, task_id)
    WHERE task_id IS NOT NULL;

CREATE INDEX idx_session_report_records_invocation_id ON session_report_records(invocation_id);

CREATE INDEX idx_session_report_records_session_id ON session_report_records(session_id);

CREATE INDEX idx_session_report_records_task_id ON session_report_records(task_id);

CREATE UNIQUE INDEX session_report_records_content_ref_unique
    ON session_report_records(content_ref_id)
    WHERE content_ref_id IS NOT NULL;

CREATE UNIQUE INDEX session_report_records_supersedes_unique
    ON session_report_records(supersedes_report_id)
    WHERE supersedes_report_id IS NOT NULL;
