-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.science
-- phase: indexes

CREATE INDEX idx_scientific_attempt_admission_requests_session
    ON scientific_attempt_admission_request_records(
        session_id, task_id, campaign_id, created_at
    );

CREATE INDEX idx_scientific_attempt_operation_bindings_attempt
    ON scientific_attempt_operation_bindings(
        attempt_id, created_at, operation_id
    );

CREATE INDEX idx_scientific_attempts_task_campaign
    ON scientific_attempt_records(
        session_id, task_id, campaign_id, workflow_id, created_at
    );

CREATE INDEX idx_scientific_authority_task_campaign
    ON scientific_attempt_authorization_records(
        session_id, task_id, campaign_id, workflow_id, created_at
    );

CREATE UNIQUE INDEX idx_scientific_contract_one_active
    ON scientific_contract_epoch_records(state) WHERE state = 'active';

CREATE INDEX idx_scientific_selection_occurrences_attempt
    ON scientific_selection_occurrence_records(
        attempt_id, selection_id, operation_id
    );
