-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.workspace.git.lfs
-- phase: indexes

CREATE UNIQUE INDEX idx_agent_git_workspace_one_current
    ON agent_git_workspace_records(session_id, agent_member_id)
    WHERE status <> 'replaced';

CREATE INDEX idx_agent_git_workspace_owner
    ON agent_git_workspace_records(
        session_id,
        agent_member_id,
        workspace_generation
    );

CREATE UNIQUE INDEX idx_agent_workspace_generation_one_current
    ON agent_workspace_generation_reservations(session_id, agent_member_id)
    WHERE status IN ('reserved', 'ready');

CREATE INDEX idx_agent_workspace_generation_owner
    ON agent_workspace_generation_reservations(
        session_id,
        agent_member_id,
        workspace_generation
    );

CREATE INDEX idx_agent_workspace_state_latest
    ON agent_workspace_state_observations(
        session_id, agent_member_id, workspace_generation, observed_at DESC,
        observation_id DESC
    );

CREATE INDEX idx_git_lfs_quota_repository_active
    ON git_lfs_quota_reservations(repository_id, state, expires_at);

CREATE INDEX idx_git_lfs_quota_workspace_active
    ON git_lfs_quota_reservations(
        session_id, agent_member_id, workspace_generation, state, expires_at
    );

CREATE INDEX idx_repository_credential_scope
    ON repository_credential_issuance_records(
        session_id,
        agent_member_id,
        workspace_generation,
        expires_at
    );

CREATE INDEX idx_repository_private_namespace_active_holds
    ON repository_private_namespace_holds(namespace_id, released_at);

CREATE UNIQUE INDEX idx_repository_provision_credential_one_open
    ON repository_provision_credential_records(workspace_id)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_repository_provision_credential_workspace
    ON repository_provision_credential_records(workspace_id, revoked_at, expires_at);
