-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.compute
-- phase: triggers

CREATE TRIGGER compute_source_manifests_immutable_delete
BEFORE DELETE ON compute_source_manifests
BEGIN SELECT RAISE(ABORT, 'compute source manifest is immutable'); END;

CREATE TRIGGER compute_source_manifests_immutable_update
BEFORE UPDATE ON compute_source_manifests
BEGIN SELECT RAISE(ABORT, 'compute source manifest is immutable'); END;

CREATE TRIGGER mutation_guard_compute_source_manifests_delete
BEFORE DELETE ON compute_source_manifests
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = OLD.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = OLD.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: compute_source_manifests'); END;

CREATE TRIGGER mutation_guard_compute_source_manifests_insert
BEFORE INSERT ON compute_source_manifests
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = NEW.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = NEW.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: compute_source_manifests'); END;

CREATE TRIGGER mutation_guard_compute_source_manifests_update
BEFORE UPDATE ON compute_source_manifests
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = OLD.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = OLD.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: compute_source_manifests'); END;

CREATE TRIGGER mutation_guard_session_run_records_delete
BEFORE DELETE ON session_run_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_session_run_records_insert
BEFORE INSERT ON session_run_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_session_run_records_update
BEFORE UPDATE ON session_run_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END) OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_workspace_external_job_handles_delete
BEFORE DELETE ON workspace_external_job_handles
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN workspace_job_dispatch_intents AS intent ON intent.request_id = request.request_id
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE intent.dispatch_id = OLD.dispatch_id
) THEN openzyme_mutation_write_allowed((
    SELECT request.session_id FROM workspace_revision_execution_requests AS request
    JOIN workspace_job_dispatch_intents AS intent ON intent.request_id = request.request_id
    WHERE intent.dispatch_id = OLD.dispatch_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_external_job_handles'); END;

CREATE TRIGGER mutation_guard_workspace_external_job_handles_insert
BEFORE INSERT ON workspace_external_job_handles
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN workspace_job_dispatch_intents AS intent ON intent.request_id = request.request_id
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE intent.dispatch_id = NEW.dispatch_id
) THEN openzyme_mutation_write_allowed((
    SELECT request.session_id FROM workspace_revision_execution_requests AS request
    JOIN workspace_job_dispatch_intents AS intent ON intent.request_id = request.request_id
    WHERE intent.dispatch_id = NEW.dispatch_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_external_job_handles'); END;

CREATE TRIGGER mutation_guard_workspace_external_job_handles_update
BEFORE UPDATE ON workspace_external_job_handles
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN workspace_job_dispatch_intents AS intent ON intent.request_id = request.request_id
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE intent.dispatch_id = OLD.dispatch_id
) THEN openzyme_mutation_write_allowed((
    SELECT request.session_id FROM workspace_revision_execution_requests AS request
    JOIN workspace_job_dispatch_intents AS intent ON intent.request_id = request.request_id
    WHERE intent.dispatch_id = OLD.dispatch_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_external_job_handles'); END;

CREATE TRIGGER mutation_guard_workspace_external_job_observations_delete
BEFORE DELETE ON workspace_external_job_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_external_job_observations'); END;

CREATE TRIGGER mutation_guard_workspace_external_job_observations_insert
BEFORE INSERT ON workspace_external_job_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = NEW.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = NEW.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_external_job_observations'); END;

CREATE TRIGGER mutation_guard_workspace_external_job_observations_update
BEFORE UPDATE ON workspace_external_job_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_external_job_observations'); END;

CREATE TRIGGER mutation_guard_workspace_job_cancellation_intents_delete
BEFORE DELETE ON workspace_job_cancellation_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_cancellation_intents'); END;

CREATE TRIGGER mutation_guard_workspace_job_cancellation_intents_insert
BEFORE INSERT ON workspace_job_cancellation_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = NEW.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = NEW.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_cancellation_intents'); END;

CREATE TRIGGER mutation_guard_workspace_job_cancellation_intents_update
BEFORE UPDATE ON workspace_job_cancellation_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_cancellation_intents'); END;

CREATE TRIGGER mutation_guard_workspace_job_cancellation_receipts_delete
BEFORE DELETE ON workspace_job_cancellation_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_job_cancellation_intents AS intent
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = intent.execution_id
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE intent.cancellation_id = OLD.cancellation_id
) THEN openzyme_mutation_write_allowed((
    SELECT execution.session_id FROM workspace_job_cancellation_intents AS intent
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = intent.execution_id
    WHERE intent.cancellation_id = OLD.cancellation_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_cancellation_receipts'); END;

CREATE TRIGGER mutation_guard_workspace_job_cancellation_receipts_insert
BEFORE INSERT ON workspace_job_cancellation_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_job_cancellation_intents AS intent
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = intent.execution_id
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE intent.cancellation_id = NEW.cancellation_id
) THEN openzyme_mutation_write_allowed((
    SELECT execution.session_id
    FROM workspace_job_cancellation_intents AS intent
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = intent.execution_id
    WHERE intent.cancellation_id = NEW.cancellation_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_cancellation_receipts'); END;

CREATE TRIGGER mutation_guard_workspace_job_cancellation_receipts_update
BEFORE UPDATE ON workspace_job_cancellation_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_job_cancellation_intents AS intent
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = intent.execution_id
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE intent.cancellation_id = OLD.cancellation_id
) THEN openzyme_mutation_write_allowed((
    SELECT execution.session_id FROM workspace_job_cancellation_intents AS intent
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = intent.execution_id
    WHERE intent.cancellation_id = OLD.cancellation_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_cancellation_receipts'); END;

CREATE TRIGGER mutation_guard_workspace_job_dispatch_intents_delete
BEFORE DELETE ON workspace_job_dispatch_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = OLD.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = OLD.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_dispatch_intents'); END;

CREATE TRIGGER mutation_guard_workspace_job_dispatch_intents_insert
BEFORE INSERT ON workspace_job_dispatch_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = NEW.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = NEW.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_dispatch_intents'); END;

CREATE TRIGGER mutation_guard_workspace_job_dispatch_intents_update
BEFORE UPDATE ON workspace_job_dispatch_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = OLD.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = OLD.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_dispatch_intents'); END;

CREATE TRIGGER mutation_guard_workspace_job_result_revision_links_delete
BEFORE DELETE ON workspace_job_result_revision_links
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_job_results AS result
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = result.execution_id
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE result.result_id = OLD.result_id
) THEN openzyme_mutation_write_allowed((
    SELECT execution.session_id FROM workspace_job_results AS result
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = result.execution_id
    WHERE result.result_id = OLD.result_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_result_revision_links'); END;

CREATE TRIGGER mutation_guard_workspace_job_result_revision_links_insert
BEFORE INSERT ON workspace_job_result_revision_links
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_job_results AS result
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = result.execution_id
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE result.result_id = NEW.result_id
) THEN openzyme_mutation_write_allowed((
    SELECT execution.session_id
    FROM workspace_job_results AS result
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = result.execution_id
    WHERE result.result_id = NEW.result_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_result_revision_links'); END;

CREATE TRIGGER mutation_guard_workspace_job_result_revision_links_update
BEFORE UPDATE ON workspace_job_result_revision_links
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_job_results AS result
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = result.execution_id
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE result.result_id = OLD.result_id
) THEN openzyme_mutation_write_allowed((
    SELECT execution.session_id FROM workspace_job_results AS result
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = result.execution_id
    WHERE result.result_id = OLD.result_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_result_revision_links'); END;

CREATE TRIGGER mutation_guard_workspace_job_results_delete
BEFORE DELETE ON workspace_job_results
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_results'); END;

CREATE TRIGGER mutation_guard_workspace_job_results_insert
BEFORE INSERT ON workspace_job_results
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = NEW.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = NEW.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_results'); END;

CREATE TRIGGER mutation_guard_workspace_job_results_update
BEFORE UPDATE ON workspace_job_results
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_job_results'); END;

CREATE TRIGGER mutation_guard_workspace_revision_clean_observations_delete
BEFORE DELETE ON workspace_revision_clean_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = OLD.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = OLD.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_revision_clean_observations'); END;

CREATE TRIGGER mutation_guard_workspace_revision_clean_observations_insert
BEFORE INSERT ON workspace_revision_clean_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = NEW.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = NEW.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_revision_clean_observations'); END;

CREATE TRIGGER mutation_guard_workspace_revision_clean_observations_update
BEFORE UPDATE ON workspace_revision_clean_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_revision_execution_requests AS request
    JOIN mutation_scope_records AS scope ON scope.session_id = request.session_id
    WHERE request.request_id = OLD.request_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_revision_execution_requests
    WHERE request_id = OLD.request_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_revision_clean_observations'); END;

CREATE TRIGGER mutation_guard_workspace_revision_execution_requests_delete
BEFORE DELETE ON workspace_revision_execution_requests
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_revision_execution_requests'); END;

CREATE TRIGGER mutation_guard_workspace_revision_execution_requests_insert
BEFORE INSERT ON workspace_revision_execution_requests
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_revision_execution_requests'); END;

CREATE TRIGGER mutation_guard_workspace_revision_execution_requests_update
BEFORE UPDATE ON workspace_revision_execution_requests
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: workspace_revision_execution_requests'); END;

CREATE TRIGGER workspace_external_job_handle_matches
BEFORE INSERT ON workspace_external_job_handles
WHEN NOT EXISTS (
    SELECT 1 FROM workspace_job_dispatch_intents AS intent
    JOIN workspace_revision_execution_requests AS request
      ON request.request_id = intent.request_id
    WHERE intent.dispatch_id = NEW.dispatch_id
      AND intent.execution_id = NEW.execution_id
      AND intent.operation_id = NEW.operation_id
      AND intent.runner_run_id = NEW.runner_run_id
      AND intent.target_profile_digest = NEW.target_profile_digest
      AND intent.workspace_id = NEW.workspace_id
      AND intent.remote_workspace_generation = NEW.remote_workspace_generation
      AND intent.source_manifest_digest = NEW.source_manifest_digest
      AND request.source_commit = NEW.source_commit
      AND (
          (intent.selected_mode = 'ssh' AND NEW.backend = 'direct')
          OR (intent.selected_mode = 'sbatch' AND NEW.backend = 'slurm')
      )
)
BEGIN
    SELECT RAISE(ABORT, 'external job handle identity mismatch');
END;

CREATE TRIGGER workspace_external_job_handles_immutable_delete
BEFORE DELETE ON workspace_external_job_handles
BEGIN SELECT RAISE(ABORT, 'external job handle is immutable'); END;

CREATE TRIGGER workspace_external_job_handles_immutable_update
BEFORE UPDATE ON workspace_external_job_handles
BEGIN SELECT RAISE(ABORT, 'external job handle is immutable'); END;

CREATE TRIGGER workspace_external_job_observation_matches
BEFORE INSERT ON workspace_external_job_observations
WHEN NOT EXISTS (
    SELECT 1 FROM workspace_external_job_handles AS handle
    WHERE handle.handle_id = NEW.handle_id
      AND handle.execution_id = NEW.execution_id
      AND handle.dispatch_id = NEW.dispatch_id
      AND NOT EXISTS (
          SELECT 1 FROM workspace_external_job_observations AS prior
          WHERE prior.handle_id = NEW.handle_id
            AND (
                prior.observation_index >= NEW.observation_index
                OR prior.state IN ('succeeded', 'failed', 'cancelled')
            )
      )
      AND NEW.observation_index = COALESCE((
          SELECT MAX(prior.observation_index) + 1
          FROM workspace_external_job_observations AS prior
          WHERE prior.handle_id = NEW.handle_id
      ), 1)
)
BEGIN
    SELECT RAISE(ABORT, 'external job observation chain mismatch');
END;

CREATE TRIGGER workspace_external_job_observations_immutable_delete
BEFORE DELETE ON workspace_external_job_observations
BEGIN SELECT RAISE(ABORT, 'external job observation is immutable'); END;

CREATE TRIGGER workspace_external_job_observations_immutable_update
BEFORE UPDATE ON workspace_external_job_observations
BEGIN SELECT RAISE(ABORT, 'external job observation is immutable'); END;

CREATE TRIGGER workspace_job_cancellation_intent_matches
BEFORE INSERT ON workspace_job_cancellation_intents
WHEN NOT EXISTS (
    SELECT 1 FROM workspace_external_job_handles AS handle
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = handle.execution_id
    WHERE handle.handle_id = NEW.handle_id
      AND handle.execution_id = NEW.execution_id
      AND execution.state_version = NEW.execution_state_version
      AND execution.fencing_token = NEW.execution_fencing_token
      AND execution.lifecycle_state IN ('waiting_external', 'reconcile_required')
)
BEGIN
    SELECT RAISE(ABORT, 'workspace job cancellation authority mismatch');
END;

CREATE TRIGGER workspace_job_cancellation_intents_immutable_delete
BEFORE DELETE ON workspace_job_cancellation_intents
BEGIN SELECT RAISE(ABORT, 'workspace cancellation intent is immutable'); END;

CREATE TRIGGER workspace_job_cancellation_intents_immutable_update
BEFORE UPDATE ON workspace_job_cancellation_intents
BEGIN SELECT RAISE(ABORT, 'workspace cancellation intent is immutable'); END;

CREATE TRIGGER workspace_job_cancellation_receipt_matches
BEFORE INSERT ON workspace_job_cancellation_receipts
WHEN NOT EXISTS (
    SELECT 1 FROM workspace_job_cancellation_intents AS intent
    WHERE intent.cancellation_id = NEW.cancellation_id
      AND intent.handle_id = NEW.handle_id
)
BEGIN
    SELECT RAISE(ABORT, 'workspace job cancellation receipt mismatch');
END;

CREATE TRIGGER workspace_job_cancellation_receipts_immutable_delete
BEFORE DELETE ON workspace_job_cancellation_receipts
BEGIN SELECT RAISE(ABORT, 'workspace cancellation receipt is immutable'); END;

CREATE TRIGGER workspace_job_cancellation_receipts_immutable_update
BEFORE UPDATE ON workspace_job_cancellation_receipts
BEGIN SELECT RAISE(ABORT, 'workspace cancellation receipt is immutable'); END;

CREATE TRIGGER workspace_job_dispatch_intents_immutable_delete
BEFORE DELETE ON workspace_job_dispatch_intents
BEGIN SELECT RAISE(ABORT, 'workspace job dispatch intent is immutable'); END;

CREATE TRIGGER workspace_job_dispatch_intents_immutable_update
BEFORE UPDATE ON workspace_job_dispatch_intents
BEGIN SELECT RAISE(ABORT, 'workspace job dispatch intent is immutable'); END;

CREATE TRIGGER workspace_job_result_matches
BEFORE INSERT ON workspace_job_results
WHEN NOT EXISTS (
    SELECT 1
    FROM workspace_external_job_handles AS handle
    JOIN workspace_external_job_observations AS observation
      ON observation.handle_id = handle.handle_id
    JOIN workspace_job_dispatch_intents AS intent
      ON intent.dispatch_id = handle.dispatch_id
    JOIN workspace_revision_execution_requests AS request
      ON request.request_id = intent.request_id
    WHERE handle.handle_id = NEW.handle_id
      AND handle.execution_id = NEW.execution_id
      AND handle.operation_id = NEW.operation_id
      AND handle.runner_run_id = NEW.runner_run_id
      AND handle.source_commit = NEW.source_commit
      AND handle.source_manifest_digest = NEW.source_manifest_digest
      AND handle.workspace_id = NEW.workspace_id
      AND handle.remote_workspace_generation = NEW.remote_workspace_generation
      AND handle.job_root_token = NEW.job_root_token
      AND observation.observation_id = NEW.terminal_observation_id
      AND observation.observation_digest = NEW.terminal_observation_digest
      AND observation.state = NEW.terminal_state
      AND observation.exit_code IS NEW.exit_code
      AND request.cwd = NEW.cwd
      AND intent.command_digest = NEW.command_digest
      AND intent.resource_digest = NEW.resource_digest
      AND intent.target_profile_digest = NEW.target_profile_digest
)
BEGIN
    SELECT RAISE(ABORT, 'workspace job result identity mismatch');
END;

CREATE TRIGGER workspace_job_result_revision_link_matches
BEFORE INSERT ON workspace_job_result_revision_links
WHEN NOT EXISTS (
    SELECT 1
    FROM workspace_job_results AS result
    JOIN workspace_revision_execution_requests AS request
      ON request.execution_id = result.execution_id
    JOIN verified_workspace_checkpoint_records AS checkpoint
      ON checkpoint.checkpoint_id = NEW.checkpoint_id
    JOIN agent_git_workspace_records AS workspace
      ON workspace.workspace_id = checkpoint.workspace_id
    JOIN git_lfs_closure_manifests AS closure
      ON closure.manifest_digest = NEW.lfs_closure_manifest_digest
    WHERE result.result_id = NEW.result_id
      AND checkpoint.boundary = 'external_job'
      AND checkpoint.workspace_id = NEW.workspace_id
      AND checkpoint.agent_member_id = NEW.linked_by_agent_member_id
      AND checkpoint.session_id = request.session_id
      AND checkpoint.agent_member_id = request.executor_agent_member_id
      AND checkpoint.repository_binding_id = request.repository_binding_id
      AND checkpoint.repository_binding_version = request.repository_binding_version
      AND checkpoint.commit_oid = NEW.result_commit
      AND checkpoint.tree_oid = NEW.result_tree
      AND workspace.agent_member_id = request.executor_agent_member_id
      AND closure.binding_id = request.repository_binding_id
      AND closure.binding_version = request.repository_binding_version
      AND closure.commit_id = NEW.result_commit
      AND closure.tree_id = NEW.result_tree
)
BEGIN
    SELECT RAISE(ABORT, 'workspace job result revision owner mismatch');
END;

CREATE TRIGGER workspace_job_result_revision_links_immutable_delete
BEFORE DELETE ON workspace_job_result_revision_links
BEGIN SELECT RAISE(ABORT, 'workspace result revision link is immutable'); END;

CREATE TRIGGER workspace_job_result_revision_links_immutable_update
BEFORE UPDATE ON workspace_job_result_revision_links
BEGIN SELECT RAISE(ABORT, 'workspace result revision link is immutable'); END;

CREATE TRIGGER workspace_job_results_immutable_delete
BEFORE DELETE ON workspace_job_results
BEGIN SELECT RAISE(ABORT, 'workspace job result is immutable'); END;

CREATE TRIGGER workspace_job_results_immutable_update
BEFORE UPDATE ON workspace_job_results
BEGIN SELECT RAISE(ABORT, 'workspace job result is immutable'); END;

CREATE TRIGGER workspace_revision_clean_observations_immutable_delete
BEFORE DELETE ON workspace_revision_clean_observations
BEGIN SELECT RAISE(ABORT, 'workspace clean observation is immutable'); END;

CREATE TRIGGER workspace_revision_clean_observations_immutable_update
BEFORE UPDATE ON workspace_revision_clean_observations
BEGIN SELECT RAISE(ABORT, 'workspace clean observation is immutable'); END;

CREATE TRIGGER workspace_revision_execution_requests_immutable_delete
BEFORE DELETE ON workspace_revision_execution_requests
BEGIN SELECT RAISE(ABORT, 'workspace revision execution request is immutable'); END;

CREATE TRIGGER workspace_revision_execution_requests_immutable_update
BEFORE UPDATE ON workspace_revision_execution_requests
BEGIN SELECT RAISE(ABORT, 'workspace revision execution request is immutable'); END;

CREATE TRIGGER workspace_revision_execution_scientific_basis_matches
BEFORE INSERT ON workspace_revision_execution_requests
WHEN NEW.scientific_attempt_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM scientific_attempt_records AS attempt
    JOIN scientific_attempt_admission_request_records AS request
      ON request.admission_request_id = attempt.admission_request_id
    WHERE attempt.attempt_id = NEW.scientific_attempt_id
      AND attempt.state_version = NEW.scientific_attempt_state_version
      AND attempt.status = 'active'
      AND attempt.session_id = NEW.session_id
      AND attempt.admission_request_id = NEW.scientific_admission_request_id
      AND attempt.envelope_id = NEW.scientific_source_envelope_id
      AND attempt.workflow_contract_digest
          = NEW.scientific_workflow_contract_digest
      AND request.request_digest = NEW.scientific_admission_request_digest
      AND request.envelope_id = NEW.scientific_source_envelope_id
      AND request.workflow_contract_digest
          = NEW.scientific_workflow_contract_digest
)
BEGIN
    SELECT RAISE(ABORT, 'workspace revision scientific basis mismatch');
END;
