-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.hpc
-- phase: triggers

CREATE TRIGGER executor_hpc_cleanup_intent_scope_matches
BEFORE INSERT ON executor_hpc_workspace_cleanup_intents
WHEN NOT EXISTS (
    SELECT 1
    FROM executor_hpc_workspace_records AS workspace
    WHERE workspace.workspace_id = NEW.workspace_id
      AND workspace.state IN ('cleaning', 'cleanup_reconciliation_required')
      AND workspace.state_version = NEW.workspace_state_version
      AND workspace.runner_handle = NEW.runner_handle
      AND workspace.remote_root_digest = NEW.remote_root_digest
)
BEGIN
    SELECT RAISE(ABORT, 'executor HPC cleanup intent scope mismatch');
END;

CREATE TRIGGER executor_hpc_cleanup_intents_immutable_delete
BEFORE DELETE ON executor_hpc_workspace_cleanup_intents
BEGIN SELECT RAISE(ABORT, 'executor HPC cleanup intent is immutable'); END;

CREATE TRIGGER executor_hpc_cleanup_intents_immutable_update
BEFORE UPDATE ON executor_hpc_workspace_cleanup_intents
BEGIN SELECT RAISE(ABORT, 'executor HPC cleanup intent is immutable'); END;

CREATE TRIGGER executor_hpc_cleanup_receipt_matches
BEFORE INSERT ON executor_hpc_workspace_cleanup_receipts
WHEN NOT EXISTS (
    SELECT 1
    FROM executor_hpc_workspace_cleanup_intents AS intent
    WHERE intent.cleanup_intent_id = NEW.cleanup_intent_id
      AND intent.intent_digest = NEW.cleanup_intent_digest
      AND intent.workspace_id = NEW.workspace_id
      AND intent.runner_handle = NEW.runner_handle
      AND intent.remote_root_digest = NEW.remote_root_digest
      AND intent.settlement_proof_digest = NEW.settlement_proof_digest
)
BEGIN
    SELECT RAISE(ABORT, 'executor HPC cleanup receipt identity mismatch');
END;

CREATE TRIGGER executor_hpc_cleanup_receipts_immutable_delete
BEFORE DELETE ON executor_hpc_workspace_cleanup_receipts
BEGIN SELECT RAISE(ABORT, 'executor HPC cleanup receipt is immutable'); END;

CREATE TRIGGER executor_hpc_cleanup_receipts_immutable_update
BEFORE UPDATE ON executor_hpc_workspace_cleanup_receipts
BEGIN SELECT RAISE(ABORT, 'executor HPC cleanup receipt is immutable'); END;

CREATE TRIGGER executor_hpc_credential_claim_immutable
BEFORE UPDATE ON executor_hpc_credential_claims
WHEN NEW.claim_id <> OLD.claim_id
  OR NEW.workspace_id <> OLD.workspace_id
  OR NEW.session_id <> OLD.session_id
  OR NEW.executor_agent_member_id <> OLD.executor_agent_member_id
  OR NEW.local_workspace_generation <> OLD.local_workspace_generation
  OR NEW.remote_workspace_generation <> OLD.remote_workspace_generation
  OR NEW.target_profile_id <> OLD.target_profile_id
  OR NEW.target_profile_digest <> OLD.target_profile_digest
  OR NEW.capability_lease_id <> OLD.capability_lease_id
  OR NEW.capability_lease_version <> OLD.capability_lease_version
  OR NEW.credential_provider_id <> OLD.credential_provider_id
  OR NEW.authenticator_id <> OLD.authenticator_id
  OR NEW.login_alias <> OLD.login_alias
  OR NEW.remote_workspace_path <> OLD.remote_workspace_path
  OR NEW.remote_root_digest <> OLD.remote_root_digest
  OR NEW.os_principal_identity_digest <> OLD.os_principal_identity_digest
  OR NEW.operations_json <> OLD.operations_json
  OR NEW.credential_fingerprint <> OLD.credential_fingerprint
  OR NEW.authentication_receipt_digest <> OLD.authentication_receipt_digest
  OR NEW.issued_at <> OLD.issued_at
  OR NEW.expires_at <> OLD.expires_at
  OR OLD.revoked_at IS NOT NULL
  OR NEW.revoked_at IS NULL
BEGIN
    SELECT RAISE(ABORT, 'executor HPC credential claim is immutable except revoke-once');
END;

CREATE TRIGGER executor_hpc_credential_claim_no_delete
BEFORE DELETE ON executor_hpc_credential_claims
BEGIN SELECT RAISE(ABORT, 'executor HPC credential claim is immutable history'); END;

CREATE TRIGGER executor_hpc_credential_claim_scope_matches
BEFORE INSERT ON executor_hpc_credential_claims
WHEN NOT EXISTS (
    SELECT 1
    FROM executor_hpc_workspace_records AS workspace
    JOIN agent_capability_lease_records AS lease
      ON lease.lease_id = workspace.capability_lease_id
    WHERE workspace.workspace_id = NEW.workspace_id
      AND workspace.state = 'ready'
      AND workspace.session_id = NEW.session_id
      AND workspace.executor_agent_member_id = NEW.executor_agent_member_id
      AND workspace.local_workspace_generation = NEW.local_workspace_generation
      AND workspace.remote_workspace_generation = NEW.remote_workspace_generation
      AND workspace.target_profile_id = NEW.target_profile_id
      AND workspace.target_profile_digest = NEW.target_profile_digest
      AND workspace.capability_lease_id = NEW.capability_lease_id
      AND workspace.capability_lease_version = NEW.capability_lease_version
      AND EXISTS (
          SELECT 1 FROM executor_hpc_target_qualifications AS target
          WHERE target.target_profile_id = NEW.target_profile_id
            AND target.credential_provider_id = NEW.credential_provider_id
            AND target.authenticator_id = NEW.authenticator_id
            AND target.activated = 1
      )
      AND workspace.login_alias = NEW.login_alias
      AND workspace.remote_workspace_path = NEW.remote_workspace_path
      AND workspace.remote_root_digest = NEW.remote_root_digest
      AND workspace.os_principal_identity_digest
          = NEW.os_principal_identity_digest
      AND lease.status = 'active'
      AND lease.state_version = NEW.capability_lease_version
      AND json_array_length(NEW.operations_json) BETWEEN 1 AND 6
      AND NOT EXISTS (
          SELECT 1 FROM json_each(NEW.operations_json)
          WHERE value NOT IN (
              'ssh_login', 'rsync', 'scp', 'git', 'git_lfs', 'workspace_crud'
          )
      )
)
BEGIN
    SELECT RAISE(ABORT, 'executor HPC credential claim scope mismatch');
END;

CREATE TRIGGER executor_hpc_provision_intent_scope_matches
BEFORE INSERT ON executor_hpc_workspace_provision_intents
WHEN NOT EXISTS (
    SELECT 1
    FROM sessions AS session
    JOIN agent_members AS member
      ON member.session_id = session.session_id
     AND member.member_id = NEW.executor_agent_member_id
    JOIN agent_git_workspace_records AS local_workspace
      ON local_workspace.workspace_id = NEW.local_workspace_id
    JOIN agent_capability_lease_records AS lease
      ON lease.lease_id = NEW.capability_lease_id
    JOIN project_repository_binding_versions AS binding
      ON binding.binding_id = NEW.repository_binding_id
    JOIN executor_hpc_target_qualifications AS target
      ON target.target_profile_id = NEW.target_profile_id
    WHERE session.session_id = NEW.session_id
      AND session.project_id = NEW.project_id
      AND local_workspace.session_id = NEW.session_id
      AND local_workspace.agent_member_id = NEW.executor_agent_member_id
      AND local_workspace.workspace_generation = NEW.local_workspace_generation
      AND local_workspace.repository_binding_id = NEW.repository_binding_id
      AND local_workspace.repository_binding_version = NEW.repository_binding_version
      AND local_workspace.repository_id = NEW.repository_id
      AND local_workspace.base_commit = NEW.base_commit
      AND lease.session_id = NEW.session_id
      AND lease.agent_member_id = NEW.executor_agent_member_id
      AND lease.workspace_generation = NEW.local_workspace_generation
      AND lease.profile = 'executor'
      AND lease.status = 'active'
      AND lease.state_version = NEW.capability_lease_version
      AND binding.binding_version = NEW.repository_binding_version
      AND binding.repository_id = NEW.repository_id
      AND target.target_profile_digest = NEW.target_profile_digest
      AND target.root_policy_digest = NEW.root_policy_digest
      AND target.activated = 1
      AND target.scheduler_submit_enabled = 0
)
BEGIN
    SELECT RAISE(ABORT, 'executor HPC provision intent scope mismatch');
END;

CREATE TRIGGER executor_hpc_provision_intents_immutable_delete
BEFORE DELETE ON executor_hpc_workspace_provision_intents
BEGIN SELECT RAISE(ABORT, 'executor HPC provision intent is immutable'); END;

CREATE TRIGGER executor_hpc_provision_intents_immutable_update
BEFORE UPDATE ON executor_hpc_workspace_provision_intents
BEGIN SELECT RAISE(ABORT, 'executor HPC provision intent is immutable'); END;

CREATE TRIGGER executor_hpc_provision_receipt_matches
BEFORE INSERT ON executor_hpc_workspace_provision_receipts
WHEN NOT EXISTS (
    SELECT 1
    FROM executor_hpc_workspace_provision_intents AS intent
    JOIN executor_hpc_workspace_records AS workspace
      ON workspace.workspace_id = intent.workspace_id
    JOIN project_repository_binding_versions AS binding
      ON binding.binding_id = intent.repository_binding_id
    JOIN executor_hpc_target_qualifications AS target
      ON target.target_profile_id = intent.target_profile_id
    WHERE intent.intent_id = NEW.intent_id
      AND intent.intent_digest = NEW.intent_digest
      AND intent.workspace_id = NEW.workspace_id
      AND intent.target_profile_digest = NEW.target_profile_digest
      AND intent.base_commit = NEW.clone_head_commit
      AND binding.binding_version = intent.repository_binding_version
      AND binding.repository_id = intent.repository_id
      AND binding.canonical_digest = NEW.repository_remote_digest
      AND target.login_alias = NEW.login_alias
      AND workspace.workspace_id = NEW.workspace_id
      AND workspace.provision_intent_id = NEW.intent_id
)
BEGIN
    SELECT RAISE(ABORT, 'executor HPC provision receipt identity mismatch');
END;

CREATE TRIGGER executor_hpc_provision_receipts_immutable_delete
BEFORE DELETE ON executor_hpc_workspace_provision_receipts
BEGIN SELECT RAISE(ABORT, 'executor HPC provision receipt is immutable'); END;

CREATE TRIGGER executor_hpc_provision_receipts_immutable_update
BEFORE UPDATE ON executor_hpc_workspace_provision_receipts
BEGIN SELECT RAISE(ABORT, 'executor HPC provision receipt is immutable'); END;

CREATE TRIGGER executor_hpc_target_qualifications_immutable_delete
BEFORE DELETE ON executor_hpc_target_qualifications
BEGIN SELECT RAISE(ABORT, 'executor HPC target qualification is immutable'); END;

CREATE TRIGGER executor_hpc_target_qualifications_immutable_update
BEFORE UPDATE ON executor_hpc_target_qualifications
BEGIN SELECT RAISE(ABORT, 'executor HPC target qualification is immutable'); END;

CREATE TRIGGER executor_hpc_workspace_identity_immutable
BEFORE UPDATE ON executor_hpc_workspace_records
WHEN NEW.workspace_id <> OLD.workspace_id
  OR NEW.project_id <> OLD.project_id
  OR NEW.repository_binding_id <> OLD.repository_binding_id
  OR NEW.repository_binding_version <> OLD.repository_binding_version
  OR NEW.repository_id <> OLD.repository_id
  OR NEW.session_id <> OLD.session_id
  OR NEW.executor_agent_member_id <> OLD.executor_agent_member_id
  OR NEW.executor_agent_id <> OLD.executor_agent_id
  OR NEW.local_workspace_id <> OLD.local_workspace_id
  OR NEW.local_workspace_generation <> OLD.local_workspace_generation
  OR NEW.capability_lease_id <> OLD.capability_lease_id
  OR NEW.capability_lease_version <> OLD.capability_lease_version
  OR NEW.target_profile_id <> OLD.target_profile_id
  OR NEW.target_profile_digest <> OLD.target_profile_digest
  OR NEW.remote_workspace_generation <> OLD.remote_workspace_generation
  OR NEW.provision_intent_id <> OLD.provision_intent_id
  OR (OLD.runner_handle IS NOT NULL
      AND NEW.runner_handle IS NOT OLD.runner_handle)
  OR (OLD.provision_receipt_id IS NOT NULL
      AND NEW.provision_receipt_id IS NOT OLD.provision_receipt_id)
  OR (OLD.login_alias IS NOT NULL
      AND NEW.login_alias IS NOT OLD.login_alias)
  OR (OLD.remote_workspace_path IS NOT NULL
      AND NEW.remote_workspace_path IS NOT OLD.remote_workspace_path)
  OR (OLD.remote_root_digest IS NOT NULL
      AND NEW.remote_root_digest IS NOT OLD.remote_root_digest)
  OR (OLD.os_principal_identity_digest IS NOT NULL
      AND NEW.os_principal_identity_digest
          IS NOT OLD.os_principal_identity_digest)
  OR (OLD.isolation_receipt_digest IS NOT NULL
      AND NEW.isolation_receipt_digest IS NOT OLD.isolation_receipt_digest)
  OR NEW.created_at <> OLD.created_at
BEGIN
    SELECT RAISE(ABORT, 'executor HPC workspace identity is immutable');
END;

CREATE TRIGGER executor_hpc_workspace_no_delete
BEFORE DELETE ON executor_hpc_workspace_records
BEGIN SELECT RAISE(ABORT, 'executor HPC workspace record is immutable history'); END;

CREATE TRIGGER executor_hpc_workspace_scope_matches
BEFORE INSERT ON executor_hpc_workspace_records
WHEN NOT EXISTS (
    SELECT 1
    FROM executor_hpc_workspace_provision_intents AS intent
    JOIN agent_members AS member
      ON member.member_id = NEW.executor_agent_member_id
    WHERE intent.intent_id = NEW.provision_intent_id
      AND intent.workspace_id = NEW.workspace_id
      AND intent.project_id = NEW.project_id
      AND intent.session_id = NEW.session_id
      AND intent.executor_agent_member_id = NEW.executor_agent_member_id
      AND intent.local_workspace_id = NEW.local_workspace_id
      AND intent.local_workspace_generation = NEW.local_workspace_generation
      AND intent.capability_lease_id = NEW.capability_lease_id
      AND intent.capability_lease_version = NEW.capability_lease_version
      AND intent.target_profile_id = NEW.target_profile_id
      AND intent.target_profile_digest = NEW.target_profile_digest
      AND intent.remote_workspace_generation = NEW.remote_workspace_generation
      AND intent.repository_binding_id = NEW.repository_binding_id
      AND intent.repository_binding_version = NEW.repository_binding_version
      AND intent.repository_id = NEW.repository_id
      AND member.session_id = NEW.session_id
      AND member.agent_id = NEW.executor_agent_id
)
BEGIN
    SELECT RAISE(ABORT, 'executor HPC workspace scope mismatch');
END;

CREATE TRIGGER executor_hpc_workspace_transition_guard
BEFORE UPDATE ON executor_hpc_workspace_records
WHEN NEW.state_version <> OLD.state_version + 1
  OR NOT (
      (OLD.state = 'provisioning' AND NEW.state IN (
          'ready', 'invalid', 'missing', 'provision_reconciliation_required',
          'retention_eligible'
      ))
      OR (OLD.state = 'provision_reconciliation_required' AND NEW.state IN (
          'ready', 'invalid', 'missing'
      ))
      OR (OLD.state = 'ready' AND NEW.state IN (
          'invalid', 'missing', 'retention_eligible'
      ))
      OR (OLD.state IN ('invalid', 'missing') AND NEW.state = 'retention_eligible')
      OR (OLD.state = 'retention_eligible' AND NEW.state = 'cleaning')
      OR (OLD.state = 'cleaning' AND NEW.state IN (
          'cleaned', 'cleanup_reconciliation_required'
      ))
      OR (OLD.state = 'cleanup_reconciliation_required'
          AND NEW.state = 'cleaned')
  )
BEGIN
    SELECT RAISE(ABORT, 'executor HPC workspace transition is invalid');
END;

CREATE TRIGGER mutation_guard_executor_hpc_credential_claims_delete
BEFORE DELETE ON executor_hpc_credential_claims
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_credential_claims_insert
BEFORE INSERT ON executor_hpc_credential_claims
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_credential_claims_update
BEFORE UPDATE ON executor_hpc_credential_claims
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_cleanup_intents_delete
BEFORE DELETE ON executor_hpc_workspace_cleanup_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = OLD.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = OLD.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_cleanup_intents_insert
BEFORE INSERT ON executor_hpc_workspace_cleanup_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = NEW.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = NEW.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_cleanup_intents_update
BEFORE UPDATE ON executor_hpc_workspace_cleanup_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = OLD.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = OLD.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_cleanup_receipts_delete
BEFORE DELETE ON executor_hpc_workspace_cleanup_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = OLD.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = OLD.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_cleanup_receipts_insert
BEFORE INSERT ON executor_hpc_workspace_cleanup_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = NEW.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = NEW.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_cleanup_receipts_update
BEFORE UPDATE ON executor_hpc_workspace_cleanup_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = OLD.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = OLD.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_provision_intents_delete
BEFORE DELETE ON executor_hpc_workspace_provision_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_provision_intents_insert
BEFORE INSERT ON executor_hpc_workspace_provision_intents
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_provision_intents_update
BEFORE UPDATE ON executor_hpc_workspace_provision_intents
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_provision_receipts_delete
BEFORE DELETE ON executor_hpc_workspace_provision_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = OLD.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = OLD.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_provision_receipts_insert
BEFORE INSERT ON executor_hpc_workspace_provision_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = NEW.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = NEW.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_provision_receipts_update
BEFORE UPDATE ON executor_hpc_workspace_provision_receipts
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM executor_hpc_workspace_records AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.workspace_id = OLD.workspace_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM executor_hpc_workspace_records
    WHERE workspace_id = OLD.workspace_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_records_delete
BEFORE DELETE ON executor_hpc_workspace_records
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_records_insert
BEFORE INSERT ON executor_hpc_workspace_records
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_executor_hpc_workspace_records_update
BEFORE UPDATE ON executor_hpc_workspace_records
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_scheduler_credential_occurrences_delete
BEFORE DELETE ON scheduler_credential_occurrences
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: scheduler_credential_occurrences'); END;

CREATE TRIGGER mutation_guard_scheduler_credential_occurrences_insert
BEFORE INSERT ON scheduler_credential_occurrences
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = NEW.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = NEW.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: scheduler_credential_occurrences'); END;

CREATE TRIGGER mutation_guard_scheduler_credential_occurrences_update
BEFORE UPDATE ON scheduler_credential_occurrences
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM controlled_operation_execution_records AS execution
    JOIN mutation_scope_records AS scope ON scope.session_id = execution.session_id
    WHERE execution.execution_id = OLD.execution_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM controlled_operation_execution_records
    WHERE execution_id = OLD.execution_id
), 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation authority denied: scheduler_credential_occurrences'); END;

CREATE TRIGGER scheduler_credential_occurrence_matches
BEFORE INSERT ON scheduler_credential_occurrences
WHEN NOT EXISTS (
    SELECT 1 FROM workspace_job_dispatch_intents AS intent
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = intent.execution_id
    WHERE intent.dispatch_id = NEW.dispatch_id
      AND intent.execution_id = NEW.execution_id
      AND intent.execution_fencing_token = NEW.execution_fencing_token
      AND intent.selected_mode = 'sbatch'
      AND intent.target_profile_digest = NEW.target_profile_digest
      AND intent.scheduler_marker = NEW.scheduler_marker
      AND intent.payload_digest = NEW.payload_digest
      AND execution.fencing_token = NEW.execution_fencing_token
)
BEGIN
    SELECT RAISE(ABORT, 'scheduler credential occurrence mismatch');
END;

CREATE TRIGGER scheduler_credential_occurrence_transition_guard
BEFORE UPDATE ON scheduler_credential_occurrences
WHEN NEW.occurrence_id <> OLD.occurrence_id
  OR NEW.dispatch_id <> OLD.dispatch_id
  OR NEW.execution_id <> OLD.execution_id
  OR NEW.execution_fencing_token <> OLD.execution_fencing_token
  OR NEW.target_profile_digest <> OLD.target_profile_digest
  OR NEW.reservation_nonce_digest <> OLD.reservation_nonce_digest
  OR NEW.scheduler_marker <> OLD.scheduler_marker
  OR NEW.payload_digest <> OLD.payload_digest
  OR NEW.protected_wrapper_audience <> OLD.protected_wrapper_audience
  OR NEW.reserved_at <> OLD.reserved_at
  OR NEW.expires_at <> OLD.expires_at
  OR NOT (
      (OLD.state = 'reserved' AND NEW.state IN ('issued', 'rejected', 'expired'))
      OR (OLD.state = 'issued' AND NEW.state IN ('consumed', 'rejected', 'expired'))
  )
BEGIN
    SELECT RAISE(ABORT, 'scheduler credential occurrence transition invalid');
END;

CREATE TRIGGER scheduler_credential_occurrences_no_delete
BEFORE DELETE ON scheduler_credential_occurrences
BEGIN SELECT RAISE(ABORT, 'scheduler credential occurrence is durable'); END;

CREATE TRIGGER workspace_job_target_qualification_matches
BEFORE INSERT ON workspace_job_target_qualifications
WHEN NOT EXISTS (
    SELECT 1 FROM executor_hpc_target_qualifications AS target
    WHERE target.target_profile_id = NEW.target_profile_id
      AND target.target_profile_digest = NEW.target_profile_digest
      AND target.activated = 1
      AND target.scheduler_submit_enabled = 0
)
BEGIN
    SELECT RAISE(ABORT, 'workspace job target qualification mismatch');
END;

CREATE TRIGGER workspace_job_target_qualifications_immutable_delete
BEFORE DELETE ON workspace_job_target_qualifications
BEGIN SELECT RAISE(ABORT, 'workspace job target qualification is immutable'); END;

CREATE TRIGGER workspace_job_target_qualifications_immutable_update
BEFORE UPDATE ON workspace_job_target_qualifications
BEGIN SELECT RAISE(ABORT, 'workspace job target qualification is immutable'); END;
