-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.reporting
-- phase: triggers

CREATE TRIGGER mutation_guard_session_report_draft_records_delete
BEFORE DELETE ON session_report_draft_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'report_publication') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_session_report_draft_records_insert
BEFORE INSERT ON session_report_draft_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'report_publication') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_session_report_draft_records_update
BEFORE UPDATE ON session_report_draft_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'report_publication') <> 1 ELSE 0 END) OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'report_publication') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_session_report_records_delete
BEFORE DELETE ON session_report_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'report_publication') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_session_report_records_insert
BEFORE INSERT ON session_report_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'report_publication') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_session_report_records_update
BEFORE UPDATE ON session_report_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'report_publication') <> 1 ELSE 0 END) OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'report_publication') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER session_report_records_content_identity_immutable
BEFORE UPDATE OF content_ref_id, report_version, supersedes_report_id
ON session_report_records
WHEN NEW.content_ref_id IS NOT OLD.content_ref_id
  OR NEW.report_version IS NOT OLD.report_version
  OR NEW.supersedes_report_id IS NOT OLD.supersedes_report_id
BEGIN
    SELECT RAISE(ABORT, 'published report content identity is immutable');
END;

CREATE TRIGGER session_report_records_content_owner_matches
BEFORE INSERT ON session_report_records
WHEN NEW.content_ref_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM revision_path_refs AS ref
    WHERE ref.ref_id = NEW.content_ref_id
      AND ref.session_id = NEW.session_id
      AND ref.entry_kind IN ('file', 'lfs_file')
)
BEGIN
    SELECT RAISE(ABORT, 'report content reference owner mismatch');
END;

CREATE TRIGGER session_report_records_version_lineage_matches
BEFORE INSERT ON session_report_records
WHEN (
    NEW.supersedes_report_id IS NULL AND NEW.report_version <> 1
) OR (
    NEW.supersedes_report_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM session_report_records AS predecessor
        WHERE predecessor.report_id = NEW.supersedes_report_id
          AND predecessor.session_id = NEW.session_id
          AND predecessor.task_id IS NEW.task_id
          AND NEW.report_version = predecessor.report_version + 1
          AND predecessor.report_id <> NEW.report_id
    )
)
BEGIN
    SELECT RAISE(ABORT, 'report version lineage mismatch');
END;
