-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.science
-- phase: triggers

CREATE TRIGGER mutation_guard_scientific_attempt_admission_request_records_delete
BEFORE DELETE ON scientific_attempt_admission_request_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_admission_request_records_insert
BEFORE INSERT ON scientific_attempt_admission_request_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_admission_request_records_update
BEFORE UPDATE ON scientific_attempt_admission_request_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_authorization_records_delete
BEFORE DELETE ON scientific_attempt_authorization_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'ledger') <> 1
    ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_authorization_records_insert
BEFORE INSERT ON scientific_attempt_authorization_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'ledger') <> 1
    ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_authorization_records_update
BEFORE UPDATE ON scientific_attempt_authorization_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(OLD.session_id, 'ledger') <> 1
    ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(NEW.session_id, 'ledger') <> 1
    ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_closure_request_records_delete
BEFORE DELETE ON scientific_attempt_closure_request_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_closure_request_records_insert
BEFORE INSERT ON scientific_attempt_closure_request_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_closure_request_records_update
BEFORE UPDATE ON scientific_attempt_closure_request_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_closure_response_records_delete
BEFORE DELETE ON scientific_attempt_closure_response_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_closure_response_records_insert
BEFORE INSERT ON scientific_attempt_closure_response_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_closure_response_records_update
BEFORE UPDATE ON scientific_attempt_closure_response_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_operation_bindings_delete
BEFORE DELETE ON scientific_attempt_operation_bindings
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_operation_bindings_insert
BEFORE INSERT ON scientific_attempt_operation_bindings
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_operation_bindings_update
BEFORE UPDATE ON scientific_attempt_operation_bindings
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_records_delete
BEFORE DELETE ON scientific_attempt_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_records_insert
BEFORE INSERT ON scientific_attempt_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_records_update
BEFORE UPDATE ON scientific_attempt_records
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_run_bindings_delete
BEFORE DELETE ON scientific_attempt_run_bindings
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_run_bindings_insert
BEFORE INSERT ON scientific_attempt_run_bindings
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_attempt_run_bindings_update
BEFORE UPDATE ON scientific_attempt_run_bindings
WHEN (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
    ) THEN openzyme_mutation_write_allowed(
        OLD.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
    ) THEN openzyme_mutation_write_allowed(
        NEW.session_id, 'canonical_sqlite'
    ) <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_chain_selection_records_delete
BEFORE DELETE ON scientific_chain_selection_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_chain_selection_records_insert
BEFORE INSERT ON scientific_chain_selection_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_chain_selection_records_update
BEFORE UPDATE ON scientific_chain_selection_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_effect_adoption_records_delete
BEFORE DELETE ON scientific_effect_adoption_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_effect_adoption_records_insert
BEFORE INSERT ON scientific_effect_adoption_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_effect_adoption_records_update
BEFORE UPDATE ON scientific_effect_adoption_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_operation_disposition_records_delete
BEFORE DELETE ON scientific_operation_disposition_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_operation_disposition_records_insert
BEFORE INSERT ON scientific_operation_disposition_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_operation_disposition_records_update
BEFORE UPDATE ON scientific_operation_disposition_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_selection_head_records_delete
BEFORE DELETE ON scientific_selection_head_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_selection_head_records_insert
BEFORE INSERT ON scientific_selection_head_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_selection_head_records_update
BEFORE UPDATE ON scientific_selection_head_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_selection_occurrence_records_delete
BEFORE DELETE ON scientific_selection_occurrence_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_selection_occurrence_records_insert
BEFORE INSERT ON scientific_selection_occurrence_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_scientific_selection_occurrence_records_update
BEFORE UPDATE ON scientific_selection_occurrence_records
WHEN (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = OLD.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = OLD.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
        SELECT 1
        FROM scientific_attempt_records AS attempt
        JOIN mutation_scope_records AS scope
          ON scope.session_id = attempt.session_id
        WHERE attempt.attempt_id = NEW.attempt_id
    ) THEN openzyme_mutation_write_allowed((
        SELECT session_id FROM scientific_attempt_records
        WHERE attempt_id = NEW.attempt_id
    ), 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER scientific_attempt_admission_request_authority_matches
BEFORE INSERT ON scientific_attempt_admission_request_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_attempt_authorization_records AS authority
    JOIN tasks AS task ON task.task_id = NEW.task_id
    JOIN lanes AS lane ON lane.lane_id = NEW.lane_id
    WHERE authority.envelope_id = NEW.envelope_id
      AND authority.session_id = NEW.session_id
      AND authority.task_id = NEW.task_id
      AND authority.campaign_id = NEW.campaign_id
      AND authority.workflow_id = NEW.workflow_id
      AND authority.root_ref <> ''
      AND task.session_id = NEW.session_id
      AND task.lane_id = NEW.lane_id
      AND lane.session_id = NEW.session_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt admission identity mismatch');
END;

CREATE TRIGGER scientific_attempt_admission_requests_immutable_delete
BEFORE DELETE ON scientific_attempt_admission_request_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt admission requests are durable');
END;

CREATE TRIGGER scientific_attempt_admission_requests_immutable_update
BEFORE UPDATE ON scientific_attempt_admission_request_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt admission requests are immutable');
END;

CREATE TRIGGER scientific_attempt_authority_matches
BEFORE INSERT ON scientific_attempt_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_attempt_authorization_records AS authority
    JOIN scientific_attempt_admission_request_records AS request
      ON request.admission_request_id = NEW.admission_request_id
    WHERE authority.envelope_id = NEW.envelope_id
      AND authority.session_id = NEW.session_id
      AND authority.task_id = NEW.task_id
      AND authority.campaign_id = NEW.campaign_id
      AND authority.workflow_id = NEW.workflow_id
      AND authority.root_ref = NEW.root_ref
      AND request.envelope_id = NEW.envelope_id
      AND request.session_id = NEW.session_id
      AND request.task_id = NEW.task_id
      AND request.lane_id = NEW.lane_id
      AND request.campaign_id = NEW.campaign_id
      AND request.workflow_id = NEW.workflow_id
      AND request.scope = NEW.scope
      AND request.workflow_contract_digest = NEW.workflow_contract_digest
      AND request.requested_effect_classes_json = NEW.requested_effect_classes_json
      AND request.provider IS NEW.provider
      AND request.hpc_target IS NEW.hpc_target
      AND request.reserved_micu = NEW.reserved_micu
      AND request.reserved_cost_microunits = NEW.reserved_cost_microunits
      AND request.reserved_wall_time_seconds = NEW.reserved_wall_time_seconds
      AND request.actor_ref = NEW.created_by
      AND request.idempotency_key = NEW.idempotency_key
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt authority or admission identity mismatch');
END;

CREATE TRIGGER scientific_attempt_closure_matches
BEFORE INSERT ON scientific_attempt_closure_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_attempt_records AS attempt
    JOIN scientific_attempt_closure_request_records AS request
      ON request.closure_request_id = NEW.closure_request_id
     AND request.attempt_id = attempt.attempt_id
     AND request.selection_id = NEW.selection_id
     AND request.actor_ref = NEW.actor_ref
    JOIN scientific_chain_selection_records AS selection
      ON selection.selection_id = NEW.selection_id
     AND selection.attempt_id = attempt.attempt_id
     AND selection.state = 'sealed'
    JOIN quiescence_receipt_records AS receipt
      ON receipt.receipt_id = NEW.quiescence_receipt_id
     AND receipt.scope_id = attempt.mutation_scope_id
     AND receipt.receipt_digest = NEW.quiescence_receipt_digest
    WHERE attempt.attempt_id = NEW.attempt_id
      AND selection.operation_universe_digest =
          NEW.operation_universe_digest
      AND selection.disposition_digest = NEW.disposition_digest
      AND selection.adoption_digest = NEW.adoption_digest
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closure identity mismatch');
END;

CREATE TRIGGER scientific_attempt_closure_records_immutable_delete
BEFORE DELETE ON scientific_attempt_closure_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closures are immutable');
END;

CREATE TRIGGER scientific_attempt_closure_records_immutable_update
BEFORE UPDATE ON scientific_attempt_closure_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closures are immutable');
END;

CREATE TRIGGER scientific_attempt_closure_request_matches
BEFORE INSERT ON scientific_attempt_closure_request_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_attempt_records AS attempt
    JOIN scientific_chain_selection_records AS selection
      ON selection.selection_id = NEW.selection_id
     AND selection.attempt_id = attempt.attempt_id
     AND selection.state = 'sealed'
    WHERE attempt.attempt_id = NEW.attempt_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closure request identity mismatch');
END;

CREATE TRIGGER scientific_attempt_closure_request_records_immutable_delete
BEFORE DELETE ON scientific_attempt_closure_request_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closure requests are immutable');
END;

CREATE TRIGGER scientific_attempt_closure_request_records_immutable_update
BEFORE UPDATE ON scientific_attempt_closure_request_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closure requests are immutable');
END;

CREATE TRIGGER scientific_attempt_closure_response_matches
BEFORE INSERT ON scientific_attempt_closure_response_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_attempt_closure_request_records AS request
    JOIN scientific_attempt_records AS attempt
      ON attempt.attempt_id = request.attempt_id
    JOIN inbox_messages AS message
      ON message.message_id = NEW.message_id
     AND message.session_id = attempt.session_id
     AND message.sender = 'harness'
     AND message.sender_kind = 'harness'
     AND message.recipient = NEW.recipient
     AND message.recipient_kind = NEW.recipient_kind
     AND message.message_type = 'assistant_message'
     AND message.payload_ref = NEW.document_id
    JOIN engine_documents AS document
      ON document.document_id = NEW.document_id
     AND document.session_id = attempt.session_id
     AND document.document_kind = 'conversation_message'
    WHERE request.closure_request_id = NEW.closure_request_id
      AND request.attempt_id = NEW.attempt_id
)
BEGIN
    SELECT RAISE(
        ABORT,
        'scientific attempt closure response identity mismatch'
    );
END;

CREATE TRIGGER scientific_attempt_closure_response_records_immutable_delete
BEFORE DELETE ON scientific_attempt_closure_response_records
BEGIN
    SELECT RAISE(
        ABORT,
        'scientific attempt closure responses are immutable'
    );
END;

CREATE TRIGGER scientific_attempt_closure_response_records_immutable_update
BEFORE UPDATE ON scientific_attempt_closure_response_records
BEGIN
    SELECT RAISE(
        ABORT,
        'scientific attempt closure responses are immutable'
    );
END;

CREATE TRIGGER scientific_attempt_identity_immutable
BEFORE UPDATE OF
    attempt_id,
    admission_request_id,
    envelope_id,
    session_id,
    task_id,
    lane_id,
    campaign_id,
    workflow_id,
    scope,
    root_ref,
    mutation_scope_id,
    ordinal,
    request_digest,
    idempotency_key,
    workflow_contract_digest,
    requested_effect_classes_json,
    provider,
    hpc_target,
    reserved_micu,
    reserved_cost_microunits,
    reserved_wall_time_seconds,
    created_by,
    created_at
ON scientific_attempt_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt identity is immutable');
END;

CREATE TRIGGER scientific_attempt_no_delete
BEFORE DELETE ON scientific_attempt_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt is durable');
END;

CREATE TRIGGER scientific_attempt_operation_after_closure_request_forbidden
BEFORE INSERT ON scientific_attempt_operation_bindings
WHEN EXISTS (
    SELECT 1
    FROM scientific_attempt_closure_request_records AS request
    WHERE request.attempt_id = NEW.attempt_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closure already requested');
END;

CREATE TRIGGER scientific_attempt_operation_bindings_immutable_delete
BEFORE DELETE ON scientific_attempt_operation_bindings
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt operation bindings are immutable');
END;

CREATE TRIGGER scientific_attempt_operation_bindings_immutable_update
BEFORE UPDATE ON scientific_attempt_operation_bindings
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt operation bindings are immutable');
END;

CREATE TRIGGER scientific_attempt_run_after_closure_request_forbidden
BEFORE INSERT ON scientific_attempt_run_bindings
WHEN EXISTS (
    SELECT 1
    FROM scientific_attempt_closure_request_records AS request
    WHERE request.attempt_id = NEW.attempt_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closure already requested');
END;

CREATE TRIGGER scientific_attempt_run_bindings_immutable_delete
BEFORE DELETE ON scientific_attempt_run_bindings
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt run bindings are immutable');
END;

CREATE TRIGGER scientific_attempt_run_bindings_immutable_update
BEFORE UPDATE ON scientific_attempt_run_bindings
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt run bindings are immutable');
END;

CREATE TRIGGER scientific_attempt_scope_matches
BEFORE INSERT ON scientific_attempt_records
WHEN NOT EXISTS (
    SELECT 1
    FROM mutation_scope_records AS scope
    WHERE scope.scope_id = NEW.mutation_scope_id
      AND scope.session_id = NEW.session_id
      AND scope.scope_kind = 'attempt'
      AND scope.scope_ref = NEW.attempt_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt mutation scope identity mismatch');
END;

CREATE TRIGGER scientific_authority_identity_immutable
BEFORE UPDATE OF
    envelope_id,
    session_id,
    task_id,
    campaign_id,
    workflow_id,
    root_ref,
    grantor_kind,
    grantor_ref,
    allowed_scopes_json,
    allowed_effect_classes_json,
    allowed_providers_json,
    allowed_hpc_targets_json,
    max_attempts,
    max_micu,
    max_cost_microunits,
    max_wall_time_seconds,
    expires_at,
    policy_digest,
    idempotency_key,
    request_digest,
    created_at
ON scientific_attempt_authorization_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt authority identity is immutable');
END;

CREATE TRIGGER scientific_authority_no_delete
BEFORE DELETE ON scientific_attempt_authorization_records
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt authority is durable');
END;

CREATE TRIGGER scientific_authority_task_matches_session
BEFORE INSERT ON scientific_attempt_authorization_records
WHEN NOT EXISTS (
    SELECT 1 FROM tasks
    WHERE task_id = NEW.task_id AND session_id = NEW.session_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific authority task does not belong to session');
END;

CREATE TRIGGER scientific_chain_selection_records_no_delete
BEFORE DELETE ON scientific_chain_selection_records
BEGIN
    SELECT RAISE(ABORT, 'scientific selections are durable');
END;

CREATE TRIGGER scientific_contract_epoch_no_delete
BEFORE DELETE ON scientific_contract_epoch_records
BEGIN SELECT RAISE(ABORT, 'scientific contract epochs are immutable'); END;

CREATE TRIGGER scientific_contract_epoch_transition_guard
BEFORE UPDATE ON scientific_contract_epoch_records
WHEN NEW.epoch <> OLD.epoch
  OR NEW.contract_id <> OLD.contract_id
  OR NEW.contract_digest <> OLD.contract_digest
  OR NEW.prerequisite_receipt_digest <> OLD.prerequisite_receipt_digest
  OR NEW.quiescence_receipt_digest <> OLD.quiescence_receipt_digest
  OR NEW.prepared_at <> OLD.prepared_at
  OR NOT (
      (OLD.state = 'prepared' AND NEW.state = 'active')
      OR (OLD.state = 'active' AND NEW.state = 'retired')
  )
BEGIN
    SELECT RAISE(ABORT, 'scientific contract epoch transition invalid');
END;

CREATE TRIGGER scientific_deliverable_bundle_entry_matches
BEFORE INSERT ON scientific_deliverable_bundle_entry_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_deliverable_bundle_records AS bundle
    JOIN scientific_deliverable_ref_records AS ref ON ref.ref_id = NEW.ref_id
    WHERE bundle.bundle_id = NEW.bundle_id
      AND bundle.project_id = ref.project_id
      AND bundle.session_id = ref.session_id
      AND bundle.attempt_id = ref.attempt_id
      AND bundle.selection_id = ref.selection_id
      AND bundle.publication_id = ref.publication_id
      AND ref.scientific_role = NEW.scientific_role
      AND ref.repository_path = NEW.repository_path
)
BEGIN
    SELECT RAISE(ABORT, 'scientific bundle entry identity mismatch');
END;

CREATE TRIGGER scientific_deliverable_bundle_entry_records_immutable_delete
BEFORE DELETE ON scientific_deliverable_bundle_entry_records
BEGIN SELECT RAISE(ABORT, 'scientific deliverable bundle entries are immutable'); END;

CREATE TRIGGER scientific_deliverable_bundle_entry_records_immutable_update
BEFORE UPDATE ON scientific_deliverable_bundle_entry_records
BEGIN SELECT RAISE(ABORT, 'scientific deliverable bundle entries are immutable'); END;

CREATE TRIGGER scientific_deliverable_bundle_records_immutable_delete
BEFORE DELETE ON scientific_deliverable_bundle_records
BEGIN SELECT RAISE(ABORT, 'scientific deliverable bundles are immutable'); END;

CREATE TRIGGER scientific_deliverable_bundle_records_immutable_update
BEFORE UPDATE ON scientific_deliverable_bundle_records
BEGIN SELECT RAISE(ABORT, 'scientific deliverable bundles are immutable'); END;

CREATE TRIGGER scientific_deliverable_ref_matches
BEFORE INSERT ON scientific_deliverable_ref_records
WHEN NOT EXISTS (
    SELECT 1
    FROM published_revisions AS publication
    JOIN scientific_chain_selection_records AS selection
      ON selection.selection_id = NEW.selection_id
    JOIN scientific_selection_head_records AS head
      ON head.selection_id = selection.selection_id
     AND head.attempt_id = selection.attempt_id
    JOIN scientific_attempt_records AS attempt
      ON attempt.attempt_id = selection.attempt_id
    JOIN scientific_file_effect_adoption_records AS adoption
      ON adoption.adoption_id = NEW.producer_adoption_id
    WHERE publication.publication_id = NEW.publication_id
      AND publication.project_id = NEW.project_id
      AND publication.session_id = NEW.session_id
      AND publication.repository_binding_id = NEW.repository_binding_id
      AND publication.repository_binding_version = NEW.repository_binding_version
      AND publication.repository_policy_digest = NEW.repository_policy_digest
      AND publication.revision_digest = NEW.publication_digest
      AND publication.publication_ref = NEW.publication_ref
      AND publication.commit_id = NEW.published_commit
      AND publication.tree_id = NEW.published_tree
      AND publication.publisher_workspace_id = NEW.publisher_workspace_id
      AND publication.publisher_workspace_generation = NEW.publisher_workspace_generation
      AND publication.publisher_agent_member_id = NEW.publisher_agent_member_id
      AND selection.state = 'sealed'
      AND selection.attempt_id = NEW.attempt_id
      AND selection.revision = NEW.selection_revision
      AND selection.adoption_digest = NEW.selection_adoption_digest
      AND attempt.state_version = NEW.attempt_state_version
      AND adoption.selection_id = NEW.selection_id
      AND adoption.attempt_id = NEW.attempt_id
      AND adoption.workflow_role = NEW.scientific_role
      AND adoption.operation_id = NEW.producer_operation_id
      AND adoption.execution_id = NEW.producer_execution_id
      AND adoption.result_id = NEW.producer_result_id
      AND adoption.result_digest = NEW.producer_result_digest
)
BEGIN
    SELECT RAISE(ABORT, 'scientific deliverable ref identity mismatch');
END;

CREATE TRIGGER scientific_deliverable_ref_records_immutable_delete
BEFORE DELETE ON scientific_deliverable_ref_records
BEGIN SELECT RAISE(ABORT, 'scientific deliverable refs are immutable'); END;

CREATE TRIGGER scientific_deliverable_ref_records_immutable_update
BEFORE UPDATE ON scientific_deliverable_ref_records
BEGIN SELECT RAISE(ABORT, 'scientific deliverable refs are immutable'); END;

CREATE TRIGGER scientific_deliverable_validation_receipt_matches
BEFORE INSERT ON scientific_deliverable_validation_receipt_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_deliverable_bundle_records AS bundle
    JOIN published_revisions AS publication
      ON publication.publication_id = bundle.publication_id
    JOIN scientific_chain_selection_records AS selection
      ON selection.selection_id = bundle.selection_id
    JOIN scientific_selection_head_records AS head
      ON head.selection_id = selection.selection_id
    JOIN scientific_attempt_records AS attempt
      ON attempt.attempt_id = bundle.attempt_id
    WHERE bundle.bundle_id = NEW.bundle_id
      AND bundle.bundle_digest = NEW.bundle_digest
      AND bundle.publication_id = NEW.publication_id
      AND bundle.publication_digest = NEW.publication_digest
      AND bundle.attempt_id = NEW.attempt_id
      AND bundle.selection_id = NEW.selection_id
      AND bundle.validation_preimage_digest = NEW.validation_preimage_digest
      AND publication.revision_digest = NEW.publication_digest
      AND selection.state = 'sealed'
      AND selection.revision = NEW.selection_revision
      AND attempt.state_version = NEW.attempt_state_version
)
BEGIN
    SELECT RAISE(ABORT, 'scientific validation receipt identity mismatch');
END;

CREATE TRIGGER scientific_deliverable_validation_receipt_records_immutable_delete
BEFORE DELETE ON scientific_deliverable_validation_receipt_records
BEGIN SELECT RAISE(ABORT, 'scientific validation receipts are immutable'); END;

CREATE TRIGGER scientific_deliverable_validation_receipt_records_immutable_update
BEFORE UPDATE ON scientific_deliverable_validation_receipt_records
BEGIN SELECT RAISE(ABORT, 'scientific validation receipts are immutable'); END;

CREATE TRIGGER scientific_disposition_matches_occurrence
BEFORE INSERT ON scientific_operation_disposition_records
WHEN NOT EXISTS (
    SELECT 1 FROM scientific_selection_occurrence_records AS occurrence
    WHERE occurrence.selection_id = NEW.selection_id
      AND occurrence.attempt_id = NEW.attempt_id
      AND occurrence.operation_id = NEW.operation_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific disposition occurrence mismatch');
END;

CREATE TRIGGER scientific_effect_adoption_records_immutable_delete
BEFORE DELETE ON scientific_effect_adoption_records
BEGIN
    SELECT RAISE(ABORT, 'scientific effect adoptions are immutable');
END;

CREATE TRIGGER scientific_effect_adoption_records_immutable_update
BEFORE UPDATE ON scientific_effect_adoption_records
BEGIN
    SELECT RAISE(ABORT, 'scientific effect adoptions are immutable');
END;

CREATE TRIGGER scientific_file_effect_adoption_matches
BEFORE INSERT ON scientific_file_effect_adoption_records
WHEN NOT EXISTS (
    SELECT 1
    FROM scientific_chain_selection_records AS selection
    JOIN scientific_selection_head_records AS head
      ON head.selection_id = selection.selection_id
     AND head.attempt_id = selection.attempt_id
    JOIN scientific_operation_disposition_records AS disposition
      ON disposition.selection_id = selection.selection_id
     AND disposition.attempt_id = selection.attempt_id
     AND disposition.operation_id = NEW.operation_id
     AND disposition.kind = 'adopted'
     AND disposition.workflow_role = NEW.workflow_role
    JOIN controlled_operation_execution_records AS execution
      ON execution.execution_id = NEW.execution_id
     AND execution.operation_id = NEW.operation_id
     AND execution.lifecycle_state = 'terminal'
     AND execution.effect_certainty = NEW.effect_certainty
     AND execution.result_digest = NEW.result_digest
     AND execution.fencing_token = NEW.execution_fencing_token
    WHERE selection.selection_id = NEW.selection_id
      AND selection.attempt_id = NEW.attempt_id
      AND selection.revision = NEW.selection_revision
      AND (
          EXISTS (
              SELECT 1 FROM workspace_job_results AS result
              WHERE result.result_id = NEW.result_id
                AND result.execution_id = NEW.execution_id
                AND result.operation_id = NEW.operation_id
                AND result.result_digest = NEW.result_digest
          )
          OR EXISTS (
              SELECT 1 FROM controlled_operation_result_handles AS result
              WHERE result.result_handle_id = NEW.result_id
                AND result.execution_id = NEW.execution_id
                AND result.operation_id = NEW.operation_id
                AND result.result_digest = NEW.result_digest
                AND result.terminal_outcome = 'succeeded'
          )
      )
)
BEGIN
    SELECT RAISE(ABORT, 'scientific file effect adoption identity mismatch');
END;

CREATE TRIGGER scientific_file_effect_adoption_records_immutable_delete
BEFORE DELETE ON scientific_file_effect_adoption_records
BEGIN SELECT RAISE(ABORT, 'scientific file adoptions are immutable'); END;

CREATE TRIGGER scientific_file_effect_adoption_records_immutable_update
BEFORE UPDATE ON scientific_file_effect_adoption_records
BEGIN SELECT RAISE(ABORT, 'scientific file adoptions are immutable'); END;

CREATE TRIGGER scientific_operation_disposition_records_immutable_delete
BEFORE DELETE ON scientific_operation_disposition_records
BEGIN
    SELECT RAISE(ABORT, 'scientific operation dispositions are immutable');
END;

CREATE TRIGGER scientific_operation_disposition_records_immutable_update
BEFORE UPDATE ON scientific_operation_disposition_records
BEGIN
    SELECT RAISE(ABORT, 'scientific operation dispositions are immutable');
END;

CREATE TRIGGER scientific_selection_after_closure_request_forbidden
BEFORE INSERT ON scientific_chain_selection_records
WHEN EXISTS (
    SELECT 1
    FROM scientific_attempt_closure_request_records AS request
    WHERE request.attempt_id = NEW.attempt_id
)
BEGIN
    SELECT RAISE(ABORT, 'scientific attempt closure already requested');
END;

CREATE TRIGGER scientific_selection_head_matches
BEFORE INSERT ON scientific_selection_head_records
WHEN NOT EXISTS (
    SELECT 1 FROM scientific_chain_selection_records AS selection
    WHERE selection.selection_id = NEW.selection_id
      AND selection.attempt_id = NEW.attempt_id
      AND selection.revision = NEW.revision
)
BEGIN
    SELECT RAISE(ABORT, 'scientific selection head identity mismatch');
END;

CREATE TRIGGER scientific_selection_head_update_matches
BEFORE UPDATE ON scientific_selection_head_records
WHEN NOT EXISTS (
    SELECT 1 FROM scientific_chain_selection_records AS selection
    WHERE selection.selection_id = NEW.selection_id
      AND selection.attempt_id = NEW.attempt_id
      AND selection.revision = NEW.revision
)
BEGIN
    SELECT RAISE(ABORT, 'scientific selection head identity mismatch');
END;

CREATE TRIGGER scientific_selection_identity_immutable
BEFORE UPDATE OF
    selection_id,
    attempt_id,
    revision,
    parent_selection_id,
    operation_universe_digest,
    operation_count,
    workflow_contract_digest,
    actor_ref,
    idempotency_key,
    request_digest,
    created_at
ON scientific_chain_selection_records
BEGIN
    SELECT RAISE(ABORT, 'scientific selection identity is immutable');
END;

CREATE TRIGGER scientific_selection_occurrence_records_immutable_delete
BEFORE DELETE ON scientific_selection_occurrence_records
BEGIN
    SELECT RAISE(ABORT, 'scientific selection occurrences are immutable');
END;

CREATE TRIGGER scientific_selection_occurrence_records_immutable_update
BEFORE UPDATE ON scientific_selection_occurrence_records
BEGIN
    SELECT RAISE(ABORT, 'scientific selection occurrences are immutable');
END;

CREATE TRIGGER scientific_selection_sealed_immutable
BEFORE UPDATE ON scientific_chain_selection_records
WHEN OLD.state IN ('sealed', 'invalidated')
BEGIN
    SELECT RAISE(ABORT, 'sealed scientific selection is immutable');
END;
