-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.workspace.git.lfs
-- phase: triggers

-- Retained current control-plane indexes and triggers.

CREATE TRIGGER mutation_guard_git_lfs_quota_reservations_insert
BEFORE INSERT ON git_lfs_quota_reservations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_quota_reservations_update
BEFORE UPDATE ON git_lfs_quota_reservations
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'file_publication') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'file_publication') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_quota_reservations_delete
BEFORE DELETE ON git_lfs_quota_reservations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_upload_sessions_insert
BEFORE INSERT ON git_lfs_upload_sessions
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_upload_sessions_update
BEFORE UPDATE ON git_lfs_upload_sessions
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'file_publication') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'file_publication') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_upload_sessions_delete
BEFORE DELETE ON git_lfs_upload_sessions
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_workspace_object_links_insert
BEFORE INSERT ON git_lfs_workspace_object_links
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_workspace_object_links_update
BEFORE UPDATE ON git_lfs_workspace_object_links
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'file_publication') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'file_publication') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_workspace_object_links_delete
BEFORE DELETE ON git_lfs_workspace_object_links
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_intent_proofs_insert
BEFORE INSERT ON git_lfs_publication_intent_proofs
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_publication_intents AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.intent_id = NEW.intent_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_publication_intents WHERE intent_id = NEW.intent_id
), 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_intent_proofs_update
BEFORE UPDATE ON git_lfs_publication_intent_proofs
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM workspace_publication_intents AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.intent_id = OLD.intent_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_publication_intents WHERE intent_id = OLD.intent_id
), 'file_publication') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM workspace_publication_intents AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.intent_id = NEW.intent_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_publication_intents WHERE intent_id = NEW.intent_id
), 'file_publication') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_intent_proofs_delete
BEFORE DELETE ON git_lfs_publication_intent_proofs
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM workspace_publication_intents AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.intent_id = OLD.intent_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM workspace_publication_intents WHERE intent_id = OLD.intent_id
), 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_closures_insert
BEFORE INSERT ON git_lfs_publication_closures
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = NEW.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = NEW.publication_id
), 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_closures_update
BEFORE UPDATE ON git_lfs_publication_closures
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = OLD.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = OLD.publication_id
), 'file_publication') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = NEW.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = NEW.publication_id
), 'file_publication') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_closures_delete
BEFORE DELETE ON git_lfs_publication_closures
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = OLD.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = OLD.publication_id
), 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_pins_insert
BEFORE INSERT ON git_lfs_publication_pins
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = NEW.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = NEW.publication_id
), 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_pins_update
BEFORE UPDATE ON git_lfs_publication_pins
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = OLD.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = OLD.publication_id
), 'file_publication') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = NEW.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = NEW.publication_id
), 'file_publication') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_git_lfs_publication_pins_delete
BEFORE DELETE ON git_lfs_publication_pins
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM published_revisions AS owner
    JOIN mutation_scope_records AS scope ON scope.session_id = owner.session_id
    WHERE owner.publication_id = OLD.publication_id
) THEN openzyme_mutation_write_allowed((
    SELECT session_id FROM published_revisions WHERE publication_id = OLD.publication_id
), 'file_publication') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER agent_git_workspace_binding_and_pin_match
BEFORE INSERT ON agent_git_workspace_records
WHEN NOT EXISTS (
    SELECT 1
    FROM session_repository_binding_pins AS pin
    JOIN project_repository_binding_versions AS binding
      ON binding.binding_id = pin.binding_id
     AND binding.binding_version = pin.binding_version
     AND binding.repository_id = pin.repository_id
    WHERE pin.session_id = NEW.session_id
      AND pin.binding_id = NEW.repository_binding_id
      AND pin.binding_version = NEW.repository_binding_version
      AND pin.repository_id = NEW.repository_id
      AND pin.resolved_base_commit = NEW.base_commit
      AND pin.binding_canonical_digest = NEW.repository_binding_digest
      AND binding.canonical_digest = NEW.repository_binding_digest
      AND binding.internal_git_service_id = NEW.internal_git_service_id
      AND binding.internal_git_endpoint = NEW.internal_git_endpoint
      AND binding.object_format = NEW.object_format
      AND binding.repository_policy_version = NEW.repository_policy_version
      AND binding.repository_policy_digest = NEW.repository_policy_digest
)
BEGIN
    SELECT RAISE(ABORT, 'agent Git workspace repository binding drift');
END;

CREATE TRIGGER agent_git_workspace_insert_requires_provisioning
BEFORE INSERT ON agent_git_workspace_records
WHEN NEW.status <> 'provisioning' OR NEW.state_version <> 1
BEGIN
    SELECT RAISE(ABORT, 'agent Git workspace must start provisioning');
END;

CREATE TRIGGER agent_git_workspace_no_delete
BEFORE DELETE ON agent_git_workspace_records
BEGIN
    SELECT RAISE(ABORT, 'agent Git workspaces cannot be deleted');
END;

CREATE TRIGGER agent_git_workspace_owner_and_intent_match
BEFORE INSERT ON agent_git_workspace_records
WHEN NOT EXISTS (
    SELECT 1
    FROM agent_workspace_generation_reservations AS reservation
    JOIN agent_capability_lease_records AS lease
      ON lease.session_id = reservation.session_id
     AND lease.agent_member_id = reservation.agent_member_id
     AND lease.agent_id = reservation.agent_id
     AND lease.workspace_generation = reservation.workspace_generation
    WHERE reservation.reservation_id = NEW.reservation_id
      AND reservation.session_id = NEW.session_id
      AND reservation.agent_member_id = NEW.agent_member_id
      AND reservation.agent_id = NEW.agent_id
      AND reservation.workspace_generation = NEW.workspace_generation
      AND reservation.immutable_fingerprint = NEW.reservation_fingerprint
      AND reservation.status = 'reserved'
      AND lease.lease_id = NEW.capability_lease_id
      AND lease.canonical_digest = NEW.capability_lease_intent_digest
      AND lease.policy_version = NEW.capability_policy_version
      AND lease.policy_digest = NEW.capability_policy_digest
      AND lease.status = 'pending_workspace'
)
BEGIN
    SELECT RAISE(ABORT, 'agent Git workspace requires exact pending C2 intent');
END;

CREATE TRIGGER agent_git_workspace_ready_requires_closed_provision_credentials
BEFORE UPDATE OF status ON agent_git_workspace_records
WHEN NEW.status = 'ready' AND EXISTS (
    SELECT 1
    FROM repository_provision_credential_records
    WHERE workspace_id = NEW.workspace_id AND revoked_at IS NULL
)
BEGIN
    SELECT RAISE(ABORT, 'workspace readiness requires closed provision credentials');
END;

CREATE TRIGGER agent_git_workspace_ready_requires_pending_intent
BEFORE UPDATE OF status ON agent_git_workspace_records
WHEN NEW.status = 'ready' AND NOT EXISTS (
    SELECT 1
    FROM agent_workspace_generation_reservations AS reservation
    JOIN agent_capability_lease_records AS lease
      ON lease.session_id = reservation.session_id
     AND lease.agent_member_id = reservation.agent_member_id
     AND lease.agent_id = reservation.agent_id
     AND lease.workspace_generation = reservation.workspace_generation
    WHERE reservation.reservation_id = NEW.reservation_id
      AND reservation.immutable_fingerprint = NEW.reservation_fingerprint
      AND reservation.status = 'reserved'
      AND lease.lease_id = NEW.capability_lease_id
      AND lease.canonical_digest = NEW.capability_lease_intent_digest
      AND lease.status = 'pending_workspace'
      AND lease.policy_version = NEW.capability_policy_version
      AND lease.policy_digest = NEW.capability_policy_digest
)
BEGIN
    SELECT RAISE(ABORT, 'workspace readiness requires exact pending C2 intent');
END;

CREATE TRIGGER agent_git_workspace_replacement_requires_revoked_lease
BEFORE UPDATE OF status ON agent_git_workspace_records
WHEN NEW.status = 'replaced' AND EXISTS (
    SELECT 1
    FROM agent_capability_lease_records
    WHERE lease_id = NEW.capability_lease_id AND status <> 'revoked'
)
BEGIN
    SELECT RAISE(ABORT, 'workspace replacement requires revoked capability lease');
END;

CREATE TRIGGER agent_git_workspace_state_transition
BEFORE UPDATE ON agent_git_workspace_records
WHEN NEW.workspace_id IS NOT OLD.workspace_id
  OR NEW.session_id IS NOT OLD.session_id
  OR NEW.agent_member_id IS NOT OLD.agent_member_id
  OR NEW.agent_id IS NOT OLD.agent_id
  OR NEW.workspace_generation IS NOT OLD.workspace_generation
  OR NEW.reservation_id IS NOT OLD.reservation_id
  OR NEW.reservation_fingerprint IS NOT OLD.reservation_fingerprint
  OR NEW.capability_lease_id IS NOT OLD.capability_lease_id
  OR NEW.capability_lease_intent_digest IS NOT OLD.capability_lease_intent_digest
  OR NEW.repository_binding_id IS NOT OLD.repository_binding_id
  OR NEW.repository_binding_version IS NOT OLD.repository_binding_version
  OR NEW.repository_binding_digest IS NOT OLD.repository_binding_digest
  OR NEW.repository_id IS NOT OLD.repository_id
  OR NEW.internal_git_service_id IS NOT OLD.internal_git_service_id
  OR NEW.internal_git_endpoint IS NOT OLD.internal_git_endpoint
  OR NEW.object_format IS NOT OLD.object_format
  OR NEW.base_commit IS NOT OLD.base_commit
  OR NEW.volume_id IS NOT OLD.volume_id
  OR NEW.clone_logical_root IS NOT OLD.clone_logical_root
  OR NEW.image_ref IS NOT OLD.image_ref
  OR NEW.image_manifest_digest IS NOT OLD.image_manifest_digest
  OR NEW.image_qualification_digest IS NOT OLD.image_qualification_digest
  OR NEW.private_ref_namespace IS NOT OLD.private_ref_namespace
  OR NEW.repository_policy_version IS NOT OLD.repository_policy_version
  OR NEW.repository_policy_digest IS NOT OLD.repository_policy_digest
  OR NEW.capability_policy_version IS NOT OLD.capability_policy_version
  OR NEW.capability_policy_digest IS NOT OLD.capability_policy_digest
  OR NEW.created_at IS NOT OLD.created_at
  OR NEW.workspace_identity_digest IS NOT OLD.workspace_identity_digest
  OR NEW.schema_version IS NOT OLD.schema_version
  OR NEW.state_version <> OLD.state_version + 1
  OR NEW.canonical_digest = OLD.canonical_digest
  OR NOT (
      (OLD.status = 'provisioning'
       AND NEW.status IN ('ready', 'blocked', 'frozen'))
      OR (OLD.status = 'blocked' AND NEW.status IN ('ready', 'frozen'))
      OR (OLD.status = 'ready' AND NEW.status IN ('blocked', 'frozen'))
      OR (OLD.status = 'frozen' AND NEW.status = 'replaced')
  )
BEGIN
    SELECT RAISE(ABORT, 'invalid agent Git workspace transition');
END;

CREATE TRIGGER agent_workspace_generation_insert_requires_reserved
BEFORE INSERT ON agent_workspace_generation_reservations
WHEN NEW.status <> 'reserved'
BEGIN
    SELECT RAISE(ABORT, 'workspace generation must be issued as reserved');
END;

CREATE TRIGGER agent_workspace_generation_no_delete
BEFORE DELETE ON agent_workspace_generation_reservations
BEGIN
    SELECT RAISE(ABORT, 'workspace generation reservations cannot be deleted');
END;

CREATE TRIGGER agent_workspace_generation_owner_matches
BEFORE INSERT ON agent_workspace_generation_reservations
WHEN NOT EXISTS (
    SELECT 1
    FROM sessions
    WHERE session_id = NEW.session_id
      AND status IN ('active', 'paused')
) OR NOT EXISTS (
    SELECT 1
    FROM agent_members
    WHERE session_id = NEW.session_id
      AND member_id = NEW.agent_member_id
      AND agent_id = NEW.agent_id
) OR EXISTS (
    SELECT 1
    FROM agent_retirement_records
    WHERE session_id = NEW.session_id
      AND agent_member_id = NEW.agent_member_id
) OR EXISTS (
    SELECT 1
    FROM agent_retirement_requests
    WHERE session_id = NEW.session_id
      AND agent_member_id = NEW.agent_member_id
)
BEGIN
    SELECT RAISE(ABORT, 'workspace generation owner is invalid or retired');
END;

CREATE TRIGGER agent_workspace_generation_ready_requires_activation_authority
BEFORE UPDATE OF status ON agent_workspace_generation_reservations
WHEN OLD.status = 'reserved'
 AND NEW.status = 'ready'
 AND openzyme_agent_capability_readiness_activation_allowed(
    'reservation_ready',
    NEW.reservation_id,
    (
        SELECT lease_id
        FROM agent_capability_lease_records
        WHERE session_id = NEW.session_id
          AND agent_member_id = NEW.agent_member_id
          AND agent_id = NEW.agent_id
          AND workspace_generation = NEW.workspace_generation
          AND status = 'pending_workspace'
    ),
    NEW.session_id,
    NEW.agent_member_id,
    NEW.agent_id,
    NEW.workspace_generation,
    NEW.readiness_owner_ref,
    NEW.readiness_ref,
    NEW.readiness_digest,
    NEW.ready_at,
    NEW.state_version,
    NEW.canonical_digest,
    NULL,
    NULL,
    NULL
 ) <> 1
BEGIN
    SELECT RAISE(ABORT, 'workspace readiness activation authority rejected');
END;

CREATE TRIGGER agent_workspace_generation_ready_requires_agent_git_workspace
BEFORE UPDATE OF status ON agent_workspace_generation_reservations
WHEN NEW.status = 'ready'
  AND NEW.readiness_ref LIKE 'agent_git_workspace:%'
  AND NOT EXISTS (
    SELECT 1
    FROM agent_git_workspace_records AS workspace
    WHERE workspace.reservation_id = NEW.reservation_id
      AND workspace.reservation_fingerprint = NEW.immutable_fingerprint
      AND workspace.session_id = NEW.session_id
      AND workspace.agent_member_id = NEW.agent_member_id
      AND workspace.agent_id = NEW.agent_id
      AND workspace.workspace_generation = NEW.workspace_generation
      AND workspace.status = 'ready'
      AND NEW.readiness_ref = 'agent_git_workspace:' || workspace.workspace_id
)
BEGIN
    SELECT RAISE(ABORT, 'C2 readiness requires exact ready agent Git workspace');
END;

CREATE TRIGGER agent_workspace_generation_ready_requires_pending_lease
BEFORE UPDATE OF status ON agent_workspace_generation_reservations
WHEN NEW.status = 'ready'
 AND NOT EXISTS (
    SELECT 1
    FROM agent_capability_lease_records
    WHERE session_id = NEW.session_id
      AND agent_member_id = NEW.agent_member_id
      AND agent_id = NEW.agent_id
      AND workspace_generation = NEW.workspace_generation
      AND status = 'pending_workspace'
 )
BEGIN
    SELECT RAISE(ABORT, 'workspace readiness requires its pending lease');
END;

CREATE TRIGGER agent_workspace_generation_replacement_requires_revoked_lease
BEFORE UPDATE OF status ON agent_workspace_generation_reservations
WHEN NEW.status = 'replaced'
 AND EXISTS (
    SELECT 1
    FROM agent_capability_lease_records
    WHERE session_id = NEW.session_id
      AND agent_member_id = NEW.agent_member_id
      AND workspace_generation = NEW.workspace_generation
      AND status <> 'revoked'
 )
BEGIN
    SELECT RAISE(ABORT, 'workspace replacement requires its lease to be revoked');
END;

CREATE TRIGGER agent_workspace_generation_state_transition
BEFORE UPDATE ON agent_workspace_generation_reservations
WHEN NEW.reservation_id <> OLD.reservation_id
  OR NEW.session_id <> OLD.session_id
  OR NEW.agent_member_id <> OLD.agent_member_id
  OR NEW.agent_id <> OLD.agent_id
  OR NEW.workspace_generation <> OLD.workspace_generation
  OR NEW.reserved_at <> OLD.reserved_at
  OR NEW.immutable_fingerprint <> OLD.immutable_fingerprint
  OR NEW.schema_version <> OLD.schema_version
  OR NEW.state_version <> OLD.state_version + 1
  OR NEW.canonical_digest = OLD.canonical_digest
  OR NOT (
      (OLD.status = 'reserved' AND NEW.status IN ('ready', 'replaced'))
      OR
      (OLD.status = 'ready' AND NEW.status = 'replaced')
  )
  OR (
      OLD.status = 'ready'
      AND NEW.status = 'replaced'
      AND (
          NEW.readiness_owner_kind IS NOT OLD.readiness_owner_kind
          OR NEW.readiness_owner_ref IS NOT OLD.readiness_owner_ref
          OR NEW.readiness_ref IS NOT OLD.readiness_ref
          OR NEW.readiness_digest IS NOT OLD.readiness_digest
          OR NEW.ready_at IS NOT OLD.ready_at
      )
  )
BEGIN
    SELECT RAISE(ABORT, 'invalid workspace generation transition');
END;

CREATE TRIGGER agent_workspace_generation_strictly_increases
BEFORE INSERT ON agent_workspace_generation_reservations
WHEN EXISTS (
    SELECT 1
    FROM agent_workspace_generation_reservations
    WHERE session_id = NEW.session_id
      AND agent_member_id = NEW.agent_member_id
      AND workspace_generation >= NEW.workspace_generation
)
BEGIN
    SELECT RAISE(ABORT, 'workspace generation must strictly increase');
END;

CREATE TRIGGER agent_workspace_state_observation_append_only
BEFORE UPDATE ON agent_workspace_state_observations
BEGIN
    SELECT RAISE(ABORT, 'workspace state observations are append-only');
END;

CREATE TRIGGER agent_workspace_state_observation_exact_identity
BEFORE INSERT ON agent_workspace_state_observations
WHEN NOT EXISTS (
    SELECT 1
    FROM agent_git_workspace_records
    WHERE workspace_id = NEW.workspace_id
      AND session_id = NEW.session_id
      AND agent_member_id = NEW.agent_member_id
      AND agent_id = NEW.agent_id
      AND workspace_generation = NEW.workspace_generation
      AND status IN ('ready', 'frozen')
)
BEGIN
    SELECT RAISE(ABORT, 'workspace state observation requires exact workspace identity');
END;

CREATE TRIGGER agent_workspace_state_observation_no_delete
BEFORE DELETE ON agent_workspace_state_observations
BEGIN
    SELECT RAISE(ABORT, 'workspace state observations cannot be deleted');
END;

CREATE TRIGGER git_lfs_binding_policies_immutable_delete
BEFORE DELETE ON git_lfs_binding_policies
BEGIN
    SELECT RAISE(ABORT, 'Git LFS binding policies are immutable');
END;

CREATE TRIGGER git_lfs_binding_policies_immutable_update
BEFORE UPDATE ON git_lfs_binding_policies
BEGIN
    SELECT RAISE(ABORT, 'Git LFS binding policies are immutable');
END;

CREATE TRIGGER git_lfs_binding_policy_matches_repository_binding
BEFORE INSERT ON git_lfs_binding_policies
WHEN NOT EXISTS (
    SELECT 1
    FROM project_repository_binding_versions
    WHERE binding_id = NEW.binding_id
      AND binding_version = NEW.binding_version
      AND repository_id = NEW.repository_id
      AND lfs_service_id = NEW.lfs_service_id
      AND lfs_endpoint = NEW.lfs_endpoint
      AND repository_policy_version = NEW.policy_version
      AND repository_policy_digest = NEW.policy_digest
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS policy differs from immutable repository binding');
END;

CREATE TRIGGER git_lfs_closure_entries_immutable_delete
BEFORE DELETE ON git_lfs_closure_entries
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure entries are immutable');
END;

CREATE TRIGGER git_lfs_closure_entries_immutable_update
BEFORE UPDATE ON git_lfs_closure_entries
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure entries are immutable');
END;

CREATE TRIGGER git_lfs_closure_manifests_immutable_delete
BEFORE DELETE ON git_lfs_closure_manifests
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure manifests are immutable');
END;

CREATE TRIGGER git_lfs_closure_manifests_immutable_update
BEFORE UPDATE ON git_lfs_closure_manifests
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure manifests are immutable');
END;

CREATE TRIGGER git_lfs_closure_verification_entries_immutable_delete
BEFORE DELETE ON git_lfs_closure_verification_entries
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure verification entries are immutable');
END;

CREATE TRIGGER git_lfs_closure_verification_entries_immutable_update
BEFORE UPDATE ON git_lfs_closure_verification_entries
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure verification entries are immutable');
END;

CREATE TRIGGER git_lfs_closure_verification_entry_matches
BEFORE INSERT ON git_lfs_closure_verification_entries
WHEN NOT EXISTS (
    SELECT 1
    FROM git_lfs_closure_verifications v
    JOIN git_lfs_closure_entries e
      ON e.manifest_digest = v.manifest_digest
     AND e.repository_path = NEW.repository_path
    JOIN git_lfs_object_read_receipts r
      ON r.receipt_id = NEW.object_read_receipt_id
    WHERE v.verification_id = NEW.verification_id
      AND v.manifest_digest = NEW.manifest_digest
      AND r.binding_id = v.binding_id
      AND r.binding_version = v.binding_version
      AND r.repository_id = v.repository_id
      AND r.authorization_scope_digest = v.authorization_scope_digest
      AND r.oid = e.lfs_oid
      AND r.declared_size = e.size_bytes
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure verification entry drifted');
END;

CREATE TRIGGER git_lfs_closure_verification_matches_manifest
BEFORE INSERT ON git_lfs_closure_verifications
WHEN NOT EXISTS (
    SELECT 1 FROM git_lfs_closure_manifests m
    WHERE m.manifest_digest = NEW.manifest_digest
      AND m.binding_id = NEW.binding_id
      AND m.binding_version = NEW.binding_version
      AND m.repository_id = NEW.repository_id
      AND m.authorization_scope_digest = NEW.authorization_scope_digest
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure verification scope drifted');
END;

CREATE TRIGGER git_lfs_closure_verifications_immutable_delete
BEFORE DELETE ON git_lfs_closure_verifications
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure verifications are immutable');
END;

CREATE TRIGGER git_lfs_closure_verifications_immutable_update
BEFORE UPDATE ON git_lfs_closure_verifications
BEGIN
    SELECT RAISE(ABORT, 'Git LFS closure verifications are immutable');
END;

CREATE TRIGGER git_lfs_gc_candidate_items_immutable_delete
BEFORE DELETE ON git_lfs_gc_candidate_items
BEGIN
    SELECT RAISE(ABORT, 'Git LFS GC candidate items are immutable');
END;

CREATE TRIGGER git_lfs_gc_candidate_items_immutable_update
BEFORE UPDATE ON git_lfs_gc_candidate_items
BEGIN
    SELECT RAISE(ABORT, 'Git LFS GC candidate items are immutable');
END;

CREATE TRIGGER git_lfs_gc_candidate_receipts_immutable_delete
BEFORE DELETE ON git_lfs_gc_candidate_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS GC candidate receipts are immutable');
END;

CREATE TRIGGER git_lfs_gc_candidate_receipts_immutable_update
BEFORE UPDATE ON git_lfs_gc_candidate_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS GC candidate receipts are immutable');
END;

CREATE TRIGGER git_lfs_gc_deletion_receipts_immutable_delete
BEFORE DELETE ON git_lfs_gc_deletion_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS GC deletion receipts are immutable');
END;

CREATE TRIGGER git_lfs_gc_deletion_receipts_immutable_update
BEFORE UPDATE ON git_lfs_gc_deletion_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS GC deletion receipts are immutable');
END;

CREATE TRIGGER git_lfs_object_read_receipts_immutable_delete
BEFORE DELETE ON git_lfs_object_read_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS object-read receipts are immutable');
END;

CREATE TRIGGER git_lfs_object_read_receipts_immutable_update
BEFORE UPDATE ON git_lfs_object_read_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS object-read receipts are immutable');
END;

CREATE TRIGGER git_lfs_object_record_scope_matches
BEFORE INSERT ON git_lfs_object_records
WHEN NOT EXISTS (
    SELECT 1
    FROM git_lfs_binding_policies p
    JOIN git_lfs_upload_sessions u
      ON u.upload_session_id = NEW.first_upload_session_id
    WHERE p.binding_id = NEW.binding_id
      AND p.binding_version = NEW.binding_version
      AND p.repository_id = NEW.repository_id
      AND u.binding_id = NEW.binding_id
      AND u.binding_version = NEW.binding_version
      AND u.repository_id = NEW.repository_id
      AND u.oid = NEW.oid
      AND u.declared_size = NEW.size_bytes
      AND u.status IN ('reserved', 'committed')
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS object metadata scope drifted');
END;

CREATE TRIGGER git_lfs_object_records_insert_only
BEFORE UPDATE ON git_lfs_object_records
WHEN NEW.binding_id <> OLD.binding_id
  OR NEW.binding_version <> OLD.binding_version
  OR NEW.repository_id <> OLD.repository_id
  OR NEW.oid <> OLD.oid
  OR NEW.size_bytes <> OLD.size_bytes
  OR NEW.first_upload_session_id <> OLD.first_upload_session_id
  OR NEW.object_receipt_digest <> OLD.object_receipt_digest
  OR NEW.created_at <> OLD.created_at
  OR OLD.deleted_at IS NOT NULL
  OR (
      NEW.retention_class = 'published'
      AND (
          OLD.retention_class <> 'private'
          OR NEW.retained_until IS NOT NULL
          OR NEW.deleted_at IS NOT OLD.deleted_at
          OR NEW.deletion_receipt_id IS NOT OLD.deletion_receipt_id
      )
  )
  OR (
      NEW.deleted_at IS NOT NULL
      AND (
          OLD.retention_class <> 'private'
          OR NEW.retention_class <> OLD.retention_class
          OR NEW.retained_until IS NOT OLD.retained_until
          OR NEW.deletion_receipt_id IS NULL
      )
  )
  OR (NEW.retention_class <> 'published' AND NEW.deleted_at IS NULL)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS object metadata permits only publication pin or exact GC tombstone');
END;

CREATE TRIGGER git_lfs_object_records_no_delete
BEFORE DELETE ON git_lfs_object_records
BEGIN
    SELECT RAISE(ABORT, 'Git LFS object metadata requires an exact GC deletion receipt');
END;

CREATE TRIGGER git_lfs_private_reachability_receipt_matches
BEFORE INSERT ON git_lfs_private_reachability_receipts
WHEN NOT EXISTS (
    SELECT 1
    FROM repository_private_namespace_records n
    JOIN repository_private_namespace_retirement_receipts r
      ON r.namespace_id = n.namespace_id
    JOIN git_lfs_binding_policies p
      ON p.binding_id = n.binding_id
     AND p.binding_version = n.binding_version
    WHERE n.namespace_id = NEW.namespace_id
      AND n.binding_id = NEW.binding_id
      AND n.binding_version = NEW.binding_version
      AND n.workspace_generation = NEW.workspace_generation
      AND n.status IN ('closed', 'retired')
      AND r.receipt_id = NEW.retirement_receipt_id
      AND p.repository_id = NEW.repository_id
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS private reachability receipt scope drifted');
END;

CREATE TRIGGER git_lfs_private_reachability_receipts_immutable_delete
BEFORE DELETE ON git_lfs_private_reachability_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS private reachability receipts are immutable');
END;

CREATE TRIGGER git_lfs_private_reachability_receipts_immutable_update
BEFORE UPDATE ON git_lfs_private_reachability_receipts
BEGIN
    SELECT RAISE(ABORT, 'Git LFS private reachability receipts are immutable');
END;

CREATE TRIGGER git_lfs_publication_closure_matches_revision
BEFORE INSERT ON git_lfs_publication_closures
WHEN NOT EXISTS (
    SELECT 1
    FROM published_revisions p
    JOIN git_lfs_closure_manifests m ON m.manifest_digest = NEW.manifest_digest
    JOIN git_lfs_closure_verifications v
      ON v.verification_id = NEW.verification_id
     AND v.manifest_digest = m.manifest_digest
    JOIN git_lfs_publication_intent_proofs proof
      ON proof.intent_id = p.intent_id
     AND proof.publication_id = p.publication_id
    WHERE p.publication_id = NEW.publication_id
      AND p.repository_binding_id = NEW.binding_id
      AND p.repository_binding_version = NEW.binding_version
      AND p.repository_id = NEW.repository_id
      AND p.commit_id = m.commit_id
      AND p.tree_id = m.tree_id
      AND p.repository_policy_digest = m.policy_digest
      AND v.verification_digest = NEW.verification_digest
      AND proof.manifest_digest = NEW.manifest_digest
      AND proof.verification_id = NEW.verification_id
      AND proof.verification_digest = NEW.verification_digest
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication closure differs from revision identity');
END;

CREATE TRIGGER git_lfs_publication_closures_immutable_delete
BEFORE DELETE ON git_lfs_publication_closures
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication closures are immutable');
END;

CREATE TRIGGER git_lfs_publication_closures_immutable_update
BEFORE UPDATE ON git_lfs_publication_closures
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication closures are immutable');
END;

CREATE TRIGGER git_lfs_publication_intent_proof_matches
BEFORE INSERT ON git_lfs_publication_intent_proofs
WHEN NOT EXISTS (
    SELECT 1
    FROM workspace_publication_intents i
    JOIN git_lfs_closure_manifests m ON m.manifest_digest = NEW.manifest_digest
    JOIN git_lfs_closure_verifications v
      ON v.verification_id = NEW.verification_id
     AND v.manifest_digest = m.manifest_digest
    WHERE i.intent_id = NEW.intent_id
      AND i.publication_id = NEW.publication_id
      AND i.repository_binding_id = NEW.binding_id
      AND i.repository_binding_version = NEW.binding_version
      AND i.repository_id = NEW.repository_id
      AND i.expected_head_commit = NEW.commit_id
      AND i.expected_tree = NEW.tree_id
      AND i.repository_policy_digest = m.policy_digest
      AND v.verification_digest = NEW.verification_digest
      AND v.authorization_scope_digest = m.authorization_scope_digest
      AND (
          SELECT COUNT(*) FROM git_lfs_closure_entries ce
          WHERE ce.manifest_digest = m.manifest_digest
      ) = (
          SELECT COUNT(*) FROM git_lfs_closure_verification_entries ve
          WHERE ve.verification_id = v.verification_id
            AND ve.manifest_digest = m.manifest_digest
      )
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication intent proof drifted');
END;

CREATE TRIGGER git_lfs_publication_intent_proofs_immutable_delete
BEFORE DELETE ON git_lfs_publication_intent_proofs
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication intent proofs are immutable');
END;

CREATE TRIGGER git_lfs_publication_intent_proofs_immutable_update
BEFORE UPDATE ON git_lfs_publication_intent_proofs
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication intent proofs are immutable');
END;

CREATE TRIGGER git_lfs_publication_pin_matches_revision
BEFORE INSERT ON git_lfs_publication_pins
WHEN NOT EXISTS (
    SELECT 1
    FROM git_lfs_publication_closures c
    JOIN published_revisions p ON p.publication_id = c.publication_id
    JOIN git_lfs_closure_manifests m
      ON m.manifest_digest = c.manifest_digest
    JOIN git_lfs_closure_entries e
      ON e.manifest_digest = NEW.manifest_digest
     AND e.lfs_oid = NEW.lfs_oid
     AND e.size_bytes = NEW.size_bytes
    WHERE c.publication_id = NEW.publication_id
      AND c.manifest_digest = NEW.manifest_digest
      AND c.binding_id = NEW.binding_id
      AND c.binding_version = NEW.binding_version
      AND c.repository_id = NEW.repository_id
      AND p.repository_binding_id = NEW.binding_id
      AND p.repository_binding_version = NEW.binding_version
      AND p.repository_id = NEW.repository_id
      AND p.commit_id = m.commit_id
      AND p.tree_id = m.tree_id
      AND p.repository_policy_digest = m.policy_digest
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication pin differs from revision closure');
END;

CREATE TRIGGER git_lfs_publication_pins_immutable_delete
BEFORE DELETE ON git_lfs_publication_pins
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication pins are immutable');
END;

CREATE TRIGGER git_lfs_publication_pins_immutable_update
BEFORE UPDATE ON git_lfs_publication_pins
BEGIN
    SELECT RAISE(ABORT, 'Git LFS publication pins are immutable');
END;

CREATE TRIGGER git_lfs_quota_reservations_no_delete
BEFORE DELETE ON git_lfs_quota_reservations
BEGIN
    SELECT RAISE(ABORT, 'Git LFS quota reservations cannot be deleted');
END;

CREATE TRIGGER git_lfs_quota_reservations_settle_only
BEFORE UPDATE ON git_lfs_quota_reservations
WHEN NEW.reservation_id <> OLD.reservation_id
  OR NEW.upload_session_id <> OLD.upload_session_id
  OR NEW.binding_id <> OLD.binding_id
  OR NEW.binding_version <> OLD.binding_version
  OR NEW.repository_id <> OLD.repository_id
  OR NEW.session_id <> OLD.session_id
  OR NEW.agent_member_id <> OLD.agent_member_id
  OR NEW.workspace_generation <> OLD.workspace_generation
  OR NEW.oid <> OLD.oid
  OR NEW.reserved_bytes <> OLD.reserved_bytes
  OR NEW.created_at <> OLD.created_at
  OR NEW.expires_at <> OLD.expires_at
  OR OLD.state <> 'reserved'
  OR NEW.state NOT IN ('committed', 'released')
  OR NEW.settled_at IS NULL
BEGIN
    SELECT RAISE(ABORT, 'Git LFS quota reservation permits one settlement');
END;

CREATE TRIGGER git_lfs_upload_session_scope_matches
BEFORE INSERT ON git_lfs_upload_sessions
WHEN NOT EXISTS (
    SELECT 1
    FROM repository_credential_issuance_records c
    JOIN session_repository_binding_pins p ON p.session_id = c.session_id
    WHERE c.credential_id = NEW.credential_id
      AND c.binding_id = NEW.binding_id
      AND c.binding_version = NEW.binding_version
      AND c.repository_id = NEW.repository_id
      AND c.session_id = NEW.session_id
      AND c.agent_member_id = NEW.agent_member_id
      AND c.workspace_generation = NEW.workspace_generation
      AND c.revoked_at IS NULL
      AND p.binding_id = NEW.binding_id
      AND p.binding_version = NEW.binding_version
      AND p.repository_id = NEW.repository_id
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS upload scope differs from credential and session pin');
END;

CREATE TRIGGER git_lfs_upload_sessions_no_delete
BEFORE DELETE ON git_lfs_upload_sessions
BEGIN
    SELECT RAISE(ABORT, 'Git LFS upload sessions cannot be deleted');
END;

CREATE TRIGGER git_lfs_upload_sessions_terminal_only
BEFORE UPDATE ON git_lfs_upload_sessions
WHEN NEW.upload_session_id <> OLD.upload_session_id
  OR NEW.binding_id <> OLD.binding_id
  OR NEW.binding_version <> OLD.binding_version
  OR NEW.repository_id <> OLD.repository_id
  OR NEW.session_id <> OLD.session_id
  OR NEW.agent_member_id <> OLD.agent_member_id
  OR NEW.workspace_generation <> OLD.workspace_generation
  OR NEW.credential_id <> OLD.credential_id
  OR NEW.oid <> OLD.oid
  OR NEW.declared_size <> OLD.declared_size
  OR NEW.reserved_bytes <> OLD.reserved_bytes
  OR NEW.created_at <> OLD.created_at
  OR NEW.expires_at <> OLD.expires_at
  OR OLD.status <> 'reserved'
  OR NEW.status NOT IN ('committed', 'aborted')
  OR NEW.completed_at IS NULL
BEGIN
    SELECT RAISE(ABORT, 'Git LFS upload session permits one terminal transition');
END;

CREATE TRIGGER git_lfs_workspace_object_link_scope_matches
BEFORE INSERT ON git_lfs_workspace_object_links
WHEN NOT EXISTS (
    SELECT 1
    FROM repository_credential_issuance_records c
    JOIN repository_private_namespace_records n
      ON n.binding_id = c.binding_id
     AND n.binding_version = c.binding_version
     AND n.session_id = c.session_id
     AND n.agent_member_id = c.agent_member_id
     AND n.workspace_generation = c.workspace_generation
    WHERE c.credential_id = NEW.credential_id
      AND c.binding_id = NEW.binding_id
      AND c.binding_version = NEW.binding_version
      AND c.repository_id = NEW.repository_id
      AND c.session_id = NEW.session_id
      AND c.agent_member_id = NEW.agent_member_id
      AND c.workspace_generation = NEW.workspace_generation
      AND c.revoked_at IS NULL
      AND n.status IN ('open', 'closed')
      AND NOT EXISTS (
          SELECT 1 FROM repository_private_namespace_retirement_receipts r
          WHERE r.namespace_id = n.namespace_id
      )
)
BEGIN
    SELECT RAISE(ABORT, 'Git LFS workspace object link scope drifted');
END;

CREATE TRIGGER git_lfs_workspace_object_links_immutable_delete
BEFORE DELETE ON git_lfs_workspace_object_links
BEGIN
    SELECT RAISE(ABORT, 'Git LFS workspace object links are immutable');
END;

CREATE TRIGGER git_lfs_workspace_object_links_immutable_update
BEFORE UPDATE ON git_lfs_workspace_object_links
BEGIN
    SELECT RAISE(ABORT, 'Git LFS workspace object links are immutable');
END;

CREATE TRIGGER mutation_guard_agent_git_workspace_records_delete
BEFORE DELETE ON agent_git_workspace_records
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_agent_git_workspace_records_insert
BEFORE INSERT ON agent_git_workspace_records
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_agent_git_workspace_records_update
BEFORE UPDATE ON agent_git_workspace_records
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_agent_workspace_generation_reservations_delete
BEFORE DELETE ON agent_workspace_generation_reservations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_agent_workspace_generation_reservations_insert
BEFORE INSERT ON agent_workspace_generation_reservations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_agent_workspace_generation_reservations_update
BEFORE UPDATE ON agent_workspace_generation_reservations
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_agent_workspace_state_observations_delete
BEFORE DELETE ON agent_workspace_state_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_agent_workspace_state_observations_insert
BEFORE INSERT ON agent_workspace_state_observations
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_agent_workspace_state_observations_update
BEFORE UPDATE ON agent_workspace_state_observations
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN SELECT RAISE(ABORT, 'mutation write authority rejected'); END;

CREATE TRIGGER mutation_guard_repository_provision_credential_records_delete
BEFORE DELETE ON repository_provision_credential_records
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_repository_provision_credential_records_insert
BEFORE INSERT ON repository_provision_credential_records
WHEN CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER mutation_guard_repository_provision_credential_records_update
BEFORE UPDATE ON repository_provision_credential_records
WHEN (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = OLD.session_id
) THEN openzyme_mutation_write_allowed(OLD.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
 OR (CASE WHEN EXISTS (
    SELECT 1 FROM mutation_scope_records WHERE session_id = NEW.session_id
) THEN openzyme_mutation_write_allowed(NEW.session_id, 'canonical_sqlite') <> 1 ELSE 0 END)
BEGIN
    SELECT RAISE(ABORT, 'mutation write authority rejected');
END;

CREATE TRIGGER repository_capability_hold_requires_active_lease
BEFORE INSERT ON repository_private_namespace_holds
WHEN NEW.hold_kind = 'active_capability_lease'
 AND (
 NOT EXISTS (
    SELECT 1
    FROM repository_private_namespace_records AS namespace
    JOIN agent_capability_lease_records AS lease
      ON lease.lease_id = NEW.owner_ref
     AND lease.session_id = namespace.session_id
     AND lease.agent_member_id = namespace.agent_member_id
     AND lease.workspace_generation = namespace.workspace_generation
    WHERE namespace.namespace_id = NEW.namespace_id
      AND lease.status = 'active'
 ) OR EXISTS (
    SELECT 1
    FROM agent_retirement_requests AS request
    JOIN agent_capability_lease_records AS lease
      ON lease.lease_id = NEW.owner_ref
     AND lease.session_id = request.session_id
     AND lease.agent_member_id = request.agent_member_id
 )
 )
BEGIN
    SELECT RAISE(ABORT, 'repository hold requires exact active capability lease');
END;

CREATE TRIGGER repository_credential_issuance_identity_matches
BEFORE INSERT ON repository_credential_issuance_records
WHEN NOT EXISTS (
    SELECT 1
    FROM session_repository_binding_pins
    WHERE session_id = NEW.session_id
      AND binding_id = NEW.binding_id
      AND binding_version = NEW.binding_version
      AND repository_id = NEW.repository_id
)
BEGIN
    SELECT RAISE(ABORT, 'repository credential session binding mismatch');
END;

CREATE TRIGGER repository_credential_issuance_records_immutable_identity
BEFORE UPDATE ON repository_credential_issuance_records
WHEN NEW.credential_id <> OLD.credential_id
  OR NEW.token_digest <> OLD.token_digest
  OR NEW.binding_id <> OLD.binding_id
  OR NEW.binding_version <> OLD.binding_version
  OR NEW.repository_id <> OLD.repository_id
  OR NEW.session_id <> OLD.session_id
  OR NEW.agent_member_id <> OLD.agent_member_id
  OR NEW.workspace_generation <> OLD.workspace_generation
  OR NEW.capability_lease_id <> OLD.capability_lease_id
  OR NEW.protocols_json <> OLD.protocols_json
  OR NEW.ref_classes_json <> OLD.ref_classes_json
  OR NEW.claims_digest <> OLD.claims_digest
  OR NEW.issued_at <> OLD.issued_at
  OR NEW.expires_at <> OLD.expires_at
  OR OLD.revoked_at IS NOT NULL
  OR NEW.revoked_at IS NULL
BEGIN
    SELECT RAISE(ABORT, 'repository credential identity is immutable');
END;

CREATE TRIGGER repository_credential_issuance_records_no_delete
BEFORE DELETE ON repository_credential_issuance_records
BEGIN
    SELECT RAISE(ABORT, 'repository credential issuance records cannot be deleted');
END;

CREATE TRIGGER repository_credential_requires_active_capability_lease
BEFORE INSERT ON repository_credential_issuance_records
WHEN NOT EXISTS (
    SELECT 1
    FROM agent_capability_lease_records AS lease
    WHERE lease.lease_id = NEW.capability_lease_id
      AND lease.session_id = NEW.session_id
      AND lease.agent_member_id = NEW.agent_member_id
      AND lease.workspace_generation = NEW.workspace_generation
      AND lease.status = 'active'
      AND EXISTS (
          SELECT 1
          FROM json_each(lease.capabilities_json)
          WHERE value = 'git'
      )
      AND (
          NOT EXISTS (
              SELECT 1
              FROM json_each(NEW.protocols_json)
              WHERE value IN ('lfs_read', 'lfs_write')
          )
          OR EXISTS (
              SELECT 1
              FROM json_each(lease.capabilities_json)
              WHERE value = 'git_lfs'
          )
      )
) OR EXISTS (
    SELECT 1
    FROM agent_retirement_requests
    WHERE session_id = NEW.session_id
      AND agent_member_id = NEW.agent_member_id
)
BEGIN
    SELECT RAISE(ABORT, 'repository credential requires exact active capability lease');
END;

CREATE TRIGGER repository_private_namespace_hold_requires_live_namespace
BEFORE INSERT ON repository_private_namespace_holds
WHEN NOT EXISTS (
    SELECT 1
    FROM repository_private_namespace_records
    WHERE namespace_id = NEW.namespace_id
      AND status IN ('open', 'closed')
) OR EXISTS (
    SELECT 1
    FROM repository_private_namespace_retirement_receipts
    WHERE namespace_id = NEW.namespace_id
)
BEGIN
    SELECT RAISE(ABORT, 'repository private namespace is not retainable');
END;

CREATE TRIGGER repository_private_namespace_holds_no_delete
BEFORE DELETE ON repository_private_namespace_holds
BEGIN
    SELECT RAISE(ABORT, 'repository namespace holds cannot be deleted');
END;

CREATE TRIGGER repository_private_namespace_holds_release_only
BEFORE UPDATE ON repository_private_namespace_holds
WHEN NEW.hold_id <> OLD.hold_id
  OR NEW.namespace_id <> OLD.namespace_id
  OR NEW.hold_kind <> OLD.hold_kind
  OR NEW.owner_ref <> OLD.owner_ref
  OR NEW.created_at <> OLD.created_at
  OR OLD.released_at IS NOT NULL
  OR NEW.released_at IS NULL
BEGIN
    SELECT RAISE(ABORT, 'repository namespace holds are release-only');
END;

CREATE TRIGGER repository_private_namespace_owner_matches
BEFORE INSERT ON repository_private_namespace_records
WHEN NOT EXISTS (
    SELECT 1
    FROM session_repository_binding_pins
    WHERE session_id = NEW.session_id
      AND binding_id = NEW.binding_id
      AND binding_version = NEW.binding_version
)
BEGIN
    SELECT RAISE(ABORT, 'repository private namespace owner mismatch');
END;

CREATE TRIGGER repository_private_namespace_records_no_delete
BEFORE DELETE ON repository_private_namespace_records
BEGIN
    SELECT RAISE(ABORT, 'repository private namespace records cannot be deleted');
END;

CREATE TRIGGER repository_private_namespace_retirement_receipt_matches
BEFORE INSERT ON repository_private_namespace_retirement_receipts
WHEN NOT EXISTS (
    SELECT 1
    FROM repository_private_namespace_records
    WHERE namespace_id = NEW.namespace_id
      AND binding_id = NEW.binding_id
      AND binding_version = NEW.binding_version
      AND namespace_prefix = NEW.namespace_prefix
      AND status = 'closed'
)
BEGIN
    SELECT RAISE(ABORT, 'repository namespace retirement receipt owner mismatch');
END;

CREATE TRIGGER repository_private_namespace_retirement_receipts_immutable_delete
BEFORE DELETE ON repository_private_namespace_retirement_receipts
BEGIN
    SELECT RAISE(ABORT, 'repository namespace retirement receipts are immutable');
END;

CREATE TRIGGER repository_private_namespace_retirement_receipts_immutable_update
BEFORE UPDATE ON repository_private_namespace_retirement_receipts
BEGIN
    SELECT RAISE(ABORT, 'repository namespace retirement receipts are immutable');
END;

CREATE TRIGGER repository_private_namespace_status_transition
BEFORE UPDATE ON repository_private_namespace_records
WHEN NEW.namespace_id <> OLD.namespace_id
  OR NEW.binding_id <> OLD.binding_id
  OR NEW.binding_version <> OLD.binding_version
  OR NEW.session_id <> OLD.session_id
  OR NEW.agent_member_id <> OLD.agent_member_id
  OR NEW.workspace_generation <> OLD.workspace_generation
  OR NEW.namespace_prefix <> OLD.namespace_prefix
  OR NEW.retention_deadline <> OLD.retention_deadline
  OR NEW.opened_at <> OLD.opened_at
  OR NOT (
      (OLD.status = 'open' AND NEW.status = 'closed'
       AND OLD.closed_at IS NULL AND NEW.closed_at IS NOT NULL
       AND NEW.retired_at IS NULL)
      OR
      (OLD.status = 'closed' AND NEW.status = 'retired'
       AND NEW.closed_at = OLD.closed_at
       AND OLD.retired_at IS NULL AND NEW.retired_at IS NOT NULL)
  )
  OR (
      NEW.status = 'retired'
      AND NOT EXISTS (
          SELECT 1
          FROM repository_private_namespace_retirement_receipts
          WHERE namespace_id = NEW.namespace_id
      )
  )
BEGIN
    SELECT RAISE(ABORT, 'invalid repository private namespace transition');
END;

CREATE TRIGGER repository_provision_credential_exact_pending_workspace
BEFORE INSERT ON repository_provision_credential_records
WHEN NOT EXISTS (
    SELECT 1
    FROM agent_git_workspace_records AS workspace
    JOIN agent_capability_lease_records AS lease
      ON lease.lease_id = workspace.capability_lease_id
    WHERE workspace.workspace_id = NEW.workspace_id
      AND workspace.repository_binding_id = NEW.binding_id
      AND workspace.repository_binding_version = NEW.binding_version
      AND workspace.repository_id = NEW.repository_id
      AND workspace.session_id = NEW.session_id
      AND workspace.agent_member_id = NEW.agent_member_id
      AND workspace.agent_id = NEW.agent_id
      AND workspace.workspace_generation = NEW.workspace_generation
      AND workspace.capability_lease_id = NEW.capability_lease_id
      AND workspace.status = 'provisioning'
      AND lease.status = 'pending_workspace'
)
BEGIN
    SELECT RAISE(ABORT, 'provision credential requires exact pending workspace');
END;

CREATE TRIGGER repository_provision_credential_no_delete
BEFORE DELETE ON repository_provision_credential_records
BEGIN
    SELECT RAISE(ABORT, 'repository provision credentials cannot be deleted');
END;

CREATE TRIGGER repository_provision_credential_state_transition
BEFORE UPDATE ON repository_provision_credential_records
WHEN NEW.credential_id IS NOT OLD.credential_id
  OR NEW.token_digest IS NOT OLD.token_digest
  OR NEW.workspace_id IS NOT OLD.workspace_id
  OR NEW.binding_id IS NOT OLD.binding_id
  OR NEW.binding_version IS NOT OLD.binding_version
  OR NEW.repository_id IS NOT OLD.repository_id
  OR NEW.session_id IS NOT OLD.session_id
  OR NEW.agent_member_id IS NOT OLD.agent_member_id
  OR NEW.agent_id IS NOT OLD.agent_id
  OR NEW.workspace_generation IS NOT OLD.workspace_generation
  OR NEW.capability_lease_id IS NOT OLD.capability_lease_id
  OR NEW.protocols_json IS NOT OLD.protocols_json
  OR NEW.claims_digest IS NOT OLD.claims_digest
  OR NEW.issued_at IS NOT OLD.issued_at
  OR NEW.expires_at IS NOT OLD.expires_at
  OR NEW.schema_version IS NOT OLD.schema_version
  OR OLD.revoked_at IS NOT NULL
  OR NEW.revoked_at IS NULL
BEGIN
    SELECT RAISE(ABORT, 'invalid provision credential transition');
END;
