-- Generated by scripts/partition-openzyme-sqlite-schema.py.
-- semantic_owner: openzyme.store.sqlite
-- phase: finalize

INSERT INTO deployment_schema_state (singleton, schema_generation, removal_state, removal_receipt_digest, manifest_digest, updated_at) VALUES (1, 'openzyme_file_workspace_final@2', 'fresh_install_complete', 'sha256:e62e9e17308fa64bc395d6aed9496e51b5212b4d05bc2f077ceffca448771a10', 'sha256:3ae48fd88ce9769be4df0a8b166d96f5f8eef4dc0ac7a0861b2c0e6237451123', '1970-01-01T00:00:00+00:00');

PRAGMA user_version = 2;
