from __future__ import annotations

from typing import Any


S12_ROUTE_POLICIES: dict[str, dict[str, Any]] = {
    "bio.ncbi_fetch_proteins.provider:v1": {
        "sdk_module": "bio",
        "function_name": "ncbi_fetch_proteins",
        "selected_backend": "provider_http",
        "backend_category": "provider_http",
        "route_reason": "static_policy:v1",
        "resource_class": "network_io",
        "runtime_packaging_id": "provider_http:v1",
        "provider_config_digest": "provider_config:ncbi:v1",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#provider-evidence-ncbi",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#provider-evidence-ncbi",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "bio.uniprot_fetch.provider:v1": {
        "sdk_module": "bio",
        "function_name": "uniprot_fetch",
        "selected_backend": "provider_http",
        "backend_category": "provider_http",
        "route_reason": "static_policy:v1",
        "resource_class": "network_io",
        "runtime_packaging_id": "provider_http:v1",
        "provider_config_digest": "provider_config:uniprot:v3",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#provider-evidence-uniprot",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#provider-evidence-uniprot",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "rcsb_pdb.download_structure.provider:v1": {
        "sdk_module": "rcsb_pdb",
        "function_name": "download_structure",
        "selected_backend": "provider_http",
        "backend_category": "provider_http",
        "route_reason": "static_policy:v1",
        "resource_class": "network_io",
        "runtime_packaging_id": "provider_http:v1",
        "provider_config_digest": "provider_config:rcsb_pdb:v1",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#provider-evidence-rcsb-pdb",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#parameter-inventory-rcsb-pdb",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "bio.hmmer_search.provider:v1": {
        "sdk_module": "bio",
        "function_name": "hmmer_search",
        "selected_backend": "provider_http",
        "backend_category": "provider_http",
        "route_reason": "static_policy:v1",
        "resource_class": "network_io",
        "runtime_packaging_id": "provider_http:v1",
        "provider_config_digest": "provider_config:ebi_hmmer:v3",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#provider-evidence-ebi-hmmer-rest",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#provider-evidence-ebi-hmmer-rest",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "bio_tools.cdhit.hpc:v1": {
        "sdk_module": "bio_tools",
        "function_name": "cdhit",
        "selected_backend": "hpc",
        "backend_category": "hpc_runner",
        "route_reason": "static_policy:v1",
        "resource_class": "hpc_batch_small",
        "runtime_packaging_id": "hpc_apptainer_sif.aox_hmm_2026_05_30",
        "toolchain_id": "cdhit_4.8.1.hpc_apptainer_sif:v1",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#hpc-evidence",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#parameter-inventory-cd-hit",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "bio_tools.mafft.hpc:v1": {
        "sdk_module": "bio_tools",
        "function_name": "mafft",
        "selected_backend": "hpc",
        "backend_category": "hpc_runner",
        "route_reason": "static_policy:v1",
        "resource_class": "hpc_batch_small",
        "runtime_packaging_id": "hpc_apptainer_sif.aox_hmm_2026_05_30",
        "toolchain_id": "mafft_7.525.hpc_apptainer_sif:v1",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#hpc-evidence",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#parameter-inventory-mafft",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "bio_tools.hmmbuild.hpc:v1": {
        "sdk_module": "bio_tools",
        "function_name": "hmmbuild",
        "selected_backend": "hpc",
        "backend_category": "hpc_runner",
        "route_reason": "static_policy:v1",
        "resource_class": "hpc_batch_small",
        "runtime_packaging_id": "hpc_apptainer_sif.aox_hmm_2026_05_30",
        "toolchain_id": "hmmer_3.4.hmmbuild.hpc_apptainer_sif:v1",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#hpc-evidence",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#parameter-inventory-hmmer-cli",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "bio_tools.hmmalign.hpc:v1": {
        "sdk_module": "bio_tools",
        "function_name": "hmmalign",
        "selected_backend": "hpc",
        "backend_category": "hpc_runner",
        "route_reason": "static_policy:v1",
        "resource_class": "hpc_batch_small",
        "runtime_packaging_id": "hpc_apptainer_sif.aox_hmm_2026_05_30",
        "toolchain_id": "hmmer_3.4.hmmalign.hpc_apptainer_sif:v1",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#hpc-evidence",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#parameter-inventory-hmmer-cli",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "bio_tools.hmmer_search_cli.disabled:v1": {
        "sdk_module": "bio_tools",
        "function_name": "hmmer_search_cli",
        "selected_backend": "disabled",
        "backend_category": "unsupported",
        "route_reason": "unsupported_in_s14",
        "resource_class": "unsupported",
        "runtime_packaging_id": "disabled",
        "toolchain_id": "disabled",
        "evidence_ref": "docs/v3/sessions/14-real-bio-tools-local-hpc-backends.md#declared-outputs--validators",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#parameter-inventory-hmmer-cli",
        "approval_requirement": {"required": False},
        "status": "disabled",
        "error_code": "unsupported_in_s14",
    },
    "structure_tools.fpocket.hpc:v1": {
        "sdk_module": "structure_tools",
        "function_name": "fpocket",
        "selected_backend": "hpc",
        "backend_category": "hpc_runner",
        "route_reason": "static_policy:v1",
        "resource_class": "hpc_batch_small",
        "runtime_packaging_id": "hpc_apptainer_sif.fpocket_2026_05_30",
        "toolchain_id": "fpocket_4.2.2.hpc_apptainer_sif:v1",
        "evidence_ref": "docs/v3/execution-pipeline-docs/hpc-fpocket.md#fpocket-with-hpc-placement",
        "parameter_inventory_ref": "docs/v3/execution-pipeline-docs/hpc-fpocket.md#parameters",
        "approval_requirement": {"required": True},
        "status": "ok",
    },
    "test.fixture_adapter:v1": {
        "sdk_module": "bio_tools",
        "function_name": "mafft",
        "selected_backend": "fixture",
        "backend_category": "host_local_tool",
        "route_reason": "unit_fixture_forbidden",
        "resource_class": "fixture",
        "runtime_packaging_id": "fixture",
        "toolchain_id": "fixture",
        "evidence_ref": "fixture",
        "parameter_inventory_ref": "fixture",
        "approval_requirement": {"required": False},
        "status": "ok",
    },
    "test.prerequisite_missing:v1": {
        "sdk_module": "bio_tools",
        "function_name": "mafft",
        "selected_backend": "hpc",
        "backend_category": "hpc_runner",
        "route_reason": "static_policy:v1",
        "resource_class": "hpc_batch_small",
        "runtime_packaging_id": "hpc_apptainer_sif.aox_hmm_2026_05_30",
        "toolchain_id": "mafft_7.525.hpc_apptainer_sif:v1",
        "evidence_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#hpc-evidence",
        "parameter_inventory_ref": "docs/v3/sessions/06-adapter-foundation-evidence.md#parameter-inventory-mafft",
        "approval_requirement": {"required": True},
        "status": "prerequisite_missing",
        "error_code": "operation_prerequisite_missing",
    },
}


__all__ = ["S12_ROUTE_POLICIES"]
